/******************************************
 * Code generated by GEB (Version: 2.2.0.0)
 * Template: Sistran.Core.Application.Collective.CollectiveLoadLog.dict v1.0
 * FileSize=5067 Header=258 CRC=3625229258
 ******************************************/
using Sistran.Core.Framework;
using Sistran.Core.Framework.DAF;
using System;
using System.Collections;
using System.Collections.Generic;

namespace Sistran.Core.Application.Collective.Entities
{
    /// <summary>
    /// Definición de entidad CollectiveLoadLog.
    /// </summary>
    [
    PersistentClass("Sistran.Core.Application.Collective.CollectiveLoadLog.dict"),
    Serializable(),
    DescriptionKey("COLLECTIVE_LOAD_LOG_ENTITY"),
    TableMap(TableName = "COLLECTIVE_LOAD_LOG", Schema = "COLL"),
    ]
    public partial class CollectiveLoadLog :
        BusinessObject2
    {
        #region static
        /// <summary>
        /// Propiedades públicas de la entidad.
        /// </summary>
        public static class Properties
        {
            public static readonly string Id = "Id";
            public static readonly string CollectiveLoadId = "CollectiveLoadId";
            public static readonly string Description = "Description";
            public static readonly string Time = "Time";
        }

        /// <summary>
        /// Crea una clave primaria para una clase concreta.
        /// </summary>
        /// <param name="concreteClass">Clase concreta.</param>
        /// <param name="id">Propiedad clave Id.</param>
        /// <returns>Clave primaria.</returns>
        protected static PrimaryKey InternalCreatePrimaryKey<T>(int id)
        {
            Dictionary<string, object> keys = new Dictionary<string, object>();
            keys.Add(Properties.Id, id);

            return new PrimaryKey<T>(keys);
        }

        /// <summary>
        /// Crea una clave primaria para esta clase.
        /// </summary>
        /// <param name="id">Propiedad clave Id.</param>
        public static PrimaryKey CreatePrimaryKey(int id)
        {
            return InternalCreatePrimaryKey<CollectiveLoadLog>(id);
        }
        #endregion

        //*** Object Attributes ********************************

        /// <summary>
        /// Atributo para la propiedad CollectiveLoadId.
        /// </summary>
        private int _collectiveLoadId;
        /// <summary>
        /// Atributo para la propiedad Description.
        /// </summary>
        private string _description = null;
        /// <summary>
        /// Atributo para la propiedad Time.
        /// </summary>
        private DateTime _time;
        //*** Object Constructors ********************************

        /// <summary>
        /// Constructor de instancia de la clase en base a las propiedades claves.
        /// </summary>
        /// <param name="id">Id key property.</param>
        public CollectiveLoadLog(int id) :
            this(CollectiveLoadLog.CreatePrimaryKey(id), null)
        {
        }

        /// <summary>
        /// Constructor de instancia de la clase en base a una clave primaria y a valores iniciales.
        /// </summary>
        /// <param name="key">
        /// Identificador de la instancia de la entidad.
        /// </param>
        /// <param name="initialValues">
        /// Valores para establecer el estado de la instancia.
        /// </param>
        public CollectiveLoadLog(PrimaryKey key, IDictionary initialValues) :
            base(key, initialValues)
        {
        }

        /*** Object Properties ********************************/
        /// <summary>
        /// Devuelve o setea el valor de la propiedad Id.
        /// </summary>
        /// <value>Propiedad Id.</value>
        [
        DescriptionKey("ID_PROPERTY"),
        PersistentProperty(IsKey = true),
        ColumnMap(ColumnName = "ID", DbType = System.Data.DbType.String),
        ]
        public int Id
        {
            get
            {
                return (int)this._primaryKey[Properties.Id];
            }
            set
            {
                this._primaryKey[Properties.Id] = value;
            }
        }

        /// <summary>
        /// Devuelve o setea el valor de la propiedad CollectiveLoadId.
        /// </summary>
        /// <value>Propiedad CollectiveLoadId.</value>
        [
        DescriptionKey("COLLECTIVE_LOAD_ID_PROPERTY"),
        PersistentProperty(),
        ColumnMap(ColumnName = "COLLECTIVE_LOAD_ID", DbType = System.Data.DbType.String),
        ]
        public int CollectiveLoadId
        {
            get
            {
                return this._collectiveLoadId;
            }
            set
            {
                this._collectiveLoadId = value;
            }
        }

        /// <summary>
        /// Devuelve o setea el valor de la propiedad Description.
        /// </summary>
        /// <value>Propiedad Description.</value>
        [
        DescriptionKey("DESCRIPTION_PROPERTY"),
        PersistentProperty(),
        ColumnMap(ColumnName = "DESCRIPTION", DbType = System.Data.DbType.String),
        ]
        public string Description
        {
            get
            {
                return this._description;
            }
            set
            {
                if (value == null)
                {
                    throw new PropertyNotNullableException(this.GetType().FullName, Properties.Description);
                }
                this._description = value;
            }
        }

        /// <summary>
        /// Devuelve o setea el valor de la propiedad Time.
        /// </summary>
        /// <value>Propiedad Time.</value>
        [
        DescriptionKey("TIME_PROPERTY"),
        PersistentProperty(),
        ColumnMap(ColumnName = "TIME", DbType = System.Data.DbType.String),
        ]
        public DateTime Time
        {
            get
            {
                return this._time;
            }
            set
            {
                this._time = value;
            }
        }

    }
}