/******************************************
 * Code generated by GEB (Version: 2.2.0.0)
 * Template: Sistran.Core.Application.Temporary.TempRisk.dict v1.0
 * FileSize=20183 Header=249 CRC=1895531267
 ******************************************/
using Sistran.Core.Framework;
using Sistran.Core.Framework.DAF;
using System;
using System.Collections;
using System.Collections.Generic;

namespace Sistran.Core.Application.Temporary.Entities
{
    /// <summary>
    /// Definición de entidad TempRisk.
    /// </summary>
    [
    PersistentClass("Sistran.Core.Application.Temporary.TempRisk.dict"),
    Serializable(),
    DescriptionKey("TEMP_RISK_ENTITY"),
    TableMap(TableName = "TEMP_RISK", Schema = "TMP"),
    ]
    public partial class TempRisk :
        BusinessObject2
    {
        #region static
        /// <summary>
        /// Propiedades públicas de la entidad.
        /// </summary>
        public static class Properties
        {
            public static readonly string TempId = "TempId";
            public static readonly string RiskId = "RiskId";
            public static readonly string InsuredId = "InsuredId";
            public static readonly string CustomerTypeCode = "CustomerTypeCode";
            public static readonly string CoveredRiskTypeCode = "CoveredRiskTypeCode";
            public static readonly string RiskNumber = "RiskNumber";
            public static readonly string EndorsementId = "EndorsementId";
            public static readonly string PolicyId = "PolicyId";
            public static readonly string RiskStatusCode = "RiskStatusCode";
            public static readonly string RiskOriginalStatusCode = "RiskOriginalStatusCode";
            public static readonly string RiskInspectionTypeCode = "RiskInspectionTypeCode";
            public static readonly string InspectionId = "InspectionId";
            public static readonly string ConditionText = "ConditionText";
            public static readonly string RatingZoneCode = "RatingZoneCode";
            public static readonly string CoverageGroupId = "CoverageGroupId";
            public static readonly string PrefixCode = "PrefixCode";
            public static readonly string IsFacultative = "IsFacultative";
            public static readonly string NameNum = "NameNum";
            public static readonly string AddressId = "AddressId";
            public static readonly string PhoneId = "PhoneId";
            public static readonly string RiskCommercialClassCode = "RiskCommercialClassCode";
            public static readonly string RiskCommercialTypeCode = "RiskCommercialTypeCode";
            public static readonly string OperationId = "OperationId";
            public static readonly string SecondaryInsuredId = "SecondaryInsuredId";
        }

        /// <summary>
        /// Crea una clave primaria para una clase concreta.
        /// </summary>
        /// <param name="concreteClass">Clase concreta.</param>
        /// <param name="tempId">Propiedad clave TempId.</param>
        /// <param name="riskId">Propiedad clave RiskId.</param>
        /// <returns>Clave primaria.</returns>
        protected static PrimaryKey InternalCreatePrimaryKey<T>()
        {
            Dictionary<string, object> keys = new Dictionary<string, object>();
            keys.Add(Properties.TempId, null);
            keys.Add(Properties.RiskId, null);

            return new PrimaryKey<T>(keys);
        }

        /// <summary>
        /// Crea una clave primaria para una clase concreta.
        /// </summary>
        /// <param name="concreteClass">Clase concreta.</param>
        /// <param name="tempId">Propiedad clave TempId.</param>
        /// <param name="riskId">Propiedad clave RiskId.</param>
        /// <returns>Clave primaria.</returns>
        protected static PrimaryKey InternalCreatePrimaryKey<T>(int tempId, int riskId)
        {
            Dictionary<string, object> keys = new Dictionary<string, object>();
            keys.Add(Properties.TempId, tempId);
            keys.Add(Properties.RiskId, riskId);

            return new PrimaryKey<T>(keys);
        }

        /// <summary>
        /// Crea una clave primaria para esta clase.
        /// </summary>
        /// <param name="tempId">Propiedad clave TempId.</param>
        /// <param name="riskId">Propiedad clave RiskId.</param>
        public static PrimaryKey CreatePrimaryKey(int tempId, int riskId)
        {
            return InternalCreatePrimaryKey<TempRisk>(tempId, riskId);
        }

        /// <summary>
        /// Crea una clave primaria para esta clase.
        /// </summary>
        public static PrimaryKey CreatePrimaryKey()
        {
            return InternalCreatePrimaryKey<TempRisk>();
        }
        #endregion

        //*** Object Attributes ********************************

        /// <summary>
        /// Atributo para la propiedad InsuredId.
        /// </summary>
        private int? _insuredId = null;
        /// <summary>
        /// Atributo para la propiedad CustomerTypeCode.
        /// </summary>
        private int? _customerTypeCode = null;
        /// <summary>
        /// Atributo para la propiedad CoveredRiskTypeCode.
        /// </summary>
        private int _coveredRiskTypeCode;
        /// <summary>
        /// Atributo para la propiedad RiskNumber.
        /// </summary>
        private int? _riskNum = null;
        /// <summary>
        /// Atributo para la propiedad EndorsementId.
        /// </summary>
        private int? _endorsementId = null;
        /// <summary>
        /// Atributo para la propiedad PolicyId.
        /// </summary>
        private int? _policyId = null;
        /// <summary>
        /// Atributo para la propiedad RiskStatusCode.
        /// </summary>
        private int? _riskStatusCode = null;
        /// <summary>
        /// Atributo para la propiedad RiskOriginalStatusCode.
        /// </summary>
        private int? _riskOriginalStatusCode = null;
        /// <summary>
        /// Atributo para la propiedad RiskInspectionTypeCode.
        /// </summary>
        private int _riskInspTypeCode;
        /// <summary>
        /// Atributo para la propiedad InspectionId.
        /// </summary>
        private int? _inspectionId = null;
        /// <summary>
        /// Atributo para la propiedad ConditionText.
        /// </summary>
        private string _conditionText = null;
        /// <summary>
        /// Atributo para la propiedad RatingZoneCode.
        /// </summary>
        private int? _ratingZoneCode = null;
        /// <summary>
        /// Atributo para la propiedad CoverageGroupId.
        /// </summary>
        private int? _coverGroupId = null;
        /// <summary>
        /// Atributo para la propiedad PrefixCode.
        /// </summary>
        private int? _prefixCode = null;
        /// <summary>
        /// Atributo para la propiedad IsFacultative.
        /// </summary>
        private bool _isFacultative;
        /// <summary>
        /// Atributo para la propiedad NameNum.
        /// </summary>
        private int? _nameNum = null;
        /// <summary>
        /// Atributo para la propiedad AddressId.
        /// </summary>
        private int? _addressId = null;
        /// <summary>
        /// Atributo para la propiedad PhoneId.
        /// </summary>
        private int? _phoneId = null;
        /// <summary>
        /// Atributo para la propiedad RiskCommercialClassCode.
        /// </summary>
        private int? _riskCommercialClassCode = null;
        /// <summary>
        /// Atributo para la propiedad RiskCommercialTypeCode.
        /// </summary>
        private int? _riskCommercialTypeCode = null;
        /// <summary>
        /// Atributo para la propiedad OperationId.
        /// </summary>
        private int? _operationId = null;

        /// <summary>
        /// Atributo para la propiedad SecondaryInsuredId.
        /// </summary>
        private int? _secondaryInsuredId = null;
        //*** Object Constructors ********************************

        /// <summary>
        /// Constructor de instancia de la clase en base a las propiedades claves.
        /// </summary>
        /// <param name="tempId">TempId key property.</param>
        /// <param name="riskId">RiskId key property.</param>
        public TempRisk(int tempId, int riskId) :
            this(TempRisk.CreatePrimaryKey(tempId, riskId), null)
        {
        }

        /// <summary>
        /// Constructor de instancia de la clase en base a una clave primaria y a valores iniciales.
        /// </summary>
        /// <param name="key">
        /// Identificador de la instancia de la entidad.
        /// </param>
        /// <param name="initialValues">
        /// Valores para establecer el estado de la instancia.
        /// </param>
        public TempRisk(PrimaryKey key, IDictionary initialValues) :
            base(key, initialValues)
        {
        }

        public TempRisk() :
            this(TempRisk.CreatePrimaryKey(), null)
        {
        }

        /*** Object Properties ********************************/
        /// <summary>
        /// Devuelve o setea el valor de la propiedad TempId.
        /// </summary>
        /// <value>Propiedad TempId.</value>
        [
        DescriptionKey("TEMP_ID_PROPERTY"),
        PersistentProperty(IsKey = true),
        ColumnMap(ColumnName = "TEMP_ID", DbType = System.Data.DbType.String),
        ]
        public int TempId
        {
            get
            {
                return (int)this._primaryKey[Properties.TempId];
            }
            set
            {
                this._primaryKey[Properties.TempId] = value;
            }
        }

        /// <summary>
        /// Devuelve o setea el valor de la propiedad RiskId.
        /// </summary>
        /// <value>Propiedad RiskId.</value>
        [
        DescriptionKey("RISK_ID_PROPERTY"),
        PersistentProperty(IsKey = true),
        ColumnMap(ColumnName = "RISK_ID", DbType = System.Data.DbType.String),
        ]
        public int RiskId
        {
            get
            {
                return (int)this._primaryKey[Properties.RiskId];
            }
            set
            {
                this._primaryKey[Properties.RiskId] = value;
            }
        }

        /// <summary>
        /// Devuelve o setea el valor de la propiedad InsuredId.
        /// </summary>
        /// <value>Propiedad InsuredId.</value>
        [
        DescriptionKey("INSURED_ID_PROPERTY"),
        PersistentProperty(IsNullable = true),
        ColumnMap(ColumnName = "INSURED_ID", DbType = System.Data.DbType.String),
        ]
        public int? InsuredId
        {
            get
            {
                return this._insuredId;
            }
            set
            {
                this._insuredId = value;
            }
        }

        /// <summary>
        /// Devuelve o setea el valor de la propiedad CustomerTypeCode.
        /// </summary>
        /// <value>Propiedad CustomerTypeCode.</value>
        [
        DescriptionKey("CUSTOMER_TYPE_CODE_PROPERTY"),
        PersistentProperty(IsNullable = true),
        ColumnMap(ColumnName = "CUSTOMER_TYPE_CD", DbType = System.Data.DbType.String),
        ]
        public int? CustomerTypeCode
        {
            get
            {
                return this._customerTypeCode;
            }
            set
            {
                this._customerTypeCode = value;
            }
        }

        /// <summary>
        /// Devuelve o setea el valor de la propiedad CoveredRiskTypeCode.
        /// </summary>
        /// <value>Propiedad CoveredRiskTypeCode.</value>
        [
        DescriptionKey("COVERED_RISK_TYPE_CODE_PROPERTY"),
        PersistentProperty(),
        ColumnMap(ColumnName = "COVERED_RISK_TYPE_CD", DbType = System.Data.DbType.String),
        ]
        public int CoveredRiskTypeCode
        {
            get
            {
                return this._coveredRiskTypeCode;
            }
            set
            {
                this._coveredRiskTypeCode = value;
            }
        }

        /// <summary>
        /// Devuelve o setea el valor de la propiedad RiskNumber.
        /// </summary>
        /// <value>Propiedad RiskNumber.</value>
        [
        DescriptionKey("RISK_NUM_PROPERTY"),
        PersistentProperty(IsNullable = true),
        ColumnMap(ColumnName = "RISK_NUM", DbType = System.Data.DbType.String),
        ]
        public int? RiskNumber
        {
            get
            {
                return this._riskNum;
            }
            set
            {
                this._riskNum = value;
            }
        }

        /// <summary>
        /// Devuelve o setea el valor de la propiedad EndorsementId.
        /// </summary>
        /// <value>Propiedad EndorsementId.</value>
        [
        DescriptionKey("ENDORSEMENT_ID_PROPERTY"),
        PersistentProperty(IsNullable = true),
        ColumnMap(ColumnName = "ENDORSEMENT_ID", DbType = System.Data.DbType.String),
        ]
        public int? EndorsementId
        {
            get
            {
                return this._endorsementId;
            }
            set
            {
                this._endorsementId = value;
            }
        }

        /// <summary>
        /// Devuelve o setea el valor de la propiedad PolicyId.
        /// </summary>
        /// <value>Propiedad PolicyId.</value>
        [
        DescriptionKey("POLICY_ID_PROPERTY"),
        PersistentProperty(IsNullable = true),
        ColumnMap(ColumnName = "POLICY_ID", DbType = System.Data.DbType.String),
        ]
        public int? PolicyId
        {
            get
            {
                return this._policyId;
            }
            set
            {
                this._policyId = value;
            }
        }

        /// <summary>
        /// Devuelve o setea el valor de la propiedad RiskStatusCode.
        /// </summary>
        /// <value>Propiedad RiskStatusCode.</value>
        [
        DescriptionKey("RISK_STATUS_CODE_PROPERTY"),
        PersistentProperty(IsNullable = true),
        ColumnMap(ColumnName = "RISK_STATUS_CD", DbType = System.Data.DbType.String),
        ]
        public int? RiskStatusCode
        {
            get
            {
                return this._riskStatusCode;
            }
            set
            {
                this._riskStatusCode = value;
            }
        }

        /// <summary>
        /// Devuelve o setea el valor de la propiedad RiskOriginalStatusCode.
        /// </summary>
        /// <value>Propiedad RiskOriginalStatusCode.</value>
        [
        DescriptionKey("RISK_ORIGINAL_STATUS_CODE_PROPERTY"),
        PersistentProperty(IsNullable = true),
        ColumnMap(ColumnName = "RISK_ORIGINAL_STATUS_CD", DbType = System.Data.DbType.String),
        ]
        public int? RiskOriginalStatusCode
        {
            get
            {
                return this._riskOriginalStatusCode;
            }
            set
            {
                this._riskOriginalStatusCode = value;
            }
        }

        /// <summary>
        /// Devuelve o setea el valor de la propiedad RiskInspectionTypeCode.
        /// </summary>
        /// <value>Propiedad RiskInspectionTypeCode.</value>
        [
        DescriptionKey("RISK_INSP_TYPE_CODE_PROPERTY"),
        PersistentProperty(),
        ColumnMap(ColumnName = "RISK_INSP_TYPE_CD", DbType = System.Data.DbType.String),
        ]
        public int RiskInspectionTypeCode
        {
            get
            {
                return this._riskInspTypeCode;
            }
            set
            {
                this._riskInspTypeCode = value;
            }
        }

        /// <summary>
        /// Devuelve o setea el valor de la propiedad InspectionId.
        /// </summary>
        /// <value>Propiedad InspectionId.</value>
        [
        DescriptionKey("INSPECTION_ID_PROPERTY"),
        PersistentProperty(IsNullable = true),
        ColumnMap(ColumnName = "INSPECTION_ID", DbType = System.Data.DbType.String),
        ]
        public int? InspectionId
        {
            get
            {
                return this._inspectionId;
            }
            set
            {
                this._inspectionId = value;
            }
        }

        /// <summary>
        /// Devuelve o setea el valor de la propiedad ConditionText.
        /// </summary>
        /// <value>Propiedad ConditionText.</value>
        [
        DescriptionKey("CONDITION_TEXT_PROPERTY"),
        PersistentProperty(IsNullable = true),
        ColumnMap(ColumnName = "CONDITION_TEXT", DbType = System.Data.DbType.String),
        ]
        public string ConditionText
        {
            get
            {
                return this._conditionText;
            }
            set
            {
                this._conditionText = value;
            }
        }

        /// <summary>
        /// Devuelve o setea el valor de la propiedad RatingZoneCode.
        /// </summary>
        /// <value>Propiedad RatingZoneCode.</value>
        [
        DescriptionKey("RATING_ZONE_CODE_PROPERTY"),
        PersistentProperty(IsNullable = true),
        ColumnMap(ColumnName = "RATING_ZONE_CD", DbType = System.Data.DbType.String),
        ]
        public int? RatingZoneCode
        {
            get
            {
                return this._ratingZoneCode;
            }
            set
            {
                this._ratingZoneCode = value;
            }
        }

        /// <summary>
        /// Devuelve o setea el valor de la propiedad CoverageGroupId.
        /// </summary>
        /// <value>Propiedad CoverageGroupId.</value>
        [
        DescriptionKey("COVER_GROUP_ID_PROPERTY"),
        PersistentProperty(IsNullable = true),
        ColumnMap(ColumnName = "COVER_GROUP_ID", DbType = System.Data.DbType.String),
        ]
        public int? CoverageGroupId
        {
            get
            {
                return this._coverGroupId;
            }
            set
            {
                this._coverGroupId = value;
            }
        }

        /// <summary>
        /// Devuelve o setea el valor de la propiedad PrefixCode.
        /// </summary>
        /// <value>Propiedad PrefixCode.</value>
        [
        DescriptionKey("PREFIX_CODE_PROPERTY"),
        PersistentProperty(IsNullable = true),
        ColumnMap(ColumnName = "PREFIX_CD", DbType = System.Data.DbType.String),
        ]
        public int? PrefixCode
        {
            get
            {
                return this._prefixCode;
            }
            set
            {
                this._prefixCode = value;
            }
        }

        /// <summary>
        /// Devuelve o setea el valor de la propiedad IsFacultative.
        /// </summary>
        /// <value>Propiedad IsFacultative.</value>
        [
        DescriptionKey("IS_FACULTATIVE_PROPERTY"),
        PersistentProperty(),
        ColumnMap(ColumnName = "IS_FACULTATIVE", DbType = System.Data.DbType.String),
        ]
        public bool IsFacultative
        {
            get
            {
                return this._isFacultative;
            }
            set
            {
                this._isFacultative = value;
            }
        }

        /// <summary>
        /// Devuelve o setea el valor de la propiedad NameNum.
        /// </summary>
        /// <value>Propiedad NameNum.</value>
        [
        DescriptionKey("NAME_NUM_PROPERTY"),
        PersistentProperty(IsNullable = true),
        ColumnMap(ColumnName = "NAME_NUM", DbType = System.Data.DbType.String),
        ]
        public int? NameNum
        {
            get
            {
                return this._nameNum;
            }
            set
            {
                this._nameNum = value;
            }
        }

        /// <summary>
        /// Devuelve o setea el valor de la propiedad AddressId.
        /// </summary>
        /// <value>Propiedad AddressId.</value>
        [
        DescriptionKey("ADDRESS_ID_PROPERTY"),
        PersistentProperty(IsNullable = true),
        ColumnMap(ColumnName = "ADDRESS_ID", DbType = System.Data.DbType.String),
        ]
        public int? AddressId
        {
            get
            {
                return this._addressId;
            }
            set
            {
                this._addressId = value;
            }
        }

        /// <summary>
        /// Devuelve o setea el valor de la propiedad PhoneId.
        /// </summary>
        /// <value>Propiedad PhoneId.</value>
        [
        DescriptionKey("PHONE_ID_PROPERTY"),
        PersistentProperty(IsNullable = true),
        ColumnMap(ColumnName = "PHONE_ID", DbType = System.Data.DbType.String),
        ]
        public int? PhoneId
        {
            get
            {
                return this._phoneId;
            }
            set
            {
                this._phoneId = value;
            }
        }

        /// <summary>
        /// Devuelve o setea el valor de la propiedad RiskCommercialClassCode.
        /// </summary>
        /// <value>Propiedad RiskCommercialClassCode.</value>
        [
        DescriptionKey("RISK_COMMERCIAL_CLASS_CODE_PROPERTY"),
        PersistentProperty(IsNullable = true),
        ColumnMap(ColumnName = "RISK_COMMERCIAL_CLASS_CD", DbType = System.Data.DbType.String),
        ]
        public int? RiskCommercialClassCode
        {
            get
            {
                return this._riskCommercialClassCode;
            }
            set
            {
                this._riskCommercialClassCode = value;
            }
        }

        /// <summary>
        /// Devuelve o setea el valor de la propiedad RiskCommercialTypeCode.
        /// </summary>
        /// <value>Propiedad RiskCommercialTypeCode.</value>
        [
        DescriptionKey("RISK_COMMERCIAL_TYPE_CODE_PROPERTY"),
        PersistentProperty(IsNullable = true),
        ColumnMap(ColumnName = "RISK_COMMERCIAL_TYPE_CD", DbType = System.Data.DbType.String),
        ]
        public int? RiskCommercialTypeCode
        {
            get
            {
                return this._riskCommercialTypeCode;
            }
            set
            {
                this._riskCommercialTypeCode = value;
            }
        }

        /// <summary>
        /// Devuelve o setea el valor de la propiedad OperationId.
        /// </summary>
        /// <value>Propiedad OperationId.</value>
        [
        DescriptionKey("OPERATION_ID_PROPERTY"),
        PersistentProperty(IsNullable = true),
        ColumnMap(ColumnName = "OPERATION_ID", DbType = System.Data.DbType.String),
        ]
        public int? OperationId
        {
            get
            {
                return this._operationId;
            }
            set
            {
                this._operationId = value;
            }
        }



        /// <summary>
        /// Devuelve o setea el valor de la propiedad SecondaryInsuredId.
        /// </summary>
        /// <value>Propiedad SecondaryInsuredId.</value>
        [
        DescriptionKey("SECONDARY_INSURED_ID_PROPERTY"),
        PersistentProperty(IsNullable = true),
        ColumnMap(ColumnName = "SECONDARY_INSURED_ID", DbType = System.Data.DbType.String),
        ]
        public int? SecondaryInsuredId
        {
            get
            {
                return this._secondaryInsuredId;
            }
            set
            {
                this._secondaryInsuredId = value;
            }
        }

    }
}