/******************************************
 * Code generated by GEB (Version: 2.2.0.0)
 * Template: Sistran.Core.Application.MassiveServices.EEProvider.CoRequestEndorsementAgent.dict v1.0
 * FileSize=4472 Header=282 CRC=2958937221
 ******************************************/
using System;
using System.Collections;
using System.Collections.Generic;
using Sistran.Core.Framework;
using Sistran.Core.Framework.DAF;

namespace Sistran.Company.Application.MassiveServices.EEProvider.Entities
{
    /// <summary>
    /// Definición de entidad CoRequestEndorsementAgent.
    /// </summary>
    [
    PersistentClass("Sistran.Company.Application.MassiveServices.EEProvider.CoRequestEndorsementAgent.dict"),
    Serializable(),
    DescriptionKey("CO_REQUEST_ENDORSEMENT_AGENT_ENTITY"),
    TableMap(TableName="CO_REQUEST_ENDORSEMENT_AGENT", Schema="REQ"),
    ]
    public partial class CoRequestEndorsementAgent :
        BusinessObject2
    {
#region static
		/// <summary>
		/// Propiedades públicas de la entidad.
		/// </summary>
		public static class Properties
		{
			public static readonly string RequestEndorsementId = "RequestEndorsementId";
			public static readonly string RequestAgentId = "RequestAgentId";
		}

		/// <summary>
		/// Crea una clave primaria para una clase concreta.
		/// </summary>
		/// <param name="concreteClass">Clase concreta.</param>
		/// <param name="requestEndorsementId">Propiedad clave RequestEndorsementId.</param>
		/// <param name="requestAgentId">Propiedad clave RequestAgentId.</param>
		/// <returns>Clave primaria.</returns>
	    protected static PrimaryKey InternalCreatePrimaryKey<T>(int requestEndorsementId, int requestAgentId)
	    {
		    Dictionary<string, object> keys = new Dictionary<string, object>();
		    keys.Add(Properties.RequestEndorsementId, requestEndorsementId);
		    keys.Add(Properties.RequestAgentId, requestAgentId);

		    return new PrimaryKey<T>(keys);
	    }

		/// <summary>
		/// Crea una clave primaria para esta clase.
		/// </summary>
		/// <param name="requestEndorsementId">Propiedad clave RequestEndorsementId.</param>
		/// <param name="requestAgentId">Propiedad clave RequestAgentId.</param>
		public static PrimaryKey CreatePrimaryKey(int requestEndorsementId, int requestAgentId)
	    {
			return InternalCreatePrimaryKey<CoRequestEndorsementAgent>(requestEndorsementId, requestAgentId);
		}
#endregion

	    //*** Object Attributes ********************************

	    //*** Object Constructors ********************************

		/// <summary>
		/// Constructor de instancia de la clase en base a las propiedades claves.
		/// </summary>
		/// <param name="requestEndorsementId">RequestEndorsementId key property.</param>
		/// <param name="requestAgentId">RequestAgentId key property.</param>
	    public CoRequestEndorsementAgent(int requestEndorsementId, int requestAgentId):
			this(CoRequestEndorsementAgent.CreatePrimaryKey(requestEndorsementId, requestAgentId), null)
	    {
	    }

		/// <summary>
		/// Constructor de instancia de la clase en base a una clave primaria y a valores iniciales.
		/// </summary>
		/// <param name="key">
		/// Identificador de la instancia de la entidad.
		/// </param>
		/// <param name="initialValues">
		/// Valores para establecer el estado de la instancia.
		/// </param>
	    public CoRequestEndorsementAgent(PrimaryKey key, IDictionary initialValues):
			base(key, initialValues)
	    {
	    }

	    /*** Object Properties ********************************/
		/// <summary>
		/// Devuelve o setea el valor de la propiedad RequestEndorsementId.
		/// </summary>
		/// <value>Propiedad RequestEndorsementId.</value>
	    [
		DescriptionKey("REQUEST_ENDORSEMENT_ID_PROPERTY"),
		PersistentProperty(IsKey = true),
        ColumnMap(ColumnName="REQUEST_ENDORSEMENT_ID", DbType=System.Data.DbType.String),
	    ]
        public int RequestEndorsementId
	    {
		    get
		    {
				return (int)this._primaryKey[Properties.RequestEndorsementId];
		    }
		    set
		    {
				this._primaryKey[Properties.RequestEndorsementId] = value;
			}
	    }

		/// <summary>
		/// Devuelve o setea el valor de la propiedad RequestAgentId.
		/// </summary>
		/// <value>Propiedad RequestAgentId.</value>
	    [
		DescriptionKey("REQUEST_AGENT_ID_PROPERTY"),
		PersistentProperty(IsKey = true),
        ColumnMap(ColumnName="REQUEST_AGENT_ID", DbType=System.Data.DbType.String),
	    ]
        public int RequestAgentId
	    {
		    get
		    {
				return (int)this._primaryKey[Properties.RequestAgentId];
		    }
		    set
		    {
				this._primaryKey[Properties.RequestAgentId] = value;
			}
	    }

    }
}