/******************************************
 * Code generated by GEB (Version: 2.2.0.0)
 * Template: Sistran.Core.Application.ReconciliationServices.EEProvider.BankAccountCompanyFormat.dict v1.0
 * FileSize=5032 Header=288 CRC=2521740193
 ******************************************/
using System;
using System.Collections;
using System.Collections.Generic;
using Sistran.Core.Framework;
using Sistran.Core.Framework.DAF;

namespace Sistran.Core.Application.ReconciliationServices.EEProvider.Entities
{
    /// <summary>
    /// Definición de entidad BankAccountCompanyFormat.
    /// </summary>
    [
    PersistentClass("Sistran.Core.Application.ReconciliationServices.EEProvider.BankAccountCompanyFormat.dict"),
    Serializable(),
    DescriptionKey("BANK_ACCOUNT_COMPANY_FORMAT_ENTITY"),
    TableMap(TableName="BANK_ACCOUNT_COMPANY_FORMAT", Schema="GL"),
    ]
    public partial class BankAccountCompanyFormat :
        BusinessObject2
    {
#region static
		/// <summary>
		/// Propiedades públicas de la entidad.
		/// </summary>
		public static class Properties
		{
			public static readonly string BankAccountCompanyFormatId = "BankAccountCompanyFormatId";
			public static readonly string BankAccountCompanyCode = "BankAccountCompanyCode";
			public static readonly string FormatCode = "FormatCode";
		}

		/// <summary>
		/// Crea una clave primaria para una clase concreta.
		/// </summary>
		/// <param name="concreteClass">Clase concreta.</param>
		/// <param name="bankAccountCompanyFormatId">Propiedad clave BankAccountCompanyFormatId.</param>
		/// <returns>Clave primaria.</returns>
	    protected static PrimaryKey InternalCreatePrimaryKey<T>(int bankAccountCompanyFormatId)
	    {
		    Dictionary<string, object> keys = new Dictionary<string, object>();
		    keys.Add(Properties.BankAccountCompanyFormatId, bankAccountCompanyFormatId);

		    return new PrimaryKey<T>(keys);
	    }

		/// <summary>
		/// Crea una clave primaria para esta clase.
		/// </summary>
		/// <param name="bankAccountCompanyFormatId">Propiedad clave BankAccountCompanyFormatId.</param>
		public static PrimaryKey CreatePrimaryKey(int bankAccountCompanyFormatId)
	    {
			return InternalCreatePrimaryKey<BankAccountCompanyFormat>(bankAccountCompanyFormatId);
		}
#endregion

	    //*** Object Attributes ********************************

		/// <summary>
		/// Atributo para la propiedad BankAccountCompanyCode.
		/// </summary>
        private int _bankAccountCompanyCode;
		/// <summary>
		/// Atributo para la propiedad FormatCode.
		/// </summary>
        private int _formatCode;
	    //*** Object Constructors ********************************

		/// <summary>
		/// Constructor de instancia de la clase en base a las propiedades claves.
		/// </summary>
		/// <param name="bankAccountCompanyFormatId">BankAccountCompanyFormatId key property.</param>
	    public BankAccountCompanyFormat(int bankAccountCompanyFormatId):
			this(BankAccountCompanyFormat.CreatePrimaryKey(bankAccountCompanyFormatId), null)
	    {
	    }

		/// <summary>
		/// Constructor de instancia de la clase en base a una clave primaria y a valores iniciales.
		/// </summary>
		/// <param name="key">
		/// Identificador de la instancia de la entidad.
		/// </param>
		/// <param name="initialValues">
		/// Valores para establecer el estado de la instancia.
		/// </param>
	    public BankAccountCompanyFormat(PrimaryKey key, IDictionary initialValues):
			base(key, initialValues)
	    {
	    }

	    /*** Object Properties ********************************/
		/// <summary>
		/// Devuelve o setea el valor de la propiedad BankAccountCompanyFormatId.
		/// </summary>
		/// <value>Propiedad BankAccountCompanyFormatId.</value>
	    [
		DescriptionKey("BANK_ACCOUNT_COMPANY_FORMAT_ID_PROPERTY"),
		PersistentProperty(IsKey = true),
        ColumnMap(ColumnName="BANK_ACCOUNT_COMPANY_FORMAT_ID", DbType=System.Data.DbType.String),
	    ]
        public int BankAccountCompanyFormatId
	    {
		    get
		    {
				return (int)this._primaryKey[Properties.BankAccountCompanyFormatId];
		    }
		    set
		    {
				this._primaryKey[Properties.BankAccountCompanyFormatId] = value;
			}
	    }

		/// <summary>
		/// Devuelve o setea el valor de la propiedad BankAccountCompanyCode.
		/// </summary>
		/// <value>Propiedad BankAccountCompanyCode.</value>
	    [
		DescriptionKey("BANK_ACCOUNT_COMPANY_CODE_PROPERTY"),
		PersistentProperty(),
        ColumnMap(ColumnName="BANK_ACCOUNT_COMPANY_CD", DbType=System.Data.DbType.String),
	    ]
        public int BankAccountCompanyCode
	    {
		    get
		    {
			    return this._bankAccountCompanyCode;
		    }
		    set
		    {
				this._bankAccountCompanyCode = value;
			}
	    }

		/// <summary>
		/// Devuelve o setea el valor de la propiedad FormatCode.
		/// </summary>
		/// <value>Propiedad FormatCode.</value>
	    [
		DescriptionKey("FORMAT_CODE_PROPERTY"),
		PersistentProperty(),
        ColumnMap(ColumnName="FORMAT_CD", DbType=System.Data.DbType.String),
	    ]
        public int FormatCode
	    {
		    get
		    {
			    return this._formatCode;
		    }
		    set
		    {
				this._formatCode = value;
			}
	    }

    }
}