///////////////////////////////////////////////////////////
//  BeneficiaryTypeDTO.cs
//  Implementation of the Class BeneficiaryTypeDTO
//  Generated by Enterprise Architect
//  Created on:      22-jun.-2018 3:52:10 p. m.
//  Original author: jpertuz
///////////////////////////////////////////////////////////

using System.Runtime.Serialization;

namespace Sistran.Company.Application.Aircrafts.AircraftApplicationService.DTOs
{
    /// <summary>
    /// Información referente a tipo de beneficiario
    /// </summary>
	[DataContract]
	public class BeneficiaryTypeDTO
    {
        /// <summary>
        /// Identificador del tipo de beneficiario
        /// </summary>
		[DataMember]
		public string Id { get; set; }

        /// <summary>
        /// Descripción del tipo de beneficiario
        /// </summary>
		[DataMember]
		public string Description { get; set; }

        public BeneficiaryTypeDTO()
        {

        }
    }//end BeneficiaryTypeDTO
}//end namespace DTOs