/******************************************
 * Code generated by GEB (Version: 2.2.0.0)
 * Template: Sistran.Core.Application.Parameters.ConditionLevel.dict v1.0
 * FileSize=5401 Header=255 CRC=2604294212
 ******************************************/
using Sistran.Core.Framework;
using Sistran.Core.Framework.DAF;
using System;
using System.Collections;
using System.Collections.Generic;

namespace Sistran.Core.Application.Parameters.Entities
{
    /// <summary>
    /// Definición de entidad ConditionLevel.
    /// </summary>
    [
    PersistentClass("Sistran.Core.Application.Parameters.ConditionLevel.dict"),
    Serializable(),
    DescriptionKey("CONDITION_LEVEL_ENTITY"),
    TableMap(TableName = "CONDITION_LEVEL", Schema = "PARAM"),
    ]
    public partial class ConditionLevel :
        BusinessObject2
    {
        #region static
        /// <summary>
        /// Propiedades públicas de la entidad.
        /// </summary>
        public static class Properties
        {
            public static readonly string ConditionLevelCode = "ConditionLevelCode";
            public static readonly string SmallDescription = "SmallDescription";
            public static readonly string LevelId = "LevelId";
            public static readonly string PackageId = "PackageId";
        }

        /// <summary>
        /// Crea una clave primaria para una clase concreta.
        /// </summary>
        /// <param name="concreteClass">Clase concreta.</param>
        /// <param name="conditionLevelCode">Propiedad clave ConditionLevelCode.</param>
        /// <returns>Clave primaria.</returns>
        protected static PrimaryKey InternalCreatePrimaryKey<T>(int conditionLevelCode)
        {
            Dictionary<string, object> keys = new Dictionary<string, object>();
            keys.Add(Properties.ConditionLevelCode, conditionLevelCode);

            return new PrimaryKey<T>(keys);
        }

        protected static PrimaryKey InternalCreatePrimaryKey<T>()
        {
            Dictionary<string, object> keys = new Dictionary<string, object>();
            keys.Add(Properties.ConditionLevelCode, null);

            return new PrimaryKey<T>(keys);
        }

        /// <summary>
        /// Crea una clave primaria para esta clase.
        /// </summary>
        /// <param name="conditionLevelCode">Propiedad clave ConditionLevelCode.</param>
        public static PrimaryKey CreatePrimaryKey(int conditionLevelCode)
        {
            return InternalCreatePrimaryKey<ConditionLevel>(conditionLevelCode);
        }

        public static PrimaryKey CreatePrimaryKey()
        {
            return InternalCreatePrimaryKey<ConditionLevel>();
        }
        #endregion

        //*** Object Attributes ********************************

        /// <summary>
        /// Atributo para la propiedad SmallDescription.
        /// </summary>
        private string _smallDescription = null;
        /// <summary>
        /// Atributo para la propiedad LevelId.
        /// </summary>
        private int _levelId;
        /// <summary>
        /// Atributo para la propiedad PackageId.
        /// </summary>
        private int _packageId;
        //*** Object Constructors ********************************

        /// <summary>
        /// Constructor de instancia de la clase en base a las propiedades claves.
        /// </summary>
        /// <param name="conditionLevelCode">ConditionLevelCode key property.</param>
        public ConditionLevel(int conditionLevelCode) :
            this(ConditionLevel.CreatePrimaryKey(conditionLevelCode), null)
        {
        }

        public ConditionLevel() :
            this(ConditionLevel.CreatePrimaryKey(), null)
        {
        }

        /// <summary>
        /// Constructor de instancia de la clase en base a una clave primaria y a valores iniciales.
        /// </summary>
        /// <param name="key">
        /// Identificador de la instancia de la entidad.
        /// </param>
        /// <param name="initialValues">
        /// Valores para establecer el estado de la instancia.
        /// </param>
        public ConditionLevel(PrimaryKey key, IDictionary initialValues) :
            base(key, initialValues)
        {
        }

        /*** Object Properties ********************************/
        /// <summary>
        /// Devuelve o setea el valor de la propiedad ConditionLevelCode.
        /// </summary>
        /// <value>Propiedad ConditionLevelCode.</value>
        [
        DescriptionKey("CONDITION_LEVEL_CODE_PROPERTY"),
        PersistentProperty(IsKey = true, KeyType = "None"),
        ColumnMap(ColumnName = "CONDITION_LEVEL_CD", DbType = System.Data.DbType.String),
        ]
        public int ConditionLevelCode
        {
            get
            {
                return (int)this._primaryKey[Properties.ConditionLevelCode];
            }
            set
            {
                this._primaryKey[Properties.ConditionLevelCode] = value;
            }
        }

        /// <summary>
        /// Devuelve o setea el valor de la propiedad SmallDescription.
        /// </summary>
        /// <value>Propiedad SmallDescription.</value>
        [
        DescriptionKey("SMALL_DESCRIPTION_PROPERTY"),
        PersistentProperty(),
        ColumnMap(ColumnName = "SMALL_DESCRIPTION", DbType = System.Data.DbType.String),
        ]
        public string SmallDescription
        {
            get
            {
                return this._smallDescription;
            }
            set
            {
                if (value == null)
                {
                    throw new PropertyNotNullableException(this.GetType().FullName, Properties.SmallDescription);
                }
                this._smallDescription = value;
            }
        }

        /// <summary>
        /// Devuelve o setea el valor de la propiedad LevelId.
        /// </summary>
        /// <value>Propiedad LevelId.</value>
        [
        DescriptionKey("LEVEL_ID_PROPERTY"),
        PersistentProperty(),
        ColumnMap(ColumnName = "LEVEL_ID", DbType = System.Data.DbType.String),
        ]
        public int LevelId
        {
            get
            {
                return this._levelId;
            }
            set
            {
                this._levelId = value;
            }
        }

        /// <summary>
        /// Devuelve o setea el valor de la propiedad PackageId.
        /// </summary>
        /// <value>Propiedad PackageId.</value>
        [
        DescriptionKey("PACKAGE_ID_PROPERTY"),
        PersistentProperty(),
        ColumnMap(ColumnName = "PACKAGE_ID", DbType = System.Data.DbType.String),
        ]
        public int PackageId
        {
            get
            {
                return this._packageId;
            }
            set
            {
                this._packageId = value;
            }
        }

    }
}