/******************************************
 * Code generated by GEB (Version: 2.2.0.0)
 * Template: Sistran.Core.Application.Parameters.EstimationTypeInternalStatus.dict v1.0
 * FileSize=4217 Header=269 CRC=1796679846
 ******************************************/
using System;
using System.Collections;
using System.Collections.Generic;
using Sistran.Core.Framework;
using Sistran.Core.Framework.DAF;

namespace Sistran.Core.Application.Parameters.Entities
{
    /// <summary>
    /// Definición de entidad EstimationTypeInternalStatus.
    /// </summary>
    [
    PersistentClass("Sistran.Core.Application.Parameters.EstimationTypeInternalStatus.dict"),
    Serializable(),
    DescriptionKey("ESTIMATION_TYPE_INTERNAL_STATUS_ENTITY"),
    TableMap(TableName="ESTIMATION_TYPE_INTERNAL_STATUS", Schema="PARAM"),
    ]
    public partial class EstimationTypeInternalStatus :
        BusinessObject2
    {
#region static
		/// <summary>
		/// Propiedades públicas de la entidad.
		/// </summary>
		public static class Properties
		{
			public static readonly string InternalStatusCode = "InternalStatusCode";
			public static readonly string Description = "Description";
		}

		/// <summary>
		/// Crea una clave primaria para una clase concreta.
		/// </summary>
		/// <param name="concreteClass">Clase concreta.</param>
		/// <param name="internalStatusCode">Propiedad clave InternalStatusCode.</param>
		/// <returns>Clave primaria.</returns>
	    protected static PrimaryKey InternalCreatePrimaryKey<T>(int internalStatusCode)
	    {
		    Dictionary<string, object> keys = new Dictionary<string, object>();
		    keys.Add(Properties.InternalStatusCode, internalStatusCode);

		    return new PrimaryKey<T>(keys);
	    }

        protected static PrimaryKey InternalCreatePrimaryKey<T>()
        {
            Dictionary<string, object> keys = new Dictionary<string, object>();
            keys.Add(Properties.InternalStatusCode, null);

            return new PrimaryKey<T>(keys);
        }

        /// <summary>
        /// Crea una clave primaria para esta clase.
        /// </summary>
        /// <param name="internalStatusCode">Propiedad clave InternalStatusCode.</param>
        public static PrimaryKey CreatePrimaryKey(int internalStatusCode)
	    {
			return InternalCreatePrimaryKey<EstimationTypeInternalStatus>(internalStatusCode);
		}
        public static PrimaryKey CreatePrimaryKey()
        {
            return InternalCreatePrimaryKey<EstimationTypeInternalStatus>();
        }
        #endregion

        //*** Object Attributes ********************************

        /// <summary>
        /// Atributo para la propiedad Description.
        /// </summary>
        private string _description = null;
	    //*** Object Constructors ********************************

		/// <summary>
		/// Constructor de instancia de la clase en base a las propiedades claves.
		/// </summary>
		/// <param name="internalStatusCode">InternalStatusCode key property.</param>
	    public EstimationTypeInternalStatus(int internalStatusCode):
			this(EstimationTypeInternalStatus.CreatePrimaryKey(internalStatusCode), null)
	    {
	    }

        public EstimationTypeInternalStatus() :
            this(EstimationTypeInternalStatus.CreatePrimaryKey(), null)
        {
        }

        /// <summary>
        /// Constructor de instancia de la clase en base a una clave primaria y a valores iniciales.
        /// </summary>
        /// <param name="key">
        /// Identificador de la instancia de la entidad.
        /// </param>
        /// <param name="initialValues">
        /// Valores para establecer el estado de la instancia.
        /// </param>
        public EstimationTypeInternalStatus(PrimaryKey key, IDictionary initialValues):
			base(key, initialValues)
	    {
	    }

	    /*** Object Properties ********************************/
		/// <summary>
		/// Devuelve o setea el valor de la propiedad InternalStatusCode.
		/// </summary>
		/// <value>Propiedad InternalStatusCode.</value>
	    [
		DescriptionKey("INTERNAL_STATUS_CODE_PROPERTY"),
		PersistentProperty(IsKey = true, KeyType = "None"),
        ColumnMap(ColumnName="INTERNAL_STATUS_CD", DbType=System.Data.DbType.String),
	    ]
        public int InternalStatusCode
	    {
		    get
		    {
				return (int)this._primaryKey[Properties.InternalStatusCode];
		    }
		    set
		    {
				this._primaryKey[Properties.InternalStatusCode] = value;
			}
	    }

		/// <summary>
		/// Devuelve o setea el valor de la propiedad Description.
		/// </summary>
		/// <value>Propiedad Description.</value>
	    [
		DescriptionKey("DESCRIPTION_PROPERTY"),
		PersistentProperty(),
        ColumnMap(ColumnName="DESCRIPTION", DbType=System.Data.DbType.String),
	    ]
        public string Description
	    {
		    get
		    {
			    return this._description;
		    }
		    set
		    {
				if(value == null)
				{
					throw new PropertyNotNullableException(this.GetType().FullName, Properties.Description);
				}
				this._description = value;
			}
	    }

    }
}