/******************************************
 * Code generated by GEB (Version: 2.2.0.0)
 * Template: Sistran.Core.Application.Parameters.HardComponent.dict v1.0
 * FileSize=3164 Header=254 CRC=2661178799
 ******************************************/
using Sistran.Core.Framework;
using Sistran.Core.Framework.DAF;
using System;
using System.Collections;
using System.Collections.Generic;

namespace Sistran.Core.Application.Parameters.Entities
{
    /// <summary>
    /// Definición de entidad HardComponent.
    /// </summary>
    [
    PersistentClass("Sistran.Core.Application.Parameters.HardComponent.dict"),
    Serializable(),
    DescriptionKey("HARD_COMPONENT_ENTITY"),
    TableMap(TableName = "HARD_COMPONENT", Schema = "PARAM"),
    ]
    public partial class HardComponent :
        BusinessObject2
    {
        #region static
        /// <summary>
        /// Propiedades públicas de la entidad.
        /// </summary>
        public static class Properties
        {
            public static readonly string ComponentCode = "ComponentCode";
        }

        /// <summary>
        /// Crea una clave primaria para una clase concreta.
        /// </summary>
        /// <param name="concreteClass">Clase concreta.</param>
        /// <param name="componentCode">Propiedad clave ComponentCode.</param>
        /// <returns>Clave primaria.</returns>
        protected static PrimaryKey InternalCreatePrimaryKey<T>(int componentCode)
        {
            Dictionary<string, object> keys = new Dictionary<string, object>();
            keys.Add(Properties.ComponentCode, componentCode);

            return new PrimaryKey<T>(keys);
        }

        /// <summary>
        /// Crea una clave primaria para esta clase.
        /// </summary>
        /// <param name="componentCode">Propiedad clave ComponentCode.</param>
        public static PrimaryKey CreatePrimaryKey(int componentCode)
        {
            return InternalCreatePrimaryKey<HardComponent>(componentCode);
        }
        #endregion

        //*** Object Attributes ********************************

        //*** Object Constructors ********************************

        /// <summary>
        /// Constructor de instancia de la clase en base a las propiedades claves.
        /// </summary>
        /// <param name="componentCode">ComponentCode key property.</param>
        public HardComponent(int componentCode) :
            this(HardComponent.CreatePrimaryKey(componentCode), null)
        {
        }

        /// <summary>
        /// Constructor de instancia de la clase en base a una clave primaria y a valores iniciales.
        /// </summary>
        /// <param name="key">
        /// Identificador de la instancia de la entidad.
        /// </param>
        /// <param name="initialValues">
        /// Valores para establecer el estado de la instancia.
        /// </param>
        public HardComponent(PrimaryKey key, IDictionary initialValues) :
            base(key, initialValues)
        {
        }

        /*** Object Properties ********************************/
        /// <summary>
        /// Devuelve o setea el valor de la propiedad ComponentCode.
        /// </summary>
        /// <value>Propiedad ComponentCode.</value>
        [
        DescriptionKey("COMPONENT_CODE_PROPERTY"),
        PersistentProperty(IsKey = true),
        ColumnMap(ColumnName = "COMPONENT_CD", DbType = System.Data.DbType.String),
        ]
        public int ComponentCode
        {
            get
            {
                return (int)this._primaryKey[Properties.ComponentCode];
            }
            set
            {
                this._primaryKey[Properties.ComponentCode] = value;
            }
        }

    }
}