/******************************************
 * Code generated by GEB (Version: 2.2.0.0)
 * Template: Sistran.Core.Application.Parameters.PaymentMethod.dict v1.0
 * FileSize=7170 Header=254 CRC=3819155726
 ******************************************/
using System;
using System.Collections;
using System.Collections.Generic;
using Sistran.Core.Framework;
using Sistran.Core.Framework.DAF;

namespace Sistran.Core.Application.Parameters.Entities
{
    /// <summary>
    /// Definición de entidad PaymentMethod.
    /// </summary>
    [
    PersistentClass("Sistran.Core.Application.Parameters.PaymentMethod.dict"),
    Serializable(),
    DescriptionKey("PAYMENT_METHOD_ENTITY"),
    TableMap(TableName="PAYMENT_METHOD", Schema="COMM"),
    ]
    public partial class PaymentMethod :
        BusinessObject2
    {
#region static
		/// <summary>
		/// Propiedades públicas de la entidad.
		/// </summary>
		public static class Properties
		{
			public static readonly string PaymentMethodCode = "PaymentMethodCode";
			public static readonly string Description = "Description";
			public static readonly string SmallDescription = "SmallDescription";
			public static readonly string TinyDescription = "TinyDescription";
			public static readonly string IsIncome = "IsIncome";
			public static readonly string PaymentMethodTypeCode = "PaymentMethodTypeCode";
		}

		/// <summary>
		/// Crea una clave primaria para una clase concreta.
		/// </summary>
		/// <param name="concreteClass">Clase concreta.</param>
		/// <param name="paymentMethodCode">Propiedad clave PaymentMethodCode.</param>
		/// <returns>Clave primaria.</returns>
	    protected static PrimaryKey InternalCreatePrimaryKey<T>(int paymentMethodCode)
	    {
		    Dictionary<string, object> keys = new Dictionary<string, object>();
		    keys.Add(Properties.PaymentMethodCode, paymentMethodCode);

		    return new PrimaryKey<T>(keys);
	    }

        protected static PrimaryKey InternalCreatePrimaryKey<T>()
        {
            Dictionary<string, object> keys = new Dictionary<string, object>();
            keys.Add(Properties.PaymentMethodCode, null);

            return new PrimaryKey<T>(keys);
        }

        /// <summary>
        /// Crea una clave primaria para esta clase.
        /// </summary>
        /// <param name="paymentMethodCode">Propiedad clave PaymentMethodCode.</param>
        public static PrimaryKey CreatePrimaryKey(int paymentMethodCode)
	    {
			return InternalCreatePrimaryKey<PaymentMethod>(paymentMethodCode);
		}

        public static PrimaryKey CreatePrimaryKey()
        {
            return InternalCreatePrimaryKey<PaymentMethod>();
        }
        #endregion

        //*** Object Attributes ********************************

        /// <summary>
        /// Atributo para la propiedad Description.
        /// </summary>
        private string _description = null;
		/// <summary>
		/// Atributo para la propiedad SmallDescription.
		/// </summary>
        private string _smallDescription = null;
		/// <summary>
		/// Atributo para la propiedad TinyDescription.
		/// </summary>
        private string _tinyDescription = null;
		/// <summary>
		/// Atributo para la propiedad IsIncome.
		/// </summary>
        private bool _isIncome;
		/// <summary>
		/// Atributo para la propiedad PaymentMethodTypeCode.
		/// </summary>
        private int _paymentMethodTypeCode;
	    //*** Object Constructors ********************************

		/// <summary>
		/// Constructor de instancia de la clase en base a las propiedades claves.
		/// </summary>
		/// <param name="paymentMethodCode">PaymentMethodCode key property.</param>
	    public PaymentMethod(int paymentMethodCode):
			this(PaymentMethod.CreatePrimaryKey(paymentMethodCode), null)
	    {
	    }

        public PaymentMethod() :
            this(PaymentMethod.CreatePrimaryKey(), null)
        {
        }

        /// <summary>
        /// Constructor de instancia de la clase en base a una clave primaria y a valores iniciales.
        /// </summary>
        /// <param name="key">
        /// Identificador de la instancia de la entidad.
        /// </param>
        /// <param name="initialValues">
        /// Valores para establecer el estado de la instancia.
        /// </param>
        public PaymentMethod(PrimaryKey key, IDictionary initialValues):
			base(key, initialValues)
	    {
	    }

	    /*** Object Properties ********************************/
		/// <summary>
		/// Devuelve o setea el valor de la propiedad PaymentMethodCode.
		/// </summary>
		/// <value>Propiedad PaymentMethodCode.</value>
	    [
		DescriptionKey("PAYMENT_METHOD_CODE_PROPERTY"),
		PersistentProperty(IsKey = true, KeyType ="None"),
        ColumnMap(ColumnName="PAYMENT_METHOD_CD", DbType=System.Data.DbType.String),
	    ]
        public int PaymentMethodCode
	    {
		    get
		    {
				return (int)this._primaryKey[Properties.PaymentMethodCode];
		    }
		    set
		    {
				this._primaryKey[Properties.PaymentMethodCode] = value;
			}
	    }

		/// <summary>
		/// Devuelve o setea el valor de la propiedad Description.
		/// </summary>
		/// <value>Propiedad Description.</value>
	    [
		DescriptionKey("DESCRIPTION_PROPERTY"),
		PersistentProperty(),
        ColumnMap(ColumnName="DESCRIPTION", DbType=System.Data.DbType.String),
	    ]
        public string Description
	    {
		    get
		    {
			    return this._description;
		    }
		    set
		    {
				if(value == null)
				{
					throw new PropertyNotNullableException(this.GetType().FullName, Properties.Description);
				}
				this._description = value;
			}
	    }

		/// <summary>
		/// Devuelve o setea el valor de la propiedad SmallDescription.
		/// </summary>
		/// <value>Propiedad SmallDescription.</value>
	    [
		DescriptionKey("SMALL_DESCRIPTION_PROPERTY"),
		PersistentProperty(),
        ColumnMap(ColumnName="SMALL_DESCRIPTION", DbType=System.Data.DbType.String),
	    ]
        public string SmallDescription
	    {
		    get
		    {
			    return this._smallDescription;
		    }
		    set
		    {
				if(value == null)
				{
					throw new PropertyNotNullableException(this.GetType().FullName, Properties.SmallDescription);
				}
				this._smallDescription = value;
			}
	    }

		/// <summary>
		/// Devuelve o setea el valor de la propiedad TinyDescription.
		/// </summary>
		/// <value>Propiedad TinyDescription.</value>
	    [
		DescriptionKey("TINY_DESCRIPTION_PROPERTY"),
		PersistentProperty(),
        ColumnMap(ColumnName="TINY_DESCRIPTION", DbType=System.Data.DbType.String),
	    ]
        public string TinyDescription
	    {
		    get
		    {
			    return this._tinyDescription;
		    }
		    set
		    {
				if(value == null)
				{
					throw new PropertyNotNullableException(this.GetType().FullName, Properties.TinyDescription);
				}
				this._tinyDescription = value;
			}
	    }

		/// <summary>
		/// Devuelve o setea el valor de la propiedad IsIncome.
		/// </summary>
		/// <value>Propiedad IsIncome.</value>
	    [
		DescriptionKey("IS_INCOME_PROPERTY"),
		PersistentProperty(),
        ColumnMap(ColumnName="IS_INCOME", DbType=System.Data.DbType.String),
	    ]
        public bool IsIncome
	    {
		    get
		    {
			    return this._isIncome;
		    }
		    set
		    {
				this._isIncome = value;
			}
	    }

		/// <summary>
		/// Devuelve o setea el valor de la propiedad PaymentMethodTypeCode.
		/// </summary>
		/// <value>Propiedad PaymentMethodTypeCode.</value>
	    [
		DescriptionKey("PAYMENT_METHOD_TYPE_CODE_PROPERTY"),
		PersistentProperty(),
        ColumnMap(ColumnName="PAYMENT_METHOD_TYPE_CD", DbType=System.Data.DbType.String),
	    ]
        public int PaymentMethodTypeCode
	    {
		    get
		    {
			    return this._paymentMethodTypeCode;
		    }
		    set
		    {
				this._paymentMethodTypeCode = value;
			}
	    }

    }
}