/******************************************
 * Code generated by GEB (Version: 2.2.0.0)
 * Template: Sistran.Core.Application.Parameters.RequestStatus.dict v1.0
 * FileSize=3900 Header=254 CRC=3350589867
 ******************************************/
using Sistran.Core.Framework;
using Sistran.Core.Framework.DAF;
using System;
using System.Collections;
using System.Collections.Generic;

namespace Sistran.Core.Application.Parameters.Entities
{
    /// <summary>
    /// Definición de entidad RequestStatus.
    /// </summary>
    [
    PersistentClass("Sistran.Core.Application.Parameters.RequestStatus.dict"),
    Serializable(),
    DescriptionKey("REQUEST_STATUS_ENTITY"),
    TableMap(TableName = "REQUEST_STATUS", Schema = "PARAM"),
    ]
    public partial class RequestStatus :
        BusinessObject2
    {
        #region static
        /// <summary>
        /// Propiedades públicas de la entidad.
        /// </summary>
        public static class Properties
        {
            public static readonly string StatusCode = "StatusCode";
            public static readonly string Description = "Description";
        }

        /// <summary>
        /// Crea una clave primaria para una clase concreta.
        /// </summary>
        /// <param name="concreteClass">Clase concreta.</param>
        /// <param name="statusCode">Propiedad clave StatusCode.</param>
        /// <returns>Clave primaria.</returns>
        protected static PrimaryKey InternalCreatePrimaryKey<T>(int statusCode)
        {
            Dictionary<string, object> keys = new Dictionary<string, object>();
            keys.Add(Properties.StatusCode, statusCode);

            return new PrimaryKey<T>(keys);
        }

        /// <summary>
        /// Crea una clave primaria para esta clase.
        /// </summary>
        /// <param name="statusCode">Propiedad clave StatusCode.</param>
        public static PrimaryKey CreatePrimaryKey(int statusCode)
        {
            return InternalCreatePrimaryKey<RequestStatus>(statusCode);
        }
        #endregion

        //*** Object Attributes ********************************

        /// <summary>
        /// Atributo para la propiedad Description.
        /// </summary>
        private string _description = null;
        //*** Object Constructors ********************************

        /// <summary>
        /// Constructor de instancia de la clase en base a las propiedades claves.
        /// </summary>
        /// <param name="statusCode">StatusCode key property.</param>
        public RequestStatus(int statusCode) :
            this(RequestStatus.CreatePrimaryKey(statusCode), null)
        {
        }

        /// <summary>
        /// Constructor de instancia de la clase en base a una clave primaria y a valores iniciales.
        /// </summary>
        /// <param name="key">
        /// Identificador de la instancia de la entidad.
        /// </param>
        /// <param name="initialValues">
        /// Valores para establecer el estado de la instancia.
        /// </param>
        public RequestStatus(PrimaryKey key, IDictionary initialValues) :
            base(key, initialValues)
        {
        }

        /*** Object Properties ********************************/
        /// <summary>
        /// Devuelve o setea el valor de la propiedad StatusCode.
        /// </summary>
        /// <value>Propiedad StatusCode.</value>
        [
        DescriptionKey("STATUS_CODE_PROPERTY"),
        PersistentProperty(IsKey = true),
        ColumnMap(ColumnName = "STATUS_CD", DbType = System.Data.DbType.String),
        ]
        public int StatusCode
        {
            get
            {
                return (int)this._primaryKey[Properties.StatusCode];
            }
            set
            {
                this._primaryKey[Properties.StatusCode] = value;
            }
        }

        /// <summary>
        /// Devuelve o setea el valor de la propiedad Description.
        /// </summary>
        /// <value>Propiedad Description.</value>
        [
        DescriptionKey("DESCRIPTION_PROPERTY"),
        PersistentProperty(),
        ColumnMap(ColumnName = "DESCRIPTION", DbType = System.Data.DbType.String),
        ]
        public string Description
        {
            get
            {
                return this._description;
            }
            set
            {
                if (value == null)
                {
                    throw new PropertyNotNullableException(this.GetType().FullName, Properties.Description);
                }
                this._description = value;
            }
        }

    }
}