/******************************************
 * Code generated by GEB (Version: 2.2.0.0)
 * Template: Sistran.Core.Application.Common.MassiveLoadType.dict v1.0
 * FileSize=3998 Header=252 CRC=1099369024
 ******************************************/
using Sistran.Core.Framework;
using Sistran.Core.Framework.DAF;
using System;
using System.Collections;
using System.Collections.Generic;

namespace Sistran.Core.Application.Common.Entities
{
    /// <summary>
    /// Definición de entidad MassiveLoadType.
    /// </summary>
    [
    PersistentClass("Sistran.Core.Application.Common.MassiveLoadType.dict"),
    Serializable(),
    DescriptionKey("MASSIVE_LOAD_TYPE_ENTITY"),
    TableMap(TableName = "MASSIVE_LOAD_TYPE", Schema = "COMM"),
    ]
    public partial class MassiveLoadType :
        BusinessObject2
    {
        #region static
        /// <summary>
        /// Propiedades públicas de la entidad.
        /// </summary>
        public static class Properties
        {
            public static readonly string MassiveLoadTypeCode = "MassiveLoadTypeCode";
            public static readonly string Description = "Description";
        }

        /// <summary>
        /// Crea una clave primaria para una clase concreta.
        /// </summary>
        /// <param name="concreteClass">Clase concreta.</param>
        /// <param name="massiveLoadTypeCode">Propiedad clave MassiveLoadTypeCode.</param>
        /// <returns>Clave primaria.</returns>
        protected static PrimaryKey InternalCreatePrimaryKey<T>(int massiveLoadTypeCode)
        {
            Dictionary<string, object> keys = new Dictionary<string, object>();
            keys.Add(Properties.MassiveLoadTypeCode, massiveLoadTypeCode);

            return new PrimaryKey<T>(keys);
        }

        /// <summary>
        /// Crea una clave primaria para esta clase.
        /// </summary>
        /// <param name="massiveLoadTypeCode">Propiedad clave MassiveLoadTypeCode.</param>
        public static PrimaryKey CreatePrimaryKey(int massiveLoadTypeCode)
        {
            return InternalCreatePrimaryKey<MassiveLoadType>(massiveLoadTypeCode);
        }
        #endregion

        //*** Object Attributes ********************************

        /// <summary>
        /// Atributo para la propiedad Description.
        /// </summary>
        private string _description = null;
        //*** Object Constructors ********************************

        /// <summary>
        /// Constructor de instancia de la clase en base a las propiedades claves.
        /// </summary>
        /// <param name="massiveLoadTypeCode">MassiveLoadTypeCode key property.</param>
        public MassiveLoadType(int massiveLoadTypeCode) :
            this(MassiveLoadType.CreatePrimaryKey(massiveLoadTypeCode), null)
        {
        }

        /// <summary>
        /// Constructor de instancia de la clase en base a una clave primaria y a valores iniciales.
        /// </summary>
        /// <param name="key">
        /// Identificador de la instancia de la entidad.
        /// </param>
        /// <param name="initialValues">
        /// Valores para establecer el estado de la instancia.
        /// </param>
        public MassiveLoadType(PrimaryKey key, IDictionary initialValues) :
            base(key, initialValues)
        {
        }

        /*** Object Properties ********************************/
        /// <summary>
        /// Devuelve o setea el valor de la propiedad MassiveLoadTypeCode.
        /// </summary>
        /// <value>Propiedad MassiveLoadTypeCode.</value>
        [
        DescriptionKey("MASSIVE_LOAD_TYPE_CODE_PROPERTY"),
        PersistentProperty(IsKey = true),
        ColumnMap(ColumnName = "MASSIVE_LOAD_TYPE_CD", DbType = System.Data.DbType.String),
        ]
        public int MassiveLoadTypeCode
        {
            get
            {
                return (int)this._primaryKey[Properties.MassiveLoadTypeCode];
            }
            set
            {
                this._primaryKey[Properties.MassiveLoadTypeCode] = value;
            }
        }

        /// <summary>
        /// Devuelve o setea el valor de la propiedad Description.
        /// </summary>
        /// <value>Propiedad Description.</value>
        [
        DescriptionKey("DESCRIPTION_PROPERTY"),
        PersistentProperty(IsNullable = true),
        ColumnMap(ColumnName = "DESCRIPTION", DbType = System.Data.DbType.String),
        ]
        public string Description
        {
            get
            {
                return this._description;
            }
            set
            {
                this._description = value;
            }
        }

    }
}