/******************************************
 * Code generated by GEB (Version: 2.2.0.0)
 * Template: Sistran.Core.Application.Common.VehicleModel.dict v1.0
 * FileSize=7458 Header=249 CRC=2001284825
 ******************************************/
using Sistran.Core.Framework;
using Sistran.Core.Framework.DAF;
using System;
using System.Collections;
using System.Collections.Generic;

namespace Sistran.Core.Application.Common.Entities
{
    /// <summary>
    /// Definición de entidad VehicleModel.
    /// </summary>
    [
    PersistentClass("Sistran.Core.Application.Common.VehicleModel.dict"),
    Serializable(),
    DescriptionKey("VEHICLE_MODEL_ENTITY"),
    TableMap(TableName = "VEHICLE_MODEL", Schema = "COMM"),
    ]
    public partial class VehicleModel :
        BusinessObject2
    {
        #region static
        /// <summary>
        /// Propiedades públicas de la entidad.
        /// </summary>
        public static class Properties
        {
            public static readonly string VehicleModelCode = "VehicleModelCode";
            public static readonly string VehicleMakeCode = "VehicleMakeCode";
            public static readonly string Description = "Description";
            public static readonly string SmallDescription = "SmallDescription";
            public static readonly string AtVehicleVersionCode = "AtVehicleVersionCode";
            public static readonly string IaVehicleModelCode = "IaVehicleModelCode";
        }

        /// <summary>
        /// Crea una clave primaria para una clase concreta.
        /// </summary>
        /// <param name="concreteClass">Clase concreta.</param>
        /// <param name="vehicleModelCode">Propiedad clave VehicleModelCode.</param>
        /// <param name="vehicleMakeCode">Propiedad clave VehicleMakeCode.</param>
        /// <returns>Clave primaria.</returns>
        protected static PrimaryKey InternalCreatePrimaryKey<T>(int vehicleModelCode, int vehicleMakeCode)
        {
            Dictionary<string, object> keys = new Dictionary<string, object>();
            keys.Add(Properties.VehicleModelCode, vehicleModelCode);
            keys.Add(Properties.VehicleMakeCode, vehicleMakeCode);

            return new PrimaryKey<T>(keys);
        }

        /// <summary>
        /// Crea una clave primaria para esta clase.
        /// </summary>
        /// <param name="vehicleModelCode">Propiedad clave VehicleModelCode.</param>
        /// <param name="vehicleMakeCode">Propiedad clave VehicleMakeCode.</param>
        public static PrimaryKey CreatePrimaryKey(int vehicleModelCode, int vehicleMakeCode)
        {
            return InternalCreatePrimaryKey<VehicleModel>(vehicleModelCode, vehicleMakeCode);
        }
        #endregion

        //*** Object Attributes ********************************

        /// <summary>
        /// Atributo para la propiedad Description.
        /// </summary>
        private string _description = null;
        /// <summary>
        /// Atributo para la propiedad SmallDescription.
        /// </summary>
        private string _smallDescription = null;
        /// <summary>
        /// Atributo para la propiedad AtVehicleVersionCode.
        /// </summary>
        private int? _atVehicleVersionCode = null;
        /// <summary>
        /// Atributo para la propiedad IaVehicleModelCode.
        /// </summary>
        private int? _iaVehicleModelCode = null;
        //*** Object Constructors ********************************

        /// <summary>
        /// Constructor de instancia de la clase en base a las propiedades claves.
        /// </summary>
        /// <param name="vehicleModelCode">VehicleModelCode key property.</param>
        /// <param name="vehicleMakeCode">VehicleMakeCode key property.</param>
        public VehicleModel(int vehicleModelCode, int vehicleMakeCode) :
            this(VehicleModel.CreatePrimaryKey(vehicleModelCode, vehicleMakeCode), null)
        {
        }

        /// <summary>
        /// Constructor de instancia de la clase en base a una clave primaria y a valores iniciales.
        /// </summary>
        /// <param name="key">
        /// Identificador de la instancia de la entidad.
        /// </param>
        /// <param name="initialValues">
        /// Valores para establecer el estado de la instancia.
        /// </param>
        public VehicleModel(PrimaryKey key, IDictionary initialValues) :
            base(key, initialValues)
        {
        }

        /*** Object Properties ********************************/
        /// <summary>
        /// Devuelve o setea el valor de la propiedad VehicleModelCode.
        /// </summary>
        /// <value>Propiedad VehicleModelCode.</value>
        [
        DescriptionKey("VEHICLE_MODEL_CODE_PROPERTY"),
        PersistentProperty(IsKey = true),
        ColumnMap(ColumnName = "VEHICLE_MODEL_CD", DbType = System.Data.DbType.String),
        ]
        public int VehicleModelCode
        {
            get
            {
                return (int)this._primaryKey[Properties.VehicleModelCode];
            }
            set
            {
                this._primaryKey[Properties.VehicleModelCode] = value;
            }
        }

        /// <summary>
        /// Devuelve o setea el valor de la propiedad VehicleMakeCode.
        /// </summary>
        /// <value>Propiedad VehicleMakeCode.</value>
        [
        DescriptionKey("VEHICLE_MAKE_CODE_PROPERTY"),
        PersistentProperty(IsKey = true),
        ColumnMap(ColumnName = "VEHICLE_MAKE_CD", DbType = System.Data.DbType.String),
        ]
        public int VehicleMakeCode
        {
            get
            {
                return (int)this._primaryKey[Properties.VehicleMakeCode];
            }
            set
            {
                this._primaryKey[Properties.VehicleMakeCode] = value;
            }
        }

        /// <summary>
        /// Devuelve o setea el valor de la propiedad Description.
        /// </summary>
        /// <value>Propiedad Description.</value>
        [
        DescriptionKey("DESCRIPTION_PROPERTY"),
        PersistentProperty(),
        ColumnMap(ColumnName = "DESCRIPTION", DbType = System.Data.DbType.String),
        ]
        public string Description
        {
            get
            {
                return this._description;
            }
            set
            {
                if (value == null)
                {
                    throw new PropertyNotNullableException(this.GetType().FullName, Properties.Description);
                }
                this._description = value;
            }
        }

        /// <summary>
        /// Devuelve o setea el valor de la propiedad SmallDescription.
        /// </summary>
        /// <value>Propiedad SmallDescription.</value>
        [
        DescriptionKey("SMALL_DESCRIPTION_PROPERTY"),
        PersistentProperty(),
        ColumnMap(ColumnName = "SMALL_DESCRIPTION", DbType = System.Data.DbType.String),
        ]
        public string SmallDescription
        {
            get
            {
                return this._smallDescription;
            }
            set
            {
                if (value == null)
                {
                    throw new PropertyNotNullableException(this.GetType().FullName, Properties.SmallDescription);
                }
                this._smallDescription = value;
            }
        }

        /// <summary>
        /// Devuelve o setea el valor de la propiedad AtVehicleVersionCode.
        /// </summary>
        /// <value>Propiedad AtVehicleVersionCode.</value>
        [
        DescriptionKey("AT_VEHICLE_VERSION_CODE_PROPERTY"),
        PersistentProperty(IsNullable = true),
        ColumnMap(ColumnName = "AT_VEHICLE_VERSION_CD", DbType = System.Data.DbType.String),
        ]
        public int? AtVehicleVersionCode
        {
            get
            {
                return this._atVehicleVersionCode;
            }
            set
            {
                this._atVehicleVersionCode = value;
            }
        }

        /// <summary>
        /// Devuelve o setea el valor de la propiedad IaVehicleModelCode.
        /// </summary>
        /// <value>Propiedad IaVehicleModelCode.</value>
        [
        DescriptionKey("IA_VEHICLE_MODEL_CODE_PROPERTY"),
        PersistentProperty(IsNullable = true),
        ColumnMap(ColumnName = "IA_VEHICLE_MODEL_CD", DbType = System.Data.DbType.String),
        ]
        public int? IaVehicleModelCode
        {
            get
            {
                return this._iaVehicleModelCode;
            }
            set
            {
                this._iaVehicleModelCode = value;
            }
        }

    }
}