/******************************************
 * Code generated by GEB (Version: 2.2.0.0)
 * Template: Sistran.Core.Application.GeneralLedger.TempEntryGeneration.dict v1.0
 * FileSize=22200 Header=281 CRC=1547305973
 ******************************************/
using System;
using System.Collections;
using System.Collections.Generic;
using Sistran.Core.Framework;
using Sistran.Core.Framework.DAF;

namespace Sistran.Core.Application.GeneralLedger.Entities
{
    /// <summary>
    /// Definición de entidad TempEntryGeneration.
    /// </summary>
    [
    PersistentClass("Sistran.Core.Application.GeneralLedger.TempEntryGeneration.dict"),
    Serializable(),
    DescriptionKey("TEMP_ENTRY_GENERATION_ENTITY"),
    TableMap(TableName="TEMP_ENTRY_GENERATION", Schema="GL"),
    ]
    public partial class TempEntryGeneration :
        BusinessObject2
    {
#region static
		/// <summary>
		/// Propiedades públicas de la entidad.
		/// </summary>
		public static class Properties
		{
			public static readonly string TempEntryGenerationId = "TempEntryGenerationId";
			public static readonly string TransactionNumber = "TransactionNumber";
			public static readonly string BranchCode = "BranchCode";
			public static readonly string SalePointCode = "SalePointCode";
			public static readonly string AccountingCompanyCode = "AccountingCompanyCode";
			public static readonly string Amount = "Amount";
			public static readonly string CurrencyCode = "CurrencyCode";
			public static readonly string ExchangeRate = "ExchangeRate";
			public static readonly string LocalAmount = "LocalAmount";
			public static readonly string IndividualId = "IndividualId";
			public static readonly string AccountingAccountId = "AccountingAccountId";
			public static readonly string AccountingNature = "AccountingNature";
			public static readonly string Description = "Description";
			public static readonly string Date = "Date";
			public static readonly string AccountingMovementTypeId = "AccountingMovementTypeId";
			public static readonly string AccountingModuleId = "AccountingModuleId";
			public static readonly string BankReconciliationId = "BankReconciliationId";
			public static readonly string ReceiptNumber = "ReceiptNumber";
			public static readonly string ReceiptDate = "ReceiptDate";
			public static readonly string AccountingConceptCode = "AccountingConceptCode";
			public static readonly string EntryDestinationId = "EntryDestinationId";
			public static readonly string IsJournalEntry = "IsJournalEntry";
			public static readonly string EntryNumber = "EntryNumber";
			public static readonly string UserCode = "UserCode";
			public static readonly string ReconciliationCode = "ReconciliationCode";
			public static readonly string ReconciliationDate = "ReconciliationDate";
			public static readonly string DueDate = "DueDate";
		}

		/// <summary>
		/// Crea una clave primaria para una clase concreta.
		/// </summary>
		/// <param name="concreteClass">Clase concreta.</param>
		/// <param name="tempEntryGenerationId">Propiedad clave TempEntryGenerationId.</param>
		/// <returns>Clave primaria.</returns>
	    protected static PrimaryKey InternalCreatePrimaryKey<T>(int tempEntryGenerationId)
	    {
		    Dictionary<string, object> keys = new Dictionary<string, object>();
		    keys.Add(Properties.TempEntryGenerationId, tempEntryGenerationId);

		    return new PrimaryKey<T>(keys);
	    }

		/// <summary>
		/// Crea una clave primaria para esta clase.
		/// </summary>
		/// <param name="tempEntryGenerationId">Propiedad clave TempEntryGenerationId.</param>
		public static PrimaryKey CreatePrimaryKey(int tempEntryGenerationId)
	    {
			return InternalCreatePrimaryKey<TempEntryGeneration>(tempEntryGenerationId);
		}
#endregion

	    //*** Object Attributes ********************************

		/// <summary>
		/// Atributo para la propiedad TransactionNumber.
		/// </summary>
        private int? _transactionNumber = null;
		/// <summary>
		/// Atributo para la propiedad BranchCode.
		/// </summary>
        private int? _branchCode = null;
		/// <summary>
		/// Atributo para la propiedad SalePointCode.
		/// </summary>
        private decimal? _salePointCode = null;
		/// <summary>
		/// Atributo para la propiedad AccountingCompanyCode.
		/// </summary>
        private int? _accountingCompanyCode = null;
		/// <summary>
		/// Atributo para la propiedad Amount.
		/// </summary>
        private decimal? _amount = null;
		/// <summary>
		/// Atributo para la propiedad CurrencyCode.
		/// </summary>
        private int? _currencyCode = null;
		/// <summary>
		/// Atributo para la propiedad ExchangeRate.
		/// </summary>
        private decimal? _exchangeRate = null;
		/// <summary>
		/// Atributo para la propiedad LocalAmount.
		/// </summary>
        private decimal? _localAmount = null;
		/// <summary>
		/// Atributo para la propiedad IndividualId.
		/// </summary>
        private int? _individualId = null;
		/// <summary>
		/// Atributo para la propiedad AccountingAccountId.
		/// </summary>
        private int? _accountingAccountId = null;
		/// <summary>
		/// Atributo para la propiedad AccountingNature.
		/// </summary>
        private int? _accountingNature = null;
		/// <summary>
		/// Atributo para la propiedad Description.
		/// </summary>
        private string _description = null;
		/// <summary>
		/// Atributo para la propiedad Date.
		/// </summary>
        private DateTime? _date = null;
		/// <summary>
		/// Atributo para la propiedad AccountingMovementTypeId.
		/// </summary>
        private int? _accountingMovementTypeId = null;
		/// <summary>
		/// Atributo para la propiedad AccountingModuleId.
		/// </summary>
        private int? _accountingModuleId = null;
		/// <summary>
		/// Atributo para la propiedad BankReconciliationId.
		/// </summary>
        private int? _bankReconciliationId = null;
		/// <summary>
		/// Atributo para la propiedad ReceiptNumber.
		/// </summary>
        private int? _receiptNumber = null;
		/// <summary>
		/// Atributo para la propiedad ReceiptDate.
		/// </summary>
        private DateTime? _receiptDate = null;
		/// <summary>
		/// Atributo para la propiedad AccountingConceptCode.
		/// </summary>
        private int? _accountingConceptCode = null;
		/// <summary>
		/// Atributo para la propiedad EntryDestinationId.
		/// </summary>
        private int? _entryDestinationId = null;
		/// <summary>
		/// Atributo para la propiedad IsJournalEntry.
		/// </summary>
        private bool? _isJournalEntry = null;
		/// <summary>
		/// Atributo para la propiedad EntryNumber.
		/// </summary>
        private int? _entryNumber = null;
		/// <summary>
		/// Atributo para la propiedad UserCode.
		/// </summary>
        private int? _userCode = null;
		/// <summary>
		/// Atributo para la propiedad ReconciliationCode.
		/// </summary>
        private int? _reconciliationCode = null;
		/// <summary>
		/// Atributo para la propiedad ReconciliationDate.
		/// </summary>
        private DateTime? _reconciliationDate = null;
		/// <summary>
		/// Atributo para la propiedad DueDate.
		/// </summary>
        private DateTime? _dueDate = null;
	    //*** Object Constructors ********************************

		/// <summary>
		/// Constructor de instancia de la clase en base a las propiedades claves.
		/// </summary>
		/// <param name="tempEntryGenerationId">TempEntryGenerationId key property.</param>
	    public TempEntryGeneration(int tempEntryGenerationId):
			this(TempEntryGeneration.CreatePrimaryKey(tempEntryGenerationId), null)
	    {
	    }

		/// <summary>
		/// Constructor de instancia de la clase en base a una clave primaria y a valores iniciales.
		/// </summary>
		/// <param name="key">
		/// Identificador de la instancia de la entidad.
		/// </param>
		/// <param name="initialValues">
		/// Valores para establecer el estado de la instancia.
		/// </param>
	    public TempEntryGeneration(PrimaryKey key, IDictionary initialValues):
			base(key, initialValues)
	    {
	    }

	    /*** Object Properties ********************************/
		/// <summary>
		/// Devuelve o setea el valor de la propiedad TempEntryGenerationId.
		/// </summary>
		/// <value>Propiedad TempEntryGenerationId.</value>
	    [
		DescriptionKey("TEMP_ENTRY_GENERATION_ID_PROPERTY"),
		PersistentProperty(IsKey = true),
        ColumnMap(ColumnName="TEMP_ENTRY_GENERATION_ID", DbType=System.Data.DbType.String),
	    ]
        public int TempEntryGenerationId
	    {
		    get
		    {
				return (int)this._primaryKey[Properties.TempEntryGenerationId];
		    }
		    set
		    {
				this._primaryKey[Properties.TempEntryGenerationId] = value;
			}
	    }

		/// <summary>
		/// Devuelve o setea el valor de la propiedad TransactionNumber.
		/// </summary>
		/// <value>Propiedad TransactionNumber.</value>
	    [
		DescriptionKey("TRANSACTION_NUMBER_PROPERTY"),
		PersistentProperty(IsNullable = true),
        ColumnMap(ColumnName="TRANSACTION_NUMBER", DbType=System.Data.DbType.String),
	    ]
        public int? TransactionNumber
	    {
		    get
		    {
			    return this._transactionNumber;
		    }
		    set
		    {
				this._transactionNumber = value;
			}
	    }

		/// <summary>
		/// Devuelve o setea el valor de la propiedad BranchCode.
		/// </summary>
		/// <value>Propiedad BranchCode.</value>
	    [
		DescriptionKey("BRANCH_CODE_PROPERTY"),
		PersistentProperty(IsNullable = true),
        ColumnMap(ColumnName="BRANCH_CD", DbType=System.Data.DbType.String),
	    ]
        public int? BranchCode
	    {
		    get
		    {
			    return this._branchCode;
		    }
		    set
		    {
				this._branchCode = value;
			}
	    }

		/// <summary>
		/// Devuelve o setea el valor de la propiedad SalePointCode.
		/// </summary>
		/// <value>Propiedad SalePointCode.</value>
	    [
		DescriptionKey("SALE_POINT_CODE_PROPERTY"),
		PersistentProperty(IsNullable = true),
        ColumnMap(ColumnName="SALE_POINT_CD", DbType=System.Data.DbType.Decimal),
	    ]
        public decimal? SalePointCode
	    {
		    get
		    {
			    return this._salePointCode;
		    }
		    set
		    {
				this._salePointCode = value;
			}
	    }

		/// <summary>
		/// Devuelve o setea el valor de la propiedad AccountingCompanyCode.
		/// </summary>
		/// <value>Propiedad AccountingCompanyCode.</value>
	    [
		DescriptionKey("ACCOUNTING_COMPANY_CODE_PROPERTY"),
		PersistentProperty(IsNullable = true),
        ColumnMap(ColumnName="ACCOUNTING_COMPANY_CD", DbType=System.Data.DbType.String),
	    ]
        public int? AccountingCompanyCode
	    {
		    get
		    {
			    return this._accountingCompanyCode;
		    }
		    set
		    {
				this._accountingCompanyCode = value;
			}
	    }

		/// <summary>
		/// Devuelve o setea el valor de la propiedad Amount.
		/// </summary>
		/// <value>Propiedad Amount.</value>
	    [
		DescriptionKey("AMOUNT_PROPERTY"),
		PersistentProperty(IsNullable = true),
        ColumnMap(ColumnName="AMOUNT", DbType=System.Data.DbType.Decimal),
	    ]
        public decimal? Amount
	    {
		    get
		    {
			    return this._amount;
		    }
		    set
		    {
				this._amount = value;
			}
	    }

		/// <summary>
		/// Devuelve o setea el valor de la propiedad CurrencyCode.
		/// </summary>
		/// <value>Propiedad CurrencyCode.</value>
	    [
		DescriptionKey("CURRENCY_CODE_PROPERTY"),
		PersistentProperty(IsNullable = true),
        ColumnMap(ColumnName="CURRENCY_CD", DbType=System.Data.DbType.String),
	    ]
        public int? CurrencyCode
	    {
		    get
		    {
			    return this._currencyCode;
		    }
		    set
		    {
				this._currencyCode = value;
			}
	    }

		/// <summary>
		/// Devuelve o setea el valor de la propiedad ExchangeRate.
		/// </summary>
		/// <value>Propiedad ExchangeRate.</value>
	    [
		DescriptionKey("EXCHANGE_RATE_PROPERTY"),
		PersistentProperty(IsNullable = true),
        ColumnMap(ColumnName="EXCHANGE_RATE", DbType=System.Data.DbType.Decimal),
	    ]
        public decimal? ExchangeRate
	    {
		    get
		    {
			    return this._exchangeRate;
		    }
		    set
		    {
				this._exchangeRate = value;
			}
	    }

		/// <summary>
		/// Devuelve o setea el valor de la propiedad LocalAmount.
		/// </summary>
		/// <value>Propiedad LocalAmount.</value>
	    [
		DescriptionKey("LOCAL_AMOUNT_PROPERTY"),
		PersistentProperty(IsNullable = true),
        ColumnMap(ColumnName="LOCAL_AMOUNT", DbType=System.Data.DbType.Decimal),
	    ]
        public decimal? LocalAmount
	    {
		    get
		    {
			    return this._localAmount;
		    }
		    set
		    {
				this._localAmount = value;
			}
	    }

		/// <summary>
		/// Devuelve o setea el valor de la propiedad IndividualId.
		/// </summary>
		/// <value>Propiedad IndividualId.</value>
	    [
		DescriptionKey("INDIVIDUAL_ID_PROPERTY"),
		PersistentProperty(IsNullable = true),
        ColumnMap(ColumnName="INDIVIDUAL_ID", DbType=System.Data.DbType.String),
	    ]
        public int? IndividualId
	    {
		    get
		    {
			    return this._individualId;
		    }
		    set
		    {
				this._individualId = value;
			}
	    }

		/// <summary>
		/// Devuelve o setea el valor de la propiedad AccountingAccountId.
		/// </summary>
		/// <value>Propiedad AccountingAccountId.</value>
	    [
		DescriptionKey("ACCOUNTING_ACCOUNT_ID_PROPERTY"),
		PersistentProperty(IsNullable = true),
        ColumnMap(ColumnName="ACCOUNTING_ACCOUNT_ID", DbType=System.Data.DbType.String),
	    ]
        public int? AccountingAccountId
	    {
		    get
		    {
			    return this._accountingAccountId;
		    }
		    set
		    {
				this._accountingAccountId = value;
			}
	    }

		/// <summary>
		/// Devuelve o setea el valor de la propiedad AccountingNature.
		/// </summary>
		/// <value>Propiedad AccountingNature.</value>
	    [
		DescriptionKey("ACCOUNTING_NATURE_PROPERTY"),
		PersistentProperty(IsNullable = true),
        ColumnMap(ColumnName="ACCOUNTING_NATURE", DbType=System.Data.DbType.String),
	    ]
        public int? AccountingNature
	    {
		    get
		    {
			    return this._accountingNature;
		    }
		    set
		    {
				this._accountingNature = value;
			}
	    }

		/// <summary>
		/// Devuelve o setea el valor de la propiedad Description.
		/// </summary>
		/// <value>Propiedad Description.</value>
	    [
		DescriptionKey("DESCRIPTION_PROPERTY"),
		PersistentProperty(IsNullable = true),
        ColumnMap(ColumnName="DESCRIPTION", DbType=System.Data.DbType.String),
	    ]
        public string Description
	    {
		    get
		    {
			    return this._description;
		    }
		    set
		    {
				this._description = value;
			}
	    }

		/// <summary>
		/// Devuelve o setea el valor de la propiedad Date.
		/// </summary>
		/// <value>Propiedad Date.</value>
	    [
		DescriptionKey("DATE_PROPERTY"),
		PersistentProperty(IsNullable = true),
        ColumnMap(ColumnName="DATE", DbType=System.Data.DbType.String),
	    ]
        public DateTime? Date
	    {
		    get
		    {
			    return this._date;
		    }
		    set
		    {
				this._date = value;
			}
	    }

		/// <summary>
		/// Devuelve o setea el valor de la propiedad AccountingMovementTypeId.
		/// </summary>
		/// <value>Propiedad AccountingMovementTypeId.</value>
	    [
		DescriptionKey("ACCOUNTING_MOVEMENT_TYPE_ID_PROPERTY"),
		PersistentProperty(IsNullable = true),
        ColumnMap(ColumnName="ACCOUNTING_MOVEMENT_TYPE_ID", DbType=System.Data.DbType.String),
	    ]
        public int? AccountingMovementTypeId
	    {
		    get
		    {
			    return this._accountingMovementTypeId;
		    }
		    set
		    {
				this._accountingMovementTypeId = value;
			}
	    }

		/// <summary>
		/// Devuelve o setea el valor de la propiedad AccountingModuleId.
		/// </summary>
		/// <value>Propiedad AccountingModuleId.</value>
	    [
		DescriptionKey("ACCOUNTING_MODULE_ID_PROPERTY"),
		PersistentProperty(IsNullable = true),
        ColumnMap(ColumnName="ACCOUNTING_MODULE_ID", DbType=System.Data.DbType.String),
	    ]
        public int? AccountingModuleId
	    {
		    get
		    {
			    return this._accountingModuleId;
		    }
		    set
		    {
				this._accountingModuleId = value;
			}
	    }

		/// <summary>
		/// Devuelve o setea el valor de la propiedad BankReconciliationId.
		/// </summary>
		/// <value>Propiedad BankReconciliationId.</value>
	    [
		DescriptionKey("BANK_RECONCILIATION_ID_PROPERTY"),
		PersistentProperty(IsNullable = true),
        ColumnMap(ColumnName="BANK_RECONCILIATION_ID", DbType=System.Data.DbType.String),
	    ]
        public int? BankReconciliationId
	    {
		    get
		    {
			    return this._bankReconciliationId;
		    }
		    set
		    {
				this._bankReconciliationId = value;
			}
	    }

		/// <summary>
		/// Devuelve o setea el valor de la propiedad ReceiptNumber.
		/// </summary>
		/// <value>Propiedad ReceiptNumber.</value>
	    [
		DescriptionKey("RECEIPT_NUMBER_PROPERTY"),
		PersistentProperty(IsNullable = true),
        ColumnMap(ColumnName="RECEIPT_NUMBER", DbType=System.Data.DbType.String),
	    ]
        public int? ReceiptNumber
	    {
		    get
		    {
			    return this._receiptNumber;
		    }
		    set
		    {
				this._receiptNumber = value;
			}
	    }

		/// <summary>
		/// Devuelve o setea el valor de la propiedad ReceiptDate.
		/// </summary>
		/// <value>Propiedad ReceiptDate.</value>
	    [
		DescriptionKey("RECEIPT_DATE_PROPERTY"),
		PersistentProperty(IsNullable = true),
        ColumnMap(ColumnName="RECEIPT_DATE", DbType=System.Data.DbType.String),
	    ]
        public DateTime? ReceiptDate
	    {
		    get
		    {
			    return this._receiptDate;
		    }
		    set
		    {
				this._receiptDate = value;
			}
	    }

		/// <summary>
		/// Devuelve o setea el valor de la propiedad AccountingConceptCode.
		/// </summary>
		/// <value>Propiedad AccountingConceptCode.</value>
	    [
		DescriptionKey("ACCOUNTING_CONCEPT_CODE_PROPERTY"),
		PersistentProperty(IsNullable = true),
        ColumnMap(ColumnName="ACCOUNTING_CONCEPT_CD", DbType=System.Data.DbType.String),
	    ]
        public int? AccountingConceptCode
	    {
		    get
		    {
			    return this._accountingConceptCode;
		    }
		    set
		    {
				this._accountingConceptCode = value;
			}
	    }

		/// <summary>
		/// Devuelve o setea el valor de la propiedad EntryDestinationId.
		/// </summary>
		/// <value>Propiedad EntryDestinationId.</value>
	    [
		DescriptionKey("ENTRY_DESTINATION_ID_PROPERTY"),
		PersistentProperty(IsNullable = true),
        ColumnMap(ColumnName="ENTRY_DESTINATION_ID", DbType=System.Data.DbType.String),
	    ]
        public int? EntryDestinationId
	    {
		    get
		    {
			    return this._entryDestinationId;
		    }
		    set
		    {
				this._entryDestinationId = value;
			}
	    }

		/// <summary>
		/// Devuelve o setea el valor de la propiedad IsJournalEntry.
		/// </summary>
		/// <value>Propiedad IsJournalEntry.</value>
	    [
		DescriptionKey("IS_JOURNAL_ENTRY_PROPERTY"),
		PersistentProperty(IsNullable = true),
        ColumnMap(ColumnName="IS_JOURNAL_ENTRY", DbType=System.Data.DbType.String),
	    ]
        public bool? IsJournalEntry
	    {
		    get
		    {
			    return this._isJournalEntry;
		    }
		    set
		    {
				this._isJournalEntry = value;
			}
	    }

		/// <summary>
		/// Devuelve o setea el valor de la propiedad EntryNumber.
		/// </summary>
		/// <value>Propiedad EntryNumber.</value>
	    [
		DescriptionKey("ENTRY_NUMBER_PROPERTY"),
		PersistentProperty(IsNullable = true),
        ColumnMap(ColumnName="ENTRY_NUMBER", DbType=System.Data.DbType.String),
	    ]
        public int? EntryNumber
	    {
		    get
		    {
			    return this._entryNumber;
		    }
		    set
		    {
				this._entryNumber = value;
			}
	    }

		/// <summary>
		/// Devuelve o setea el valor de la propiedad UserCode.
		/// </summary>
		/// <value>Propiedad UserCode.</value>
	    [
		DescriptionKey("USER_CODE_PROPERTY"),
		PersistentProperty(IsNullable = true),
        ColumnMap(ColumnName="USER_CD", DbType=System.Data.DbType.String),
	    ]
        public int? UserCode
	    {
		    get
		    {
			    return this._userCode;
		    }
		    set
		    {
				this._userCode = value;
			}
	    }

		/// <summary>
		/// Devuelve o setea el valor de la propiedad ReconciliationCode.
		/// </summary>
		/// <value>Propiedad ReconciliationCode.</value>
	    [
		DescriptionKey("RECONCILIATION_CODE_PROPERTY"),
		PersistentProperty(IsNullable = true),
        ColumnMap(ColumnName="RECONCILIATION_CD", DbType=System.Data.DbType.String),
	    ]
        public int? ReconciliationCode
	    {
		    get
		    {
			    return this._reconciliationCode;
		    }
		    set
		    {
				this._reconciliationCode = value;
			}
	    }

		/// <summary>
		/// Devuelve o setea el valor de la propiedad ReconciliationDate.
		/// </summary>
		/// <value>Propiedad ReconciliationDate.</value>
	    [
		DescriptionKey("RECONCILIATION_DATE_PROPERTY"),
		PersistentProperty(IsNullable = true),
        ColumnMap(ColumnName="RECONCILIATION_DATE", DbType=System.Data.DbType.String),
	    ]
        public DateTime? ReconciliationDate
	    {
		    get
		    {
			    return this._reconciliationDate;
		    }
		    set
		    {
				this._reconciliationDate = value;
			}
	    }

		/// <summary>
		/// Devuelve o setea el valor de la propiedad DueDate.
		/// </summary>
		/// <value>Propiedad DueDate.</value>
	    [
		DescriptionKey("DUE_DATE_PROPERTY"),
		PersistentProperty(IsNullable = true),
        ColumnMap(ColumnName="DUE_DATE", DbType=System.Data.DbType.String),
	    ]
        public DateTime? DueDate
	    {
		    get
		    {
			    return this._dueDate;
		    }
		    set
		    {
				this._dueDate = value;
			}
	    }

    }
}