//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsumerQueueRuleSetCache.WrapperServiceWCF {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WrapperServiceWCF.IWrapperService")]
    public interface IWrapperService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWrapperService/Quote", ReplyAction="http://tempuri.org/IWrapperService/QuoteResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ConsumerQueueRuleSetCache.WrapperServiceWCF.QuoteResponse Quote(ConsumerQueueRuleSetCache.WrapperServiceWCF.QuoteRequest quoteRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWrapperService/Quote", ReplyAction="http://tempuri.org/IWrapperService/QuoteResponse")]
        System.Threading.Tasks.Task<ConsumerQueueRuleSetCache.WrapperServiceWCF.QuoteResponse> QuoteAsync(ConsumerQueueRuleSetCache.WrapperServiceWCF.QuoteRequest quoteRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWrapperService/CreateQuotationListFromJson", ReplyAction="http://tempuri.org/IWrapperService/CreateQuotationListFromJsonResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void CreateQuotationListFromJson(string listCompanyVehicleLikeJson);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWrapperService/CreateQuotationListFromJson", ReplyAction="http://tempuri.org/IWrapperService/CreateQuotationListFromJsonResponse")]
        System.Threading.Tasks.Task CreateQuotationListFromJsonAsync(string listCompanyVehicleLikeJson);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWrapperService/RegisterExternalInformationLog", ReplyAction="http://tempuri.org/IWrapperService/RegisterExternalInformationLogResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void RegisterExternalInformationLog(string externalInfromationLog);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWrapperService/RegisterExternalInformationLog", ReplyAction="http://tempuri.org/IWrapperService/RegisterExternalInformationLogResponse")]
        System.Threading.Tasks.Task RegisterExternalInformationLogAsync(string externalInfromationLog);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWrapperService/loadCacheByJson", ReplyAction="http://tempuri.org/IWrapperService/loadCacheByJsonResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void loadCacheByJson(string HistoryVersionJson);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWrapperService/loadCacheByJson", ReplyAction="http://tempuri.org/IWrapperService/loadCacheByJsonResponse")]
        System.Threading.Tasks.Task loadCacheByJsonAsync(string HistoryVersionJson);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWrapperService/UpdateCacheByJson", ReplyAction="http://tempuri.org/IWrapperService/UpdateCacheByJsonResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void UpdateCacheByJson(string HistoryVersionJson);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWrapperService/UpdateCacheByJson", ReplyAction="http://tempuri.org/IWrapperService/UpdateCacheByJsonResponse")]
        System.Threading.Tasks.Task UpdateCacheByJsonAsync(string HistoryVersionJson);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class QuoteRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private InsuredQuotation insuredQuotationField;
        
        private PolicyQuotation policyQuotationField;
        
        private RiskQuotation riskQuotationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public InsuredQuotation insuredQuotation {
            get {
                return this.insuredQuotationField;
            }
            set {
                this.insuredQuotationField = value;
                this.RaisePropertyChanged("insuredQuotation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public PolicyQuotation policyQuotation {
            get {
                return this.policyQuotationField;
            }
            set {
                this.policyQuotationField = value;
                this.RaisePropertyChanged("policyQuotation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public RiskQuotation riskQuotation {
            get {
                return this.riskQuotationField;
            }
            set {
                this.riskQuotationField = value;
                this.RaisePropertyChanged("riskQuotation");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class InsuredQuotation : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int typeCardCodeField;
        
        private string idCardNroField;
        
        private string genderField;
        
        private string nameField;
        
        private string surnameField;
        
        private System.DateTime birthDateField;
        
        private int maritalStatusField;
        
        private int stateCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int typeCardCode {
            get {
                return this.typeCardCodeField;
            }
            set {
                this.typeCardCodeField = value;
                this.RaisePropertyChanged("typeCardCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string idCardNro {
            get {
                return this.idCardNroField;
            }
            set {
                this.idCardNroField = value;
                this.RaisePropertyChanged("idCardNro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string gender {
            get {
                return this.genderField;
            }
            set {
                this.genderField = value;
                this.RaisePropertyChanged("gender");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string surname {
            get {
                return this.surnameField;
            }
            set {
                this.surnameField = value;
                this.RaisePropertyChanged("surname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public System.DateTime birthDate {
            get {
                return this.birthDateField;
            }
            set {
                this.birthDateField = value;
                this.RaisePropertyChanged("birthDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int maritalStatus {
            get {
                return this.maritalStatusField;
            }
            set {
                this.maritalStatusField = value;
                this.RaisePropertyChanged("maritalStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int stateCode {
            get {
                return this.stateCodeField;
            }
            set {
                this.stateCodeField = value;
                this.RaisePropertyChanged("stateCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class QuoteResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int tempIdField;
        
        private int branchCodeField;
        
        private int sourceCodeField;
        
        private int businessIdField;
        
        private int requestIdField;
        
        private int productIdField;
        
        private string productIdResponseField;
        
        private System.DateTime currentFromField;
        
        private System.DateTime currentToField;
        
        private int userIdField;
        
        private string licensePlateField;
        
        private int coverGroupIdField;
        
        private int assistanceCodeField;
        
        private int limitRcCodeField;
        
        private decimal limitRcSumField;
        
        private int goodExperienceNumField;
        
        private System.Nullable<System.DateTime> maximumVigencyField;
        
        private string isEffectiveDateField;
        
        private int ratingZoneCodeField;
        
        private decimal vehiclePriceField;
        
        private decimal vehiclePriceDetailField;
        
        private decimal premiumAmountField;
        
        private decimal assistanceAmountField;
        
        private decimal expensesAmountField;
        
        private decimal taxAmountField;
        
        private decimal totalPremiumAmountField;
        
        private string processMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int TempId {
            get {
                return this.tempIdField;
            }
            set {
                this.tempIdField = value;
                this.RaisePropertyChanged("TempId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int BranchCode {
            get {
                return this.branchCodeField;
            }
            set {
                this.branchCodeField = value;
                this.RaisePropertyChanged("BranchCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int SourceCode {
            get {
                return this.sourceCodeField;
            }
            set {
                this.sourceCodeField = value;
                this.RaisePropertyChanged("SourceCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int BusinessId {
            get {
                return this.businessIdField;
            }
            set {
                this.businessIdField = value;
                this.RaisePropertyChanged("BusinessId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int RequestId {
            get {
                return this.requestIdField;
            }
            set {
                this.requestIdField = value;
                this.RaisePropertyChanged("RequestId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int ProductId {
            get {
                return this.productIdField;
            }
            set {
                this.productIdField = value;
                this.RaisePropertyChanged("ProductId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string ProductIdResponse {
            get {
                return this.productIdResponseField;
            }
            set {
                this.productIdResponseField = value;
                this.RaisePropertyChanged("ProductIdResponse");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public System.DateTime CurrentFrom {
            get {
                return this.currentFromField;
            }
            set {
                this.currentFromField = value;
                this.RaisePropertyChanged("CurrentFrom");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public System.DateTime CurrentTo {
            get {
                return this.currentToField;
            }
            set {
                this.currentToField = value;
                this.RaisePropertyChanged("CurrentTo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int UserId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
                this.RaisePropertyChanged("UserId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string LicensePlate {
            get {
                return this.licensePlateField;
            }
            set {
                this.licensePlateField = value;
                this.RaisePropertyChanged("LicensePlate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public int CoverGroupId {
            get {
                return this.coverGroupIdField;
            }
            set {
                this.coverGroupIdField = value;
                this.RaisePropertyChanged("CoverGroupId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public int AssistanceCode {
            get {
                return this.assistanceCodeField;
            }
            set {
                this.assistanceCodeField = value;
                this.RaisePropertyChanged("AssistanceCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public int LimitRcCode {
            get {
                return this.limitRcCodeField;
            }
            set {
                this.limitRcCodeField = value;
                this.RaisePropertyChanged("LimitRcCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public decimal LimitRcSum {
            get {
                return this.limitRcSumField;
            }
            set {
                this.limitRcSumField = value;
                this.RaisePropertyChanged("LimitRcSum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public int GoodExperienceNum {
            get {
                return this.goodExperienceNumField;
            }
            set {
                this.goodExperienceNumField = value;
                this.RaisePropertyChanged("GoodExperienceNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=16)]
        public System.Nullable<System.DateTime> MaximumVigency {
            get {
                return this.maximumVigencyField;
            }
            set {
                this.maximumVigencyField = value;
                this.RaisePropertyChanged("MaximumVigency");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string IsEffectiveDate {
            get {
                return this.isEffectiveDateField;
            }
            set {
                this.isEffectiveDateField = value;
                this.RaisePropertyChanged("IsEffectiveDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public int RatingZoneCode {
            get {
                return this.ratingZoneCodeField;
            }
            set {
                this.ratingZoneCodeField = value;
                this.RaisePropertyChanged("RatingZoneCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public decimal VehiclePrice {
            get {
                return this.vehiclePriceField;
            }
            set {
                this.vehiclePriceField = value;
                this.RaisePropertyChanged("VehiclePrice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public decimal VehiclePriceDetail {
            get {
                return this.vehiclePriceDetailField;
            }
            set {
                this.vehiclePriceDetailField = value;
                this.RaisePropertyChanged("VehiclePriceDetail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public decimal PremiumAmount {
            get {
                return this.premiumAmountField;
            }
            set {
                this.premiumAmountField = value;
                this.RaisePropertyChanged("PremiumAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public decimal AssistanceAmount {
            get {
                return this.assistanceAmountField;
            }
            set {
                this.assistanceAmountField = value;
                this.RaisePropertyChanged("AssistanceAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public decimal ExpensesAmount {
            get {
                return this.expensesAmountField;
            }
            set {
                this.expensesAmountField = value;
                this.RaisePropertyChanged("ExpensesAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public decimal TaxAmount {
            get {
                return this.taxAmountField;
            }
            set {
                this.taxAmountField = value;
                this.RaisePropertyChanged("TaxAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public decimal TotalPremiumAmount {
            get {
                return this.totalPremiumAmountField;
            }
            set {
                this.totalPremiumAmountField = value;
                this.RaisePropertyChanged("TotalPremiumAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string ProcessMessage {
            get {
                return this.processMessageField;
            }
            set {
                this.processMessageField = value;
                this.RaisePropertyChanged("ProcessMessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class QuoteResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private QuoteResult[] listQuoteResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public QuoteResult[] listQuoteResult {
            get {
                return this.listQuoteResultField;
            }
            set {
                this.listQuoteResultField = value;
                this.RaisePropertyChanged("listQuoteResult");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class RiskQuotation : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string licensePlateField;
        
        private string engineSerialNumberField;
        
        private string chassisSerialNumberField;
        
        private string fasecoldaMakeIdField;
        
        private string fasecoldaModelIdField;
        
        private int vehicleUseCodeField;
        
        private int vehicleColorCodeField;
        
        private int vehicleYearField;
        
        private bool isNewField;
        
        private decimal vehiclePriceField;
        
        private decimal vehicleAmountDetailField;
        
        private System.Nullable<int> coverGroupIdField;
        
        private System.Nullable<int> assistanceCodeField;
        
        private int limitRcCodeField;
        
        private int ratingZoneCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string licensePlate {
            get {
                return this.licensePlateField;
            }
            set {
                this.licensePlateField = value;
                this.RaisePropertyChanged("licensePlate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string engineSerialNumber {
            get {
                return this.engineSerialNumberField;
            }
            set {
                this.engineSerialNumberField = value;
                this.RaisePropertyChanged("engineSerialNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string chassisSerialNumber {
            get {
                return this.chassisSerialNumberField;
            }
            set {
                this.chassisSerialNumberField = value;
                this.RaisePropertyChanged("chassisSerialNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string fasecoldaMakeId {
            get {
                return this.fasecoldaMakeIdField;
            }
            set {
                this.fasecoldaMakeIdField = value;
                this.RaisePropertyChanged("fasecoldaMakeId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string fasecoldaModelId {
            get {
                return this.fasecoldaModelIdField;
            }
            set {
                this.fasecoldaModelIdField = value;
                this.RaisePropertyChanged("fasecoldaModelId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int vehicleUseCode {
            get {
                return this.vehicleUseCodeField;
            }
            set {
                this.vehicleUseCodeField = value;
                this.RaisePropertyChanged("vehicleUseCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int vehicleColorCode {
            get {
                return this.vehicleColorCodeField;
            }
            set {
                this.vehicleColorCodeField = value;
                this.RaisePropertyChanged("vehicleColorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int vehicleYear {
            get {
                return this.vehicleYearField;
            }
            set {
                this.vehicleYearField = value;
                this.RaisePropertyChanged("vehicleYear");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public bool isNew {
            get {
                return this.isNewField;
            }
            set {
                this.isNewField = value;
                this.RaisePropertyChanged("isNew");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public decimal vehiclePrice {
            get {
                return this.vehiclePriceField;
            }
            set {
                this.vehiclePriceField = value;
                this.RaisePropertyChanged("vehiclePrice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public decimal vehicleAmountDetail {
            get {
                return this.vehicleAmountDetailField;
            }
            set {
                this.vehicleAmountDetailField = value;
                this.RaisePropertyChanged("vehicleAmountDetail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public System.Nullable<int> coverGroupId {
            get {
                return this.coverGroupIdField;
            }
            set {
                this.coverGroupIdField = value;
                this.RaisePropertyChanged("coverGroupId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public System.Nullable<int> assistanceCode {
            get {
                return this.assistanceCodeField;
            }
            set {
                this.assistanceCodeField = value;
                this.RaisePropertyChanged("assistanceCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public int limitRcCode {
            get {
                return this.limitRcCodeField;
            }
            set {
                this.limitRcCodeField = value;
                this.RaisePropertyChanged("limitRcCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public int ratingZoneCode {
            get {
                return this.ratingZoneCodeField;
            }
            set {
                this.ratingZoneCodeField = value;
                this.RaisePropertyChanged("ratingZoneCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PolicyQuotation : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int sourceCodeField;
        
        private int businessIdField;
        
        private System.Nullable<int> productIdField;
        
        private System.Nullable<int> requestIdField;
        
        private int branchCodeField;
        
        private int policyTypeCodeField;
        
        private int agentCodeField;
        
        private int agentAgencyTypeCodeField;
        
        private System.Nullable<int> allianceIdField;
        
        private System.Nullable<int> allianceBranchIdField;
        
        private System.Nullable<int> allianceSalePointIdField;
        
        private System.Nullable<int> allianceProposalNumberField;
        
        private string accountNameField;
        
        private int currencyCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int sourceCode {
            get {
                return this.sourceCodeField;
            }
            set {
                this.sourceCodeField = value;
                this.RaisePropertyChanged("sourceCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int businessId {
            get {
                return this.businessIdField;
            }
            set {
                this.businessIdField = value;
                this.RaisePropertyChanged("businessId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<int> productId {
            get {
                return this.productIdField;
            }
            set {
                this.productIdField = value;
                this.RaisePropertyChanged("productId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<int> requestId {
            get {
                return this.requestIdField;
            }
            set {
                this.requestIdField = value;
                this.RaisePropertyChanged("requestId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int branchCode {
            get {
                return this.branchCodeField;
            }
            set {
                this.branchCodeField = value;
                this.RaisePropertyChanged("branchCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int policyTypeCode {
            get {
                return this.policyTypeCodeField;
            }
            set {
                this.policyTypeCodeField = value;
                this.RaisePropertyChanged("policyTypeCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int agentCode {
            get {
                return this.agentCodeField;
            }
            set {
                this.agentCodeField = value;
                this.RaisePropertyChanged("agentCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int agentAgencyTypeCode {
            get {
                return this.agentAgencyTypeCodeField;
            }
            set {
                this.agentAgencyTypeCodeField = value;
                this.RaisePropertyChanged("agentAgencyTypeCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public System.Nullable<int> allianceId {
            get {
                return this.allianceIdField;
            }
            set {
                this.allianceIdField = value;
                this.RaisePropertyChanged("allianceId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public System.Nullable<int> allianceBranchId {
            get {
                return this.allianceBranchIdField;
            }
            set {
                this.allianceBranchIdField = value;
                this.RaisePropertyChanged("allianceBranchId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public System.Nullable<int> allianceSalePointId {
            get {
                return this.allianceSalePointIdField;
            }
            set {
                this.allianceSalePointIdField = value;
                this.RaisePropertyChanged("allianceSalePointId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public System.Nullable<int> allianceProposalNumber {
            get {
                return this.allianceProposalNumberField;
            }
            set {
                this.allianceProposalNumberField = value;
                this.RaisePropertyChanged("allianceProposalNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string accountName {
            get {
                return this.accountNameField;
            }
            set {
                this.accountNameField = value;
                this.RaisePropertyChanged("accountName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public int currencyCode {
            get {
                return this.currencyCodeField;
            }
            set {
                this.currencyCodeField = value;
                this.RaisePropertyChanged("currencyCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWrapperServiceChannel : ConsumerQueueRuleSetCache.WrapperServiceWCF.IWrapperService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WrapperServiceClient : System.ServiceModel.ClientBase<ConsumerQueueRuleSetCache.WrapperServiceWCF.IWrapperService>, ConsumerQueueRuleSetCache.WrapperServiceWCF.IWrapperService {
        
        public WrapperServiceClient() {
        }
        
        public WrapperServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WrapperServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WrapperServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WrapperServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ConsumerQueueRuleSetCache.WrapperServiceWCF.QuoteResponse Quote(ConsumerQueueRuleSetCache.WrapperServiceWCF.QuoteRequest quoteRequest) {
            return base.Channel.Quote(quoteRequest);
        }
        
        public System.Threading.Tasks.Task<ConsumerQueueRuleSetCache.WrapperServiceWCF.QuoteResponse> QuoteAsync(ConsumerQueueRuleSetCache.WrapperServiceWCF.QuoteRequest quoteRequest) {
            return base.Channel.QuoteAsync(quoteRequest);
        }
        
        public void CreateQuotationListFromJson(string listCompanyVehicleLikeJson) {
            base.Channel.CreateQuotationListFromJson(listCompanyVehicleLikeJson);
        }
        
        public System.Threading.Tasks.Task CreateQuotationListFromJsonAsync(string listCompanyVehicleLikeJson) {
            return base.Channel.CreateQuotationListFromJsonAsync(listCompanyVehicleLikeJson);
        }
        
        public void RegisterExternalInformationLog(string externalInfromationLog) {
            base.Channel.RegisterExternalInformationLog(externalInfromationLog);
        }
        
        public System.Threading.Tasks.Task RegisterExternalInformationLogAsync(string externalInfromationLog) {
            return base.Channel.RegisterExternalInformationLogAsync(externalInfromationLog);
        }
        
        public void loadCacheByJson(string HistoryVersionJson) {
            base.Channel.loadCacheByJson(HistoryVersionJson);
        }
        
        public System.Threading.Tasks.Task loadCacheByJsonAsync(string HistoryVersionJson) {
            return base.Channel.loadCacheByJsonAsync(HistoryVersionJson);
        }
        
        public void UpdateCacheByJson(string HistoryVersionJson) {
            base.Channel.UpdateCacheByJson(HistoryVersionJson);
        }
        
        public System.Threading.Tasks.Task UpdateCacheByJsonAsync(string HistoryVersionJson) {
            return base.Channel.UpdateCacheByJsonAsync(HistoryVersionJson);
        }
    }
}
