/******************************************
 * Code generated by GEB (Version: 2.2.0.0)
 * Template: Sistran.Core.Application.Issuance.CommissAgent.dict v1.0
 * FileSize=15110 Header=251 CRC=601321519
 ******************************************/
using Sistran.Core.Framework;
using Sistran.Core.Framework.DAF;
using System;
using System.Collections;
using System.Collections.Generic;

namespace Sistran.Core.Application.Issuance.Entities
{
    /// <summary>
    /// Definición de entidad CommissAgent.
    /// </summary>
    [
    PersistentClass("Sistran.Core.Application.Issuance.CommissAgent.dict"),
    Serializable(),
    DescriptionKey("COMMISS_AGENT_ENTITY"),
    TableMap(TableName = "COMMISS_AGENT", Schema = "ISS"),
    ]
    public partial class CommissAgent :
        BusinessObject2
    {
        #region static
        /// <summary>
        /// Propiedades públicas de la entidad.
        /// </summary>
        public static class Properties
        {
            public static readonly string CommissAgentId = "CommissAgentId";
            public static readonly string IndividualId = "IndividualId";
            public static readonly string AgentAgencyId = "AgentAgencyId";
            public static readonly string PolicyId = "PolicyId";
            public static readonly string EndorsementId = "EndorsementId";
            public static readonly string CommissNum = "CommissNum";
            public static readonly string AgentPartPercentage = "AgentPartPercentage";
            public static readonly string StComissionPercentage = "StComissionPercentage";
            public static readonly string AdditCommissPercentage = "AdditCommissPercentage";
            public static readonly string StDiscCommissPercentage = "StDiscCommissPercentage";
            public static readonly string AdditDiscCommissPercentage = "AdditDiscCommissPercentage";
            public static readonly string LineBusinessCode = "LineBusinessCode";
            public static readonly string SubLineBusinessCode = "SubLineBusinessCode";
            public static readonly string InUnits = "InUnits";
            public static readonly string IncCommissAdFacPercentage = "IncCommissAdFacPercentage";
            public static readonly string DimCommissAdFacPercentage = "DimCommissAdFacPercentage";
            public static readonly string SchCommissPercentage = "SchCommissPercentage";
            public static readonly string StAgentComissionPercentage = "StAgentComissionPercentage";
        }

        /// <summary>
        /// Crea una clave primaria para una clase concreta.
        /// </summary>
        /// <param name="concreteClass">Clase concreta.</param>
        /// <param name="commissAgentId">Propiedad clave CommissAgentId.</param>
        /// <returns>Clave primaria.</returns>
        protected static PrimaryKey InternalCreatePrimaryKey<T>(int commissAgentId)
        {
            Dictionary<string, object> keys = new Dictionary<string, object>();
            keys.Add(Properties.CommissAgentId, commissAgentId);

            return new PrimaryKey<T>(keys);
        }

        /// <summary>
        /// Crea una clave primaria para esta clase.
        /// </summary>
        /// <param name="commissAgentId">Propiedad clave CommissAgentId.</param>
        public static PrimaryKey CreatePrimaryKey(int commissAgentId)
        {
            return InternalCreatePrimaryKey<CommissAgent>(commissAgentId);
        }
        #endregion

        //*** Object Attributes ********************************

        /// <summary>
        /// Atributo para la propiedad IndividualId.
        /// </summary>
        private int _individualId;
        /// <summary>
        /// Atributo para la propiedad AgentAgencyId.
        /// </summary>
        private int _agentAgencyId;
        /// <summary>
        /// Atributo para la propiedad PolicyId.
        /// </summary>
        private int _policyId;
        /// <summary>
        /// Atributo para la propiedad EndorsementId.
        /// </summary>
        private int _endorsementId;
        /// <summary>
        /// Atributo para la propiedad CommissNum.
        /// </summary>
        private int _commissNum;
        /// <summary>
        /// Atributo para la propiedad AgentPartPercentage.
        /// </summary>
        private decimal _agentPartPercentage;
        /// <summary>
        /// Atributo para la propiedad StComissionPercentage.
        /// </summary>
        private decimal _stComissionPercentage;
        /// <summary>
        /// Atributo para la propiedad AdditCommissPercentage.
        /// </summary>
        private decimal? _additCommissPercentage = null;
        /// <summary>
        /// Atributo para la propiedad StDiscCommissPercentage.
        /// </summary>
        private decimal? _stDiscCommissPercentage = null;
        /// <summary>
        /// Atributo para la propiedad AdditDiscCommissPercentage.
        /// </summary>
        private decimal? _additDiscCommissPercentage = null;
        /// <summary>
        /// Atributo para la propiedad LineBusinessCode.
        /// </summary>
        private int? _lineBusinessCode = null;
        /// <summary>
        /// Atributo para la propiedad SubLineBusinessCode.
        /// </summary>
        private int? _subLineBusinessCode = null;
        /// <summary>
        /// Atributo para la propiedad InUnits.
        /// </summary>
        private bool _inUnits;
        /// <summary>
        /// Atributo para la propiedad IncCommissAdFacPercentage.
        /// </summary>
        private decimal? _incCommissAdFacPercentage = null;
        /// <summary>
        /// Atributo para la propiedad DimCommissAdFacPercentage.
        /// </summary>
        private decimal? _dimCommissAdFacPercentage = null;
        /// <summary>
        /// Atributo para la propiedad SchCommissPercentage.
        /// </summary>
        private decimal? _schCommissPercentage = null;
        /// <summary>
        /// Atributo para la propiedad StAgentComissionPercentage.
        /// </summary>
        private decimal? _stAgentComissionPercentage;
        //*** Object Constructors ********************************

        /// <summary>
        /// Constructor de instancia de la clase en base a las propiedades claves.
        /// </summary>
        /// <param name="commissAgentId">CommissAgentId key property.</param>
        public CommissAgent(int commissAgentId) :
            this(CommissAgent.CreatePrimaryKey(commissAgentId), null)
        {
        }

        /// <summary>
        /// Constructor de instancia de la clase en base a una clave primaria y a valores iniciales.
        /// </summary>
        /// <param name="key">
        /// Identificador de la instancia de la entidad.
        /// </param>
        /// <param name="initialValues">
        /// Valores para establecer el estado de la instancia.
        /// </param>
        public CommissAgent(PrimaryKey key, IDictionary initialValues) :
            base(key, initialValues)
        {
        }

        /*** Object Properties ********************************/
        /// <summary>
        /// Devuelve o setea el valor de la propiedad CommissAgentId.
        /// </summary>
        /// <value>Propiedad CommissAgentId.</value>
        [
        DescriptionKey("COMMISS_AGENT_ID_PROPERTY"),
        PersistentProperty(IsKey = true),
        ColumnMap(ColumnName = "COMMISS_AGENT_ID", DbType = System.Data.DbType.String),
        ]
        public int CommissAgentId
        {
            get
            {
                return (int)this._primaryKey[Properties.CommissAgentId];
            }
            set
            {
                this._primaryKey[Properties.CommissAgentId] = value;
            }
        }

        /// <summary>
        /// Devuelve o setea el valor de la propiedad IndividualId.
        /// </summary>
        /// <value>Propiedad IndividualId.</value>
        [
        DescriptionKey("INDIVIDUAL_ID_PROPERTY"),
        PersistentProperty(),
        ColumnMap(ColumnName = "INDIVIDUAL_ID", DbType = System.Data.DbType.String),
        ]
        public int IndividualId
        {
            get
            {
                return this._individualId;
            }
            set
            {
                this._individualId = value;
            }
        }

        /// <summary>
        /// Devuelve o setea el valor de la propiedad AgentAgencyId.
        /// </summary>
        /// <value>Propiedad AgentAgencyId.</value>
        [
        DescriptionKey("AGENT_AGENCY_ID_PROPERTY"),
        PersistentProperty(),
        ColumnMap(ColumnName = "AGENT_AGENCY_ID", DbType = System.Data.DbType.String),
        ]
        public int AgentAgencyId
        {
            get
            {
                return this._agentAgencyId;
            }
            set
            {
                this._agentAgencyId = value;
            }
        }

        /// <summary>
        /// Devuelve o setea el valor de la propiedad PolicyId.
        /// </summary>
        /// <value>Propiedad PolicyId.</value>
        [
        DescriptionKey("POLICY_ID_PROPERTY"),
        PersistentProperty(),
        ColumnMap(ColumnName = "POLICY_ID", DbType = System.Data.DbType.String),
        ]
        public int PolicyId
        {
            get
            {
                return this._policyId;
            }
            set
            {
                this._policyId = value;
            }
        }

        /// <summary>
        /// Devuelve o setea el valor de la propiedad EndorsementId.
        /// </summary>
        /// <value>Propiedad EndorsementId.</value>
        [
        DescriptionKey("ENDORSEMENT_ID_PROPERTY"),
        PersistentProperty(),
        ColumnMap(ColumnName = "ENDORSEMENT_ID", DbType = System.Data.DbType.String),
        ]
        public int EndorsementId
        {
            get
            {
                return this._endorsementId;
            }
            set
            {
                this._endorsementId = value;
            }
        }

        /// <summary>
        /// Devuelve o setea el valor de la propiedad CommissNum.
        /// </summary>
        /// <value>Propiedad CommissNum.</value>
        [
        DescriptionKey("COMMISS_NUM_PROPERTY"),
        PersistentProperty(),
        ColumnMap(ColumnName = "COMMISS_NUM", DbType = System.Data.DbType.String),
        ]
        public int CommissNum
        {
            get
            {
                return this._commissNum;
            }
            set
            {
                this._commissNum = value;
            }
        }

        /// <summary>
        /// Devuelve o setea el valor de la propiedad AgentPartPercentage.
        /// </summary>
        /// <value>Propiedad AgentPartPercentage.</value>
        [
        DescriptionKey("AGENT_PART_PERCENTAGE_PROPERTY"),
        PersistentProperty(),
        ColumnMap(ColumnName = "AGENT_PART_PCT", DbType = System.Data.DbType.Decimal),
        ]
        public decimal AgentPartPercentage
        {
            get
            {
                return this._agentPartPercentage;
            }
            set
            {
                this._agentPartPercentage = value;
            }
        }

        /// <summary>
        /// Devuelve o setea el valor de la propiedad StComissionPercentage.
        /// </summary>
        /// <value>Propiedad StComissionPercentage.</value>
        [
        DescriptionKey("ST_COMISSION_PERCENTAGE_PROPERTY"),
        PersistentProperty(),
        ColumnMap(ColumnName = "ST_COMISSION_PCT", DbType = System.Data.DbType.Decimal),
        ]
        public decimal StComissionPercentage
        {
            get
            {
                return this._stComissionPercentage;
            }
            set
            {
                this._stComissionPercentage = value;
            }
        }

        /// <summary>
        /// Devuelve o setea el valor de la propiedad AdditCommissPercentage.
        /// </summary>
        /// <value>Propiedad AdditCommissPercentage.</value>
        [
        DescriptionKey("ADDIT_COMMISS_PERCENTAGE_PROPERTY"),
        PersistentProperty(IsNullable = true),
        ColumnMap(ColumnName = "ADDIT_COMMISS_PCT", DbType = System.Data.DbType.Decimal),
        ]
        public decimal? AdditCommissPercentage
        {
            get
            {
                return this._additCommissPercentage;
            }
            set
            {
                this._additCommissPercentage = value;
            }
        }

        /// <summary>
        /// Devuelve o setea el valor de la propiedad StDiscCommissPercentage.
        /// </summary>
        /// <value>Propiedad StDiscCommissPercentage.</value>
        [
        DescriptionKey("ST_DISC_COMMISS_PERCENTAGE_PROPERTY"),
        PersistentProperty(IsNullable = true),
        ColumnMap(ColumnName = "ST_DISC_COMMISS_PCT", DbType = System.Data.DbType.Decimal),
        ]
        public decimal? StDiscCommissPercentage
        {
            get
            {
                return this._stDiscCommissPercentage;
            }
            set
            {
                this._stDiscCommissPercentage = value;
            }
        }

        /// <summary>
        /// Devuelve o setea el valor de la propiedad AdditDiscCommissPercentage.
        /// </summary>
        /// <value>Propiedad AdditDiscCommissPercentage.</value>
        [
        DescriptionKey("ADDIT_DISC_COMMISS_PERCENTAGE_PROPERTY"),
        PersistentProperty(IsNullable = true),
        ColumnMap(ColumnName = "ADDIT_DISC_COMMISS_PCT", DbType = System.Data.DbType.Decimal),
        ]
        public decimal? AdditDiscCommissPercentage
        {
            get
            {
                return this._additDiscCommissPercentage;
            }
            set
            {
                this._additDiscCommissPercentage = value;
            }
        }

        /// <summary>
        /// Devuelve o setea el valor de la propiedad LineBusinessCode.
        /// </summary>
        /// <value>Propiedad LineBusinessCode.</value>
        [
        DescriptionKey("LINE_BUSINESS_CODE_PROPERTY"),
        PersistentProperty(IsNullable = true),
        ColumnMap(ColumnName = "LINE_BUSINESS_CD", DbType = System.Data.DbType.String),
        ]
        public int? LineBusinessCode
        {
            get
            {
                return this._lineBusinessCode;
            }
            set
            {
                this._lineBusinessCode = value;
            }
        }

        /// <summary>
        /// Devuelve o setea el valor de la propiedad SubLineBusinessCode.
        /// </summary>
        /// <value>Propiedad SubLineBusinessCode.</value>
        [
        DescriptionKey("SUB_LINE_BUSINESS_CODE_PROPERTY"),
        PersistentProperty(IsNullable = true),
        ColumnMap(ColumnName = "SUB_LINE_BUSINESS_CD", DbType = System.Data.DbType.String),
        ]
        public int? SubLineBusinessCode
        {
            get
            {
                return this._subLineBusinessCode;
            }
            set
            {
                this._subLineBusinessCode = value;
            }
        }

        /// <summary>
        /// Devuelve o setea el valor de la propiedad InUnits.
        /// </summary>
        /// <value>Propiedad InUnits.</value>
        [
        DescriptionKey("IN_UNITS_PROPERTY"),
        PersistentProperty(),
        ColumnMap(ColumnName = "IN_UNITS", DbType = System.Data.DbType.String),
        ]
        public bool InUnits
        {
            get
            {
                return this._inUnits;
            }
            set
            {
                this._inUnits = value;
            }
        }

        /// <summary>
        /// Devuelve o setea el valor de la propiedad IncCommissAdFacPercentage.
        /// </summary>
        /// <value>Propiedad IncCommissAdFacPercentage.</value>
        [
        DescriptionKey("INC_COMMISS_AD_FAC_PERCENTAGE_PROPERTY"),
        PersistentProperty(IsNullable = true),
        ColumnMap(ColumnName = "INC_COMMISS_AD_FAC_PCT", DbType = System.Data.DbType.Decimal),
        ]
        public decimal? IncCommissAdFacPercentage
        {
            get
            {
                return this._incCommissAdFacPercentage;
            }
            set
            {
                this._incCommissAdFacPercentage = value;
            }
        }

        /// <summary>
        /// Devuelve o setea el valor de la propiedad DimCommissAdFacPercentage.
        /// </summary>
        /// <value>Propiedad DimCommissAdFacPercentage.</value>
        [
        DescriptionKey("DIM_COMMISS_AD_FAC_PERCENTAGE_PROPERTY"),
        PersistentProperty(IsNullable = true),
        ColumnMap(ColumnName = "DIM_COMMISS_AD_FAC_PCT", DbType = System.Data.DbType.Decimal),
        ]
        public decimal? DimCommissAdFacPercentage
        {
            get
            {
                return this._dimCommissAdFacPercentage;
            }
            set
            {
                this._dimCommissAdFacPercentage = value;
            }
        }

        /// <summary>
        /// Devuelve o setea el valor de la propiedad SchCommissPercentage.
        /// </summary>
        /// <value>Propiedad SchCommissPercentage.</value>
        [
        DescriptionKey("SCH_COMMISS_PERCENTAGE_PROPERTY"),
        PersistentProperty(IsNullable = true),
        ColumnMap(ColumnName = "SCH_COMMISS_PCT", DbType = System.Data.DbType.Decimal),
        ]
        public decimal? SchCommissPercentage
        {
            get
            {
                return this._schCommissPercentage;
            }
            set
            {
                this._schCommissPercentage = value;
            }
        }
        /// <summary>
        /// Devuelve o setea el valor de la propiedad StAgentComissionPercentage.
        /// </summary>
        /// <value>Propiedad StAgentComissionPercentage.</value>
        [
        DescriptionKey("AGENT_ST_COMISSION_PCT_PROPERTY"),
        PersistentProperty(IsNullable = true),
        ColumnMap(ColumnName = "AGENT_ST_COMISSION_PCT", DbType = System.Data.DbType.Decimal),
        ]
        public decimal? StAgentComissionPercentage
        {
            get
            {
                return this._stAgentComissionPercentage;
            }
            set
            {
                this._stAgentComissionPercentage = value;
            }
        }

    }
}