/******************************************
 * Code generated by GEB (Version: 2.2.0.0)
 * Template: Sistran.Core.Application.Issuance.PayerPayment.dict v1.0
 * FileSize=12047 Header=252 CRC=1325479125
 ******************************************/
using System;
using System.Collections;
using System.Collections.Generic;
using Sistran.Core.Framework;
using Sistran.Core.Framework.DAF;

namespace Sistran.Core.Application.Issuance.Entities
{
    /// <summary>
    /// Definición de entidad PayerPayment.
    /// </summary>
    [
    PersistentClass("Sistran.Core.Application.Issuance.PayerPayment.dict"),
    Serializable(),
    DescriptionKey("PAYER_PAYMENT_ENTITY"),
    TableMap(TableName="PAYER_PAYMENT", Schema="ISS"),
    ]
    public partial class PayerPayment :
        BusinessObject2
    {
#region static
		/// <summary>
		/// Propiedades públicas de la entidad.
		/// </summary>
		public static class Properties
		{
			public static readonly string EndorsementId = "EndorsementId";
			public static readonly string PolicyId = "PolicyId";
			public static readonly string PaymentNum = "PaymentNum";
			public static readonly string PayerId = "PayerId";
			public static readonly string PayExpDate = "PayExpDate";
			public static readonly string PaymentPercentage = "PaymentPercentage";
			public static readonly string Amount = "Amount";
			public static readonly string AgtPayExpDate = "AgtPayExpDate";
			public static readonly string PayerPaymentId = "PayerPaymentId";
			public static readonly string LocalAmount = "LocalAmount";
			public static readonly string MainAmount = "MainAmount";
			public static readonly string MainLocalAmount = "MainLocalAmount";
			public static readonly string PaymentState = "PaymentState";
		}

		/// <summary>
		/// Crea una clave primaria para una clase concreta.
		/// </summary>
		/// <param name="concreteClass">Clase concreta.</param>
		/// <param name="endorsementId">Propiedad clave EndorsementId.</param>
		/// <param name="policyId">Propiedad clave PolicyId.</param>
		/// <param name="paymentNum">Propiedad clave PaymentNum.</param>
		/// <param name="payerId">Propiedad clave PayerId.</param>
		/// <returns>Clave primaria.</returns>
	    protected static PrimaryKey InternalCreatePrimaryKey<T>(int endorsementId, int policyId, int paymentNum, int payerId)
	    {
		    Dictionary<string, object> keys = new Dictionary<string, object>();
		    keys.Add(Properties.EndorsementId, endorsementId);
		    keys.Add(Properties.PolicyId, policyId);
		    keys.Add(Properties.PaymentNum, paymentNum);
		    keys.Add(Properties.PayerId, payerId);

		    return new PrimaryKey<T>(keys);
	    }

		/// <summary>
		/// Crea una clave primaria para esta clase.
		/// </summary>
		/// <param name="endorsementId">Propiedad clave EndorsementId.</param>
		/// <param name="policyId">Propiedad clave PolicyId.</param>
		/// <param name="paymentNum">Propiedad clave PaymentNum.</param>
		/// <param name="payerId">Propiedad clave PayerId.</param>
		public static PrimaryKey CreatePrimaryKey(int endorsementId, int policyId, int paymentNum, int payerId)
	    {
			return InternalCreatePrimaryKey<PayerPayment>(endorsementId, policyId, paymentNum, payerId);
		}
#endregion

	    //*** Object Attributes ********************************

		/// <summary>
		/// Atributo para la propiedad PayExpDate.
		/// </summary>
        private DateTime _payExpDate;
		/// <summary>
		/// Atributo para la propiedad PaymentPercentage.
		/// </summary>
        private decimal? _paymentPercentage = null;
		/// <summary>
		/// Atributo para la propiedad Amount.
		/// </summary>
        private decimal _amount;
		/// <summary>
		/// Atributo para la propiedad AgtPayExpDate.
		/// </summary>
        private DateTime? _agtPayExpDate = null;
		/// <summary>
		/// Atributo para la propiedad PayerPaymentId.
		/// </summary>
        private int _payerPaymentId;
		/// <summary>
		/// Atributo para la propiedad LocalAmount.
		/// </summary>
        private decimal? _localAmount = null;
		/// <summary>
		/// Atributo para la propiedad MainAmount.
		/// </summary>
        private decimal? _mainAmount = null;
		/// <summary>
		/// Atributo para la propiedad MainLocalAmount.
		/// </summary>
        private decimal? _mainLocalAmount = null;
		/// <summary>
		/// Atributo para la propiedad PaymentState.
		/// </summary>
        private int? _paymentState = null;
	    //*** Object Constructors ********************************

		/// <summary>
		/// Constructor de instancia de la clase en base a las propiedades claves.
		/// </summary>
		/// <param name="endorsementId">EndorsementId key property.</param>
		/// <param name="policyId">PolicyId key property.</param>
		/// <param name="paymentNum">PaymentNum key property.</param>
		/// <param name="payerId">PayerId key property.</param>
	    public PayerPayment(int endorsementId, int policyId, int paymentNum, int payerId):
			this(PayerPayment.CreatePrimaryKey(endorsementId, policyId, paymentNum, payerId), null)
	    {
	    }

		/// <summary>
		/// Constructor de instancia de la clase en base a una clave primaria y a valores iniciales.
		/// </summary>
		/// <param name="key">
		/// Identificador de la instancia de la entidad.
		/// </param>
		/// <param name="initialValues">
		/// Valores para establecer el estado de la instancia.
		/// </param>
	    public PayerPayment(PrimaryKey key, IDictionary initialValues):
			base(key, initialValues)
	    {
	    }

	    /*** Object Properties ********************************/
		/// <summary>
		/// Devuelve o setea el valor de la propiedad EndorsementId.
		/// </summary>
		/// <value>Propiedad EndorsementId.</value>
	    [
		DescriptionKey("ENDORSEMENT_ID_PROPERTY"),
		PersistentProperty(IsKey = true),
        ColumnMap(ColumnName="ENDORSEMENT_ID", DbType=System.Data.DbType.String),
	    ]
        public int EndorsementId
	    {
		    get
		    {
				return (int)this._primaryKey[Properties.EndorsementId];
		    }
		    set
		    {
				this._primaryKey[Properties.EndorsementId] = value;
			}
	    }

		/// <summary>
		/// Devuelve o setea el valor de la propiedad PolicyId.
		/// </summary>
		/// <value>Propiedad PolicyId.</value>
	    [
		DescriptionKey("POLICY_ID_PROPERTY"),
		PersistentProperty(IsKey = true),
        ColumnMap(ColumnName="POLICY_ID", DbType=System.Data.DbType.String),
	    ]
        public int PolicyId
	    {
		    get
		    {
				return (int)this._primaryKey[Properties.PolicyId];
		    }
		    set
		    {
				this._primaryKey[Properties.PolicyId] = value;
			}
	    }

		/// <summary>
		/// Devuelve o setea el valor de la propiedad PaymentNum.
		/// </summary>
		/// <value>Propiedad PaymentNum.</value>
	    [
		DescriptionKey("PAYMENT_NUM_PROPERTY"),
		PersistentProperty(IsKey = true),
        ColumnMap(ColumnName="PAYMENT_NUM", DbType=System.Data.DbType.String),
	    ]
        public int PaymentNum
	    {
		    get
		    {
				return (int)this._primaryKey[Properties.PaymentNum];
		    }
		    set
		    {
				this._primaryKey[Properties.PaymentNum] = value;
			}
	    }

		/// <summary>
		/// Devuelve o setea el valor de la propiedad PayerId.
		/// </summary>
		/// <value>Propiedad PayerId.</value>
	    [
		DescriptionKey("PAYER_ID_PROPERTY"),
		PersistentProperty(IsKey = true),
        ColumnMap(ColumnName="PAYER_ID", DbType=System.Data.DbType.String),
	    ]
        public int PayerId
	    {
		    get
		    {
				return (int)this._primaryKey[Properties.PayerId];
		    }
		    set
		    {
				this._primaryKey[Properties.PayerId] = value;
			}
	    }

		/// <summary>
		/// Devuelve o setea el valor de la propiedad PayExpDate.
		/// </summary>
		/// <value>Propiedad PayExpDate.</value>
	    [
		DescriptionKey("PAY_EXP_DATE_PROPERTY"),
		PersistentProperty(),
        ColumnMap(ColumnName="PAY_EXP_DATE", DbType=System.Data.DbType.String),
	    ]
        public DateTime PayExpDate
	    {
		    get
		    {
			    return this._payExpDate;
		    }
		    set
		    {
				this._payExpDate = value;
			}
	    }

		/// <summary>
		/// Devuelve o setea el valor de la propiedad PaymentPercentage.
		/// </summary>
		/// <value>Propiedad PaymentPercentage.</value>
	    [
		DescriptionKey("PAYMENT_PERCENTAGE_PROPERTY"),
		PersistentProperty(IsNullable = true),
        ColumnMap(ColumnName="PAYMENT_PCT", DbType=System.Data.DbType.Decimal),
	    ]
        public decimal? PaymentPercentage
	    {
		    get
		    {
			    return this._paymentPercentage;
		    }
		    set
		    {
				this._paymentPercentage = value;
			}
	    }

		/// <summary>
		/// Devuelve o setea el valor de la propiedad Amount.
		/// </summary>
		/// <value>Propiedad Amount.</value>
	    [
		DescriptionKey("AMOUNT_PROPERTY"),
		PersistentProperty(),
        ColumnMap(ColumnName="AMOUNT", DbType=System.Data.DbType.Decimal),
	    ]
        public decimal Amount
	    {
		    get
		    {
			    return this._amount;
		    }
		    set
		    {
				this._amount = value;
			}
	    }

		/// <summary>
		/// Devuelve o setea el valor de la propiedad AgtPayExpDate.
		/// </summary>
		/// <value>Propiedad AgtPayExpDate.</value>
	    [
		DescriptionKey("AGT_PAY_EXP_DATE_PROPERTY"),
		PersistentProperty(IsNullable = true),
        ColumnMap(ColumnName="AGT_PAY_EXP_DATE", DbType=System.Data.DbType.String),
	    ]
        public DateTime? AgtPayExpDate
	    {
		    get
		    {
			    return this._agtPayExpDate;
		    }
		    set
		    {
				this._agtPayExpDate = value;
			}
	    }

		/// <summary>
		/// Devuelve o setea el valor de la propiedad PayerPaymentId.
		/// </summary>
		/// <value>Propiedad PayerPaymentId.</value>
	    [
		DescriptionKey("PAYER_PAYMENT_ID_PROPERTY"),
		PersistentProperty(),
        ColumnMap(ColumnName="PAYER_PAYMENT_ID", DbType=System.Data.DbType.String),
	    ]
        public int PayerPaymentId
	    {
		    get
		    {
			    return this._payerPaymentId;
		    }
		    set
		    {
				this._payerPaymentId = value;
			}
	    }

		/// <summary>
		/// Devuelve o setea el valor de la propiedad LocalAmount.
		/// </summary>
		/// <value>Propiedad LocalAmount.</value>
	    [
		DescriptionKey("LOCAL_AMOUNT_PROPERTY"),
		PersistentProperty(IsNullable = true),
        ColumnMap(ColumnName="LOCAL_AMOUNT", DbType=System.Data.DbType.Decimal),
	    ]
        public decimal? LocalAmount
	    {
		    get
		    {
			    return this._localAmount;
		    }
		    set
		    {
				this._localAmount = value;
			}
	    }

		/// <summary>
		/// Devuelve o setea el valor de la propiedad MainAmount.
		/// </summary>
		/// <value>Propiedad MainAmount.</value>
	    [
		DescriptionKey("MAIN_AMOUNT_PROPERTY"),
		PersistentProperty(IsNullable = true),
        ColumnMap(ColumnName="MAIN_AMOUNT", DbType=System.Data.DbType.Decimal),
	    ]
        public decimal? MainAmount
	    {
		    get
		    {
			    return this._mainAmount;
		    }
		    set
		    {
				this._mainAmount = value;
			}
	    }

		/// <summary>
		/// Devuelve o setea el valor de la propiedad MainLocalAmount.
		/// </summary>
		/// <value>Propiedad MainLocalAmount.</value>
	    [
		DescriptionKey("MAIN_LOCAL_AMOUNT_PROPERTY"),
		PersistentProperty(IsNullable = true),
        ColumnMap(ColumnName="MAIN_LOCAL_AMOUNT", DbType=System.Data.DbType.Decimal),
	    ]
        public decimal? MainLocalAmount
	    {
		    get
		    {
			    return this._mainLocalAmount;
		    }
		    set
		    {
				this._mainLocalAmount = value;
			}
	    }

		/// <summary>
		/// Devuelve o setea el valor de la propiedad PaymentState.
		/// </summary>
		/// <value>Propiedad PaymentState.</value>
	    [
		DescriptionKey("PAYMENT_STATE_PROPERTY"),
		PersistentProperty(IsNullable = true),
        ColumnMap(ColumnName="PAYMENT_STATE", DbType=System.Data.DbType.String),
	    ]
        public int? PaymentState
	    {
		    get
		    {
			    return this._paymentState;
		    }
		    set
		    {
				this._paymentState = value;
			}
	    }
    }
}