/******************************************
 * Code generated by GEB (Version: 2.2.0.0)
 * Template: Sistran.Core.Application.UniquePersonV1.SupplierGroupSupplier.dict v1.0
 * FileSize=4904 Header=266 CRC=4180758351
 ******************************************/
using System;
using System.Collections;
using System.Collections.Generic;
using Sistran.Core.Framework;
using Sistran.Core.Framework.DAF;

namespace Sistran.Core.Application.UniquePersonV1.Entities
{
    /// <summary>
    /// Definición de entidad SupplierGroupSupplier.
    /// </summary>
    [
    PersistentClass("Sistran.Core.Application.UniquePersonV1.SupplierGroupSupplier.dict"),
    Serializable(),
    DescriptionKey("SUPPLIER_GROUP_SUPPLIER_ENTITY"),
    TableMap(TableName="SUPPLIER_GROUP_SUPPLIER", Schema="UP"),
    ]
    public partial class SupplierGroupSupplier :
        BusinessObject2
    {
#region static
		/// <summary>
		/// Propiedades públicas de la entidad.
		/// </summary>
		public static class Properties
		{
			public static readonly string SupplierGroupSupplierCode = "SupplierGroupSupplierCode";
			public static readonly string SupplierCode = "SupplierCode";
			public static readonly string GroupSupplierCode = "GroupSupplierCode";
		}

		/// <summary>
		/// Crea una clave primaria para una clase concreta.
		/// </summary>
		/// <param name="concreteClass">Clase concreta.</param>
		/// <param name="supplierGroupSupplierCode">Propiedad clave SupplierGroupSupplierCode.</param>
		/// <returns>Clave primaria.</returns>
	    protected static PrimaryKey InternalCreatePrimaryKey<T>(int supplierGroupSupplierCode)
	    {
		    Dictionary<string, object> keys = new Dictionary<string, object>();
		    keys.Add(Properties.SupplierGroupSupplierCode, supplierGroupSupplierCode);

		    return new PrimaryKey<T>(keys);
	    }
        protected static PrimaryKey InternalCreatePrimaryKey<T>()
        {
            Dictionary<string, object> keys = new Dictionary<string, object>();
            keys.Add(Properties.SupplierGroupSupplierCode, null);

            return new PrimaryKey<T>(keys);
        }

        /// <summary>
        /// Crea una clave primaria para esta clase.
        /// </summary>
        /// <param name="supplierGroupSupplierCode">Propiedad clave SupplierGroupSupplierCode.</param>
        public static PrimaryKey CreatePrimaryKey(int supplierGroupSupplierCode)
	    {
			return InternalCreatePrimaryKey<SupplierGroupSupplier>(supplierGroupSupplierCode);
		}
        public static PrimaryKey CreatePrimaryKey()
        {
            return InternalCreatePrimaryKey<SupplierGroupSupplier>();
        }
        #endregion

        //*** Object Attributes ********************************

        /// <summary>
        /// Atributo para la propiedad SupplierCode.
        /// </summary>
        private int _supplierCode;
		/// <summary>
		/// Atributo para la propiedad GroupSupplierCode.
		/// </summary>
        private int _groupSupplierCode;
	    //*** Object Constructors ********************************

		/// <summary>
		/// Constructor de instancia de la clase en base a las propiedades claves.
		/// </summary>
		/// <param name="supplierGroupSupplierCode">SupplierGroupSupplierCode key property.</param>
	    public SupplierGroupSupplier(int supplierGroupSupplierCode):
			this(SupplierGroupSupplier.CreatePrimaryKey(supplierGroupSupplierCode), null)
	    {
	    }
        public SupplierGroupSupplier() :
           this(SupplierGroupSupplier.CreatePrimaryKey(), null)
        {
        }

        /// <summary>
        /// Constructor de instancia de la clase en base a una clave primaria y a valores iniciales.
        /// </summary>
        /// <param name="key">
        /// Identificador de la instancia de la entidad.
        /// </param>
        /// <param name="initialValues">
        /// Valores para establecer el estado de la instancia.
        /// </param>
        public SupplierGroupSupplier(PrimaryKey key, IDictionary initialValues):
			base(key, initialValues)
	    {
	    }

	    /*** Object Properties ********************************/
		/// <summary>
		/// Devuelve o setea el valor de la propiedad SupplierGroupSupplierCode.
		/// </summary>
		/// <value>Propiedad SupplierGroupSupplierCode.</value>
	    [
		DescriptionKey("SUPPLIER_GROUP_SUPPLIER_CODE_PROPERTY"),
		PersistentProperty(IsKey = true, KeyType = "Identity"),
        ColumnMap(ColumnName="SUPPLIER_GROUP_SUPPLIER_CD", DbType=System.Data.DbType.String),
	    ]
        public int SupplierGroupSupplierCode
	    {
		    get
		    {
				return (int)this._primaryKey[Properties.SupplierGroupSupplierCode];
		    }
		    set
		    {
				this._primaryKey[Properties.SupplierGroupSupplierCode] = value;
			}
	    }

		/// <summary>
		/// Devuelve o setea el valor de la propiedad SupplierCode.
		/// </summary>
		/// <value>Propiedad SupplierCode.</value>
	    [
		DescriptionKey("SUPPLIER_CODE_PROPERTY"),
		PersistentProperty(),
        ColumnMap(ColumnName="SUPPLIER_CD", DbType=System.Data.DbType.String),
	    ]
        public int SupplierCode
	    {
		    get
		    {
			    return this._supplierCode;
		    }
		    set
		    {
				this._supplierCode = value;
			}
	    }

		/// <summary>
		/// Devuelve o setea el valor de la propiedad GroupSupplierCode.
		/// </summary>
		/// <value>Propiedad GroupSupplierCode.</value>
	    [
		DescriptionKey("GROUP_SUPPLIER_CODE_PROPERTY"),
		PersistentProperty(),
        ColumnMap(ColumnName="GROUP_SUPPLIER_CD", DbType=System.Data.DbType.String),
	    ]
        public int GroupSupplierCode
	    {
		    get
		    {
			    return this._groupSupplierCode;
		    }
		    set
		    {
				this._groupSupplierCode = value;
			}
	    }

    }
}