using Sistran.Core.Application.Utilities.Helper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Sistran.Core.Application.Utilities.RulesEngine
{
    public class RuleConceptAutomaticQuotaBusiness
    {
        public static int Id = int.Parse(EnumHelper.GetEnumParameterValue(Enums.FacadeType.RULE_FACADE_BUSINESS_AUTOMATIC_QUOTA).ToString());

        public static KeyValuePair<string, int> InitialCashAndEquivalent => new KeyValuePair<string, int>("InitialCashAndEquivalent", Id);
        public static KeyValuePair<string, int> RelativeCashAndEquivalent => new KeyValuePair<string, int>("RelativeCashAndEquivalent", Id);
        public static KeyValuePair<string, int> InitialOperatingIncome => new KeyValuePair<string, int>("InitialOperatingIncome", Id);
        public static KeyValuePair<string, int> EndOperatingIncome => new KeyValuePair<string, int>("EndOperatingIncome", Id);
        public static KeyValuePair<string, int> AbsoluteOperatingIncome => new KeyValuePair<string, int>("AbsoluteOperatingIncome", Id);
        public static KeyValuePair<string, int> InitialCosts => new KeyValuePair<string, int>("InitialCosts", Id);
        public static KeyValuePair<string, int> EndCosts => new KeyValuePair<string, int>("EndCosts", Id);
        public static KeyValuePair<string, int> AbsoluteCosts => new KeyValuePair<string, int>("AbsoluteCosts", Id);
        public static KeyValuePair<string, int> InitialGrossProfit => new KeyValuePair<string, int>("InitialGrossProfit", Id);
        public static KeyValuePair<string, int> EndGrossProfit => new KeyValuePair<string, int>("EndGrossProfit", Id);
        public static KeyValuePair<string, int> AbsoluteGrossProfit => new KeyValuePair<string, int>("AbsoluteGrossProfit", Id);
        public static KeyValuePair<string, int> InitialCostsAndExpenses => new KeyValuePair<string, int>("InitialCostsAndExpenses", Id);
        public static KeyValuePair<string, int> EndCostsAndExpenses => new KeyValuePair<string, int>("EndCostsAndExpenses", Id);
        public static KeyValuePair<string, int> AbsoluteCostsAndExpenses => new KeyValuePair<string, int>("AbsoluteCostsAndExpenses", Id);
        public static KeyValuePair<string, int> InitialOperationalUtility => new KeyValuePair<string, int>("InitialOperationalUtility", Id);
        public static KeyValuePair<string, int> EndOperationalUtility => new KeyValuePair<string, int>("EndOperationalUtility", Id);
        public static KeyValuePair<string, int> AbsoluteOperationalUtility => new KeyValuePair<string, int>("AbsoluteOperationalUtility", Id);
        public static KeyValuePair<string, int> InitialIncomeAndExpensesNoOperating => new KeyValuePair<string, int>("InitialIncomeAndExpensesNoOperating", Id);
        public static KeyValuePair<string, int> EndIncomeAndExpensesNoOperating => new KeyValuePair<string, int>("EndIncomeAndExpensesNoOperating", Id);
        public static KeyValuePair<string, int> AbsoluteIncomeAndExpensesNoOperating => new KeyValuePair<string, int>("AbsoluteIncomeAndExpensesNoOperating", Id);
        public static KeyValuePair<string, int> InitialIncomeBeforeTaxes => new KeyValuePair<string, int>("InitialIncomeBeforeTaxes", Id);
        public static KeyValuePair<string, int> EndIncomeBeforeTaxes => new KeyValuePair<string, int>("EndIncomeBeforeTaxes", Id);
        public static KeyValuePair<string, int> AbsoluteIncomeBeforeTaxes => new KeyValuePair<string, int>("AbsoluteIncomeBeforeTaxes", Id);
        public static KeyValuePair<string, int> InitialTaxProvition => new KeyValuePair<string, int>("InitialTaxProvition", Id);
        public static KeyValuePair<string, int> EndTaxProvition => new KeyValuePair<string, int>("EndTaxProvition", Id);
        public static KeyValuePair<string, int> AbsoluteTaxProvition => new KeyValuePair<string, int>("AbsoluteTaxProvition", Id);
        public static KeyValuePair<string, int> InitialNetProfit => new KeyValuePair<string, int>("InitialNetProfit", Id);
        public static KeyValuePair<string, int> EndNetProfit => new KeyValuePair<string, int>("EndNetProfit", Id);
        public static KeyValuePair<string, int> AbsoluteNetProfit => new KeyValuePair<string, int>("AbsoluteNetProfit", Id);
        public static KeyValuePair<string, int> RelativeNetProfit => new KeyValuePair<string, int>("RelativeNetProfit", Id);
        public static KeyValuePair<string, int> RelativeTaxProvition => new KeyValuePair<string, int>("RelativeTaxProvition", Id);
        public static KeyValuePair<string, int> RelativeIncomeBeforeTaxes => new KeyValuePair<string, int>("RelativeIncomeBeforeTaxes", Id);
        public static KeyValuePair<string, int> RelativeIncomeAndExpensesNoOperating => new KeyValuePair<string, int>("RelativeIncomeAndExpensesNoOperating", Id);
        public static KeyValuePair<string, int> RelativeOperationalUtility => new KeyValuePair<string, int>("RelativeOperationalUtility", Id);
        public static KeyValuePair<string, int> RelativeCostsAndExpenses => new KeyValuePair<string, int>("RelativeCostsAndExpenses", Id);
        public static KeyValuePair<string, int> RelativeGrossProfit => new KeyValuePair<string, int>("RelativeGrossProfit", Id);
        public static KeyValuePair<string, int> RelativeCosts => new KeyValuePair<string, int>("RelativeCosts", Id);
        public static KeyValuePair<string, int> RelativeOperatingIncome => new KeyValuePair<string, int>("RelativeOperatingIncome", Id);
        public static KeyValuePair<string, int> AbsoluteAccountsReceivable => new KeyValuePair<string, int>("AbsoluteAccountsReceivable", Id);
        public static KeyValuePair<string, int> RelativeAccountsReceivable => new KeyValuePair<string, int>("RelativeAccountsReceivable", Id);
        public static KeyValuePair<string, int> AbsoluteCapitalReserves => new KeyValuePair<string, int>("AbsoluteCapitalReserves", Id);
        public static KeyValuePair<string, int> RelativeCapitalBuffers => new KeyValuePair<string, int>("RelativeCapitalBuffers", Id);
        public static KeyValuePair<string, int> AbsoluteCashAndEquivalents => new KeyValuePair<string, int>("AbsoluteCashAndEquivalents", Id);
        public static KeyValuePair<string, int> RelativeCurrentAssets => new KeyValuePair<string, int>("RelativeCurrentAssets", Id);
        public static KeyValuePair<string, int> AbsoluteCurrentAssets => new KeyValuePair<string, int>("AbsoluteCurrentAssets", Id);
        public static KeyValuePair<string, int> RelativeCurrentLiabilities => new KeyValuePair<string, int>("RelativeCurrentLiabilities", Id);
        public static KeyValuePair<string, int> RelativeInventories => new KeyValuePair<string, int>("RelativeInventories", Id);
        public static KeyValuePair<string, int> RelativeLongTermFinancialObligations => new KeyValuePair<string, int>("RelativeLongTermFinancialObligations", Id);
        public static KeyValuePair<string, int> RelativeNonCurrentAssets => new KeyValuePair<string, int>("RelativeNonCurrentAssets", Id);
        public static KeyValuePair<string, int> RelativeNonCurrentLiabilities => new KeyValuePair<string, int>("RelativeNonCurrentLiabilities", Id);
        public static KeyValuePair<string, int> RelativeOwnershipPlantAndEquipment => new KeyValuePair<string, int>("RelativeOwnershipPlantAndEquipment", Id);
        public static KeyValuePair<string, int> RelativeResultsOfPreviousYears => new KeyValuePair<string, int>("RelativeResultsOfPreviousYears", Id);
        public static KeyValuePair<string, int> RelativeShareCapital => new KeyValuePair<string, int>("RelativeShareCapital", Id);
        public static KeyValuePair<string, int> RelativeShortTermFinancialObligations => new KeyValuePair<string, int>("RelativeShortTermFinancialObligations", Id);
        public static KeyValuePair<string, int> RelativeSuppliers => new KeyValuePair<string, int>("RelativeSuppliers", Id);
        public static KeyValuePair<string, int> RelativeTotalAssets => new KeyValuePair<string, int>("RelativeTotalAssets", Id);
        public static KeyValuePair<string, int> RelativeTotalEquity => new KeyValuePair<string, int>("RelativeTotalEquity", Id);
        public static KeyValuePair<string, int> TotalRelativeLiabilities => new KeyValuePair<string, int>("TotalRelativeLiabilities", Id);
        public static KeyValuePair<string, int> AbsoluteCurrentLiabilities => new KeyValuePair<string, int>("AbsoluteCurrentLiabilities", Id);
        public static KeyValuePair<string, int> AbsoluteInventories => new KeyValuePair<string, int>("AbsoluteInventories", Id);
        public static KeyValuePair<string, int> AbsoluteLongTermFinancialObligations => new KeyValuePair<string, int>("AbsoluteLongTermFinancialObligations", Id);
        public static KeyValuePair<string, int> AbsoluteNonCurrentAssets => new KeyValuePair<string, int>("AbsoluteNonCurrentAssets", Id);
        public static KeyValuePair<string, int> InitialTotalLiabilities => new KeyValuePair<string, int>("InitialTotalLiabilities", Id);
        public static KeyValuePair<string, int> AbsolutePropertyPlantAndEquipment => new KeyValuePair<string, int>("AbsolutePropertyPlantAndEquipment", Id);
        public static KeyValuePair<string, int> AbsoluteResultsOfPreviousYears => new KeyValuePair<string, int>("AbsoluteResultsOfPreviousYears", Id);
        public static KeyValuePair<string, int> AbsoluteShareCapital => new KeyValuePair<string, int>("AbsoluteShareCapital", Id);
        public static KeyValuePair<string, int> AbsoluteShortTermFinancialObligations => new KeyValuePair<string, int>("AbsoluteShortTermFinancialObligations", Id);
        public static KeyValuePair<string, int> AbsoluteSuppliers => new KeyValuePair<string, int>("AbsoluteSuppliers", Id);
        public static KeyValuePair<string, int> AbsoluteTotalAssets => new KeyValuePair<string, int>("AbsoluteTotalAssets", Id);
        public static KeyValuePair<string, int> AbsoluteTotalEquity => new KeyValuePair<string, int>("AbsoluteTotalEquity", Id);
        public static KeyValuePair<string, int> AbsoluteTotalLiability => new KeyValuePair<string, int>("AbsoluteTotalLiability", Id);
        public static KeyValuePair<string, int> CurrentActiveEnd => new KeyValuePair<string, int>("CurrentActiveEnd", Id);
        public static KeyValuePair<string, int> EffectiveEndAndEquivalents => new KeyValuePair<string, int>("EffectiveEndAndEquivalents", Id);
        public static KeyValuePair<string, int> EndCurrentLiabilities => new KeyValuePair<string, int>("EndCurrentLiabilities", Id);
        public static KeyValuePair<string, int> EndOfNonCurrentLiabilities => new KeyValuePair<string, int>("EndOfNonCurrentLiabilities", Id);
        public static KeyValuePair<string, int> FinalAccountsReceivable => new KeyValuePair<string, int>("FinalAccountsReceivable", Id);
        public static KeyValuePair<string, int> FinalCapitalReserves => new KeyValuePair<string, int>("FinalCapitalReserves", Id);
        public static KeyValuePair<string, int> FinalInventories => new KeyValuePair<string, int>("FinalInventories", Id);
        public static KeyValuePair<string, int> Finallongtermfinancialobligations => new KeyValuePair<string, int>("Finallongtermfinancialobligations", Id);
        public static KeyValuePair<string, int> FinalPropertyPlantAndEquipment => new KeyValuePair<string, int>("FinalPropertyPlantAndEquipment", Id);
        public static KeyValuePair<string, int> FinalResultsOfPreviousYears => new KeyValuePair<string, int>("FinalResultsOfPreviousYears", Id);
        public static KeyValuePair<string, int> FinalShareCapital => new KeyValuePair<string, int>("FinalShareCapital", Id);
        public static KeyValuePair<string, int> FinalShortTermFinancialObligations => new KeyValuePair<string, int>("FinalShortTermFinancialObligations", Id);
        public static KeyValuePair<string, int> FinalSuppliers => new KeyValuePair<string, int>("FinalSuppliers", Id);
        public static KeyValuePair<string, int> FinalTotalActive => new KeyValuePair<string, int>("FinalTotalActive", Id);
        public static KeyValuePair<string, int> FinalTotalHeritage => new KeyValuePair<string, int>("FinalTotalHeritage", Id);
        public static KeyValuePair<string, int> FinalTotalPassive => new KeyValuePair<string, int>("FinalTotalPassive", Id);
        public static KeyValuePair<string, int> InitialAccountsReceivable => new KeyValuePair<string, int>("InitialAccountsReceivable", Id);
        public static KeyValuePair<string, int> InitialCapitalReserves => new KeyValuePair<string, int>("InitialCapitalReserves", Id);
        public static KeyValuePair<string, int> InitialCurrentAssets => new KeyValuePair<string, int>("InitialCurrentAssets", Id);
        public static KeyValuePair<string, int> InitialCurrentLiabilities => new KeyValuePair<string, int>("InitialCurrentLiabilities", Id);
        public static KeyValuePair<string, int> InitialInventories => new KeyValuePair<string, int>("InitialInventories", Id);
        public static KeyValuePair<string, int> InitialLongTermFinancialObligations => new KeyValuePair<string, int>("InitialLongTermFinancialObligations", Id);
        public static KeyValuePair<string, int> InitialNonCurrentActive => new KeyValuePair<string, int>("InitialNonCurrentActive", Id);
        public static KeyValuePair<string, int> InitialNonCurrentLiabilities => new KeyValuePair<string, int>("InitialNonCurrentLiabilities", Id);
        public static KeyValuePair<string, int> InitialPropertyPlantAndEquipment => new KeyValuePair<string, int>("InitialPropertyPlantAndEquipment", Id);
        public static KeyValuePair<string, int> InitialResultsOfPreviousYears => new KeyValuePair<string, int>("InitialResultsOfPreviousYears", Id);
        public static KeyValuePair<string, int> InitialShareCapital => new KeyValuePair<string, int>("InitialShareCapital", Id);
        public static KeyValuePair<string, int> InitialShortTermFinancialObligations => new KeyValuePair<string, int>("InitialShortTermFinancialObligations", Id);
        public static KeyValuePair<string, int> InitialSuppliers => new KeyValuePair<string, int>("InitialSuppliers", Id);
        public static KeyValuePair<string, int> InitialTotalAssets => new KeyValuePair<string, int>("InitialTotalAssets", Id);
        public static KeyValuePair<string, int> InitialTotalEquity => new KeyValuePair<string, int>("InitialTotalEquity", Id);
        public static KeyValuePair<string, int> NonCurrentActiveEnd => new KeyValuePair<string, int>("NonCurrentActiveEnd", Id);

    }
}
