/******************************************
 * Code generated by GEB (Version: 2.2.0.0)
 * Template: Sistran.Core.Application.Claims.ClaimCoverageCoinsurance.dict v1.0
 * FileSize=11331 Header=262 CRC=4166898661
 ******************************************/
using System;
using System.Collections;
using System.Collections.Generic;
using Sistran.Core.Framework;
using Sistran.Core.Framework.DAF;

namespace Sistran.Core.Application.Claims.Entities
{
    /// <summary>
    /// Definición de entidad ClaimCoverageCoinsurance.
    /// </summary>
    [
    PersistentClass("Sistran.Core.Application.Claims.ClaimCoverageCoinsurance.dict"),
    Serializable(),
    DescriptionKey("CLAIM_COVERAGE_COINSURANCE_ENTITY"),
    TableMap(TableName="CLAIM_COVERAGE_COINSURANCE", Schema="CLM"),
    ]
    public partial class ClaimCoverageCoinsurance :
        BusinessObject2
    {
#region static
		/// <summary>
		/// Propiedades públicas de la entidad.
		/// </summary>
		public static class Properties
		{
			public static readonly string ClaimCoverageCode = "ClaimCoverageCode";
			public static readonly string CompanyCode = "CompanyCode";
			public static readonly string EstimationTypeCode = "EstimationTypeCode";
            public static readonly string CoverageCode = "CoverageCode";
            public static readonly string EstimationTypeStatusCode = "EstimationTypeStatusCode";
			public static readonly string EstimationTypeStatusReasonCode = "EstimationTypeStatusReasonCode";
			public static readonly string EstimationAmount = "EstimationAmount";
			public static readonly string DeductibleAmount = "DeductibleAmount";
			public static readonly string VersionCode = "VersionCode";
			public static readonly string Date = "Date";
			public static readonly string CurrencyCode = "CurrencyCode";
			public static readonly string EstimateAmountAccumulate = "EstimateAmountAccumulate";
            public static readonly string PartCiaPct = "PartCiaPct";
        }

		/// <summary>
		/// Crea una clave primaria para una clase concreta.
		/// </summary>
		/// <param name="concreteClass">Clase concreta.</param>
		/// <param name="claimCoverageCode">Propiedad clave ClaimCoverageCode.</param>
		/// <param name="companyCode">Propiedad clave CompanyCode.</param>
		/// <param name="estimationTypeCode">Propiedad clave EstimationTypeCode.</param>
		/// <returns>Clave primaria.</returns>
	    protected static PrimaryKey InternalCreatePrimaryKey<T>(int claimCoverageCode, int companyCode, int estimationTypeCode)
	    {
		    Dictionary<string, object> keys = new Dictionary<string, object>();
		    keys.Add(Properties.ClaimCoverageCode, claimCoverageCode);
		    keys.Add(Properties.CompanyCode, companyCode);
		    keys.Add(Properties.EstimationTypeCode, estimationTypeCode);

		    return new PrimaryKey<T>(keys);
	    }

		/// <summary>
		/// Crea una clave primaria para esta clase.
		/// </summary>
		/// <param name="claimCoverageCode">Propiedad clave ClaimCoverageCode.</param>
		/// <param name="companyCode">Propiedad clave CompanyCode.</param>
		/// <param name="estimationTypeCode">Propiedad clave EstimationTypeCode.</param>
		public static PrimaryKey CreatePrimaryKey(int claimCoverageCode, int companyCode, int estimationTypeCode)
	    {
			return InternalCreatePrimaryKey<ClaimCoverageCoinsurance>(claimCoverageCode, companyCode, estimationTypeCode);
		}
        #endregion

        //*** Object Attributes ********************************
        /// <summary>
        /// Atributo para la propiedad CoverageCode.
        /// </summary>
        private int? _coverageCode = null;
        /// <summary>
        /// Atributo para la propiedad EstimationTypeStatusCode.
        /// </summary>
        private int? _estimationTypeStatusCode = null;
		/// <summary>
		/// Atributo para la propiedad EstimationTypeStatusReasonCode.
		/// </summary>
        private int? _estimationTypeStatusReasonCode = null;
		/// <summary>
		/// Atributo para la propiedad EstimationAmount.
		/// </summary>
        private decimal _estimationAmount;
		/// <summary>
		/// Atributo para la propiedad DeductibleAmount.
		/// </summary>
        private decimal _deductibleAmount;
		/// <summary>
		/// Atributo para la propiedad VersionCode.
		/// </summary>
        private int? _versionCode = null;
		/// <summary>
		/// Atributo para la propiedad Date.
		/// </summary>
        private DateTime _date;
		/// <summary>
		/// Atributo para la propiedad CurrencyCode.
		/// </summary>
        private int? _currencyCode = null;
		/// <summary>
		/// Atributo para la propiedad EstimateAmountAccumulate.
		/// </summary>
        private decimal _estimateAmountAccumulate;
        /// <summary>
		/// Atributo para la propiedad PartCiaPct.
		/// </summary>
        private decimal _partCiaPct;
        //*** Object Constructors ********************************

        /// <summary>
        /// Constructor de instancia de la clase en base a las propiedades claves.
        /// </summary>
        /// <param name="claimCoverageCode">ClaimCoverageCode key property.</param>
        /// <param name="companyCode">CompanyCode key property.</param>
        /// <param name="estimationTypeCode">EstimationTypeCode key property.</param>
        public ClaimCoverageCoinsurance(int claimCoverageCode, int companyCode, int estimationTypeCode):
			this(ClaimCoverageCoinsurance.CreatePrimaryKey(claimCoverageCode, companyCode, estimationTypeCode), null)
	    {
	    }

		/// <summary>
		/// Constructor de instancia de la clase en base a una clave primaria y a valores iniciales.
		/// </summary>
		/// <param name="key">
		/// Identificador de la instancia de la entidad.
		/// </param>
		/// <param name="initialValues">
		/// Valores para establecer el estado de la instancia.
		/// </param>
	    public ClaimCoverageCoinsurance(PrimaryKey key, IDictionary initialValues):
			base(key, initialValues)
	    {
	    }

	    /*** Object Properties ********************************/
		/// <summary>
		/// Devuelve o setea el valor de la propiedad ClaimCoverageCode.
		/// </summary>
		/// <value>Propiedad ClaimCoverageCode.</value>
	    [
		DescriptionKey("CLAIM_COVERAGE_CODE_PROPERTY"),
		PersistentProperty(IsKey = true),
        ColumnMap(ColumnName="CLAIM_COVERAGE_CD", DbType=System.Data.DbType.String),
	    ]
        public int ClaimCoverageCode
	    {
		    get
		    {
				return (int)this._primaryKey[Properties.ClaimCoverageCode];
		    }
		    set
		    {
				this._primaryKey[Properties.ClaimCoverageCode] = value;
			}
	    }

		/// <summary>
		/// Devuelve o setea el valor de la propiedad CompanyCode.
		/// </summary>
		/// <value>Propiedad CompanyCode.</value>
	    [
		DescriptionKey("COMPANY_CODE_PROPERTY"),
		PersistentProperty(IsKey = true),
        ColumnMap(ColumnName="COMPANY_CD", DbType=System.Data.DbType.String),
	    ]
        public int CompanyCode
	    {
		    get
		    {
				return (int)this._primaryKey[Properties.CompanyCode];
		    }
		    set
		    {
				this._primaryKey[Properties.CompanyCode] = value;
			}
	    }

		/// <summary>
		/// Devuelve o setea el valor de la propiedad EstimationTypeCode.
		/// </summary>
		/// <value>Propiedad EstimationTypeCode.</value>
	    [
		DescriptionKey("ESTIMATION_TYPE_CODE_PROPERTY"),
		PersistentProperty(IsKey = true),
        ColumnMap(ColumnName="ESTIMATION_TYPE_CD", DbType=System.Data.DbType.String),
	    ]
        public int EstimationTypeCode
	    {
		    get
		    {
				return (int)this._primaryKey[Properties.EstimationTypeCode];
		    }
		    set
		    {
				this._primaryKey[Properties.EstimationTypeCode] = value;
			}
	    }

        /// <summary>
		/// Devuelve o setea el valor de la propiedad CoverageCode.
		/// </summary>
		/// <value>Propiedad CoverageCode.</value>
	    [
        DescriptionKey("COVERAGE_CODE_PROPERTY"),
        PersistentProperty(IsNullable = true),
        ColumnMap(ColumnName = "COVERAGE_CD", DbType = System.Data.DbType.String),
        ]
        public int? CoverageCode
        {
            get
            {
                return this._coverageCode;
            }
            set
            {
                this._coverageCode = value;
            }
        }

        /// <summary>
        /// Devuelve o setea el valor de la propiedad EstimationTypeStatusCode.
        /// </summary>
        /// <value>Propiedad EstimationTypeStatusCode.</value>
        [
		DescriptionKey("ESTIMATION_TYPE_STATUS_CODE_PROPERTY"),
		PersistentProperty(IsNullable = true),
        ColumnMap(ColumnName="ESTIMATION_TYPE_STATUS_CD", DbType=System.Data.DbType.String),
	    ]
        public int? EstimationTypeStatusCode
	    {
		    get
		    {
			    return this._estimationTypeStatusCode;
		    }
		    set
		    {
				this._estimationTypeStatusCode = value;
			}
	    }

		/// <summary>
		/// Devuelve o setea el valor de la propiedad EstimationTypeStatusReasonCode.
		/// </summary>
		/// <value>Propiedad EstimationTypeStatusReasonCode.</value>
	    [
		DescriptionKey("ESTIMATION_TYPE_STATUS_REASON_CODE_PROPERTY"),
		PersistentProperty(IsNullable = true),
        ColumnMap(ColumnName="ESTIMATION_TYPE_STATUS_REASON_CD", DbType=System.Data.DbType.String),
	    ]
        public int? EstimationTypeStatusReasonCode
	    {
		    get
		    {
			    return this._estimationTypeStatusReasonCode;
		    }
		    set
		    {
				this._estimationTypeStatusReasonCode = value;
			}
	    }

		/// <summary>
		/// Devuelve o setea el valor de la propiedad EstimationAmount.
		/// </summary>
		/// <value>Propiedad EstimationAmount.</value>
	    [
		DescriptionKey("ESTIMATION_AMOUNT_PROPERTY"),
		PersistentProperty(),
        ColumnMap(ColumnName="ESTIMATION_AMOUNT", DbType=System.Data.DbType.Decimal),
	    ]
        public decimal EstimationAmount
	    {
		    get
		    {
			    return this._estimationAmount;
		    }
		    set
		    {
				this._estimationAmount = value;
			}
	    }

		/// <summary>
		/// Devuelve o setea el valor de la propiedad DeductibleAmount.
		/// </summary>
		/// <value>Propiedad DeductibleAmount.</value>
	    [
		DescriptionKey("DEDUCTIBLE_AMOUNT_PROPERTY"),
		PersistentProperty(),
        ColumnMap(ColumnName="DEDUCTIBLE_AMOUNT", DbType=System.Data.DbType.Decimal),
	    ]
        public decimal DeductibleAmount
	    {
		    get
		    {
			    return this._deductibleAmount;
		    }
		    set
		    {
				this._deductibleAmount = value;
			}
	    }

		/// <summary>
		/// Devuelve o setea el valor de la propiedad VersionCode.
		/// </summary>
		/// <value>Propiedad VersionCode.</value>
	    [
		DescriptionKey("VERSION_CODE_PROPERTY"),
		PersistentProperty(IsNullable = true),
        ColumnMap(ColumnName="VERSION_CD", DbType=System.Data.DbType.String),
	    ]
        public int? VersionCode
	    {
		    get
		    {
			    return this._versionCode;
		    }
		    set
		    {
				this._versionCode = value;
			}
	    }

		/// <summary>
		/// Devuelve o setea el valor de la propiedad Date.
		/// </summary>
		/// <value>Propiedad Date.</value>
	    [
		DescriptionKey("DATE_PROPERTY"),
		PersistentProperty(),
        ColumnMap(ColumnName="DATE", DbType=System.Data.DbType.String),
	    ]
        public DateTime Date
	    {
		    get
		    {
			    return this._date;
		    }
		    set
		    {
				this._date = value;
			}
	    }

		/// <summary>
		/// Devuelve o setea el valor de la propiedad CurrencyCode.
		/// </summary>
		/// <value>Propiedad CurrencyCode.</value>
	    [
		DescriptionKey("CURRENCY_CODE_PROPERTY"),
		PersistentProperty(IsNullable = true),
        ColumnMap(ColumnName="CURRENCY_CD", DbType=System.Data.DbType.String),
	    ]
        public int? CurrencyCode
	    {
		    get
		    {
			    return this._currencyCode;
		    }
		    set
		    {
				this._currencyCode = value;
			}
	    }

		/// <summary>
		/// Devuelve o setea el valor de la propiedad EstimateAmountAccumulate.
		/// </summary>
		/// <value>Propiedad EstimateAmountAccumulate.</value>
	    [
		DescriptionKey("ESTIMATE_AMOUNT_ACCUMULATE_PROPERTY"),
		PersistentProperty(),
        ColumnMap(ColumnName="ESTIMATE_AMOUNT_ACCUMULATE", DbType=System.Data.DbType.Decimal),
	    ]
        public decimal EstimateAmountAccumulate
	    {
		    get
		    {
			    return this._estimateAmountAccumulate;
		    }
		    set
		    {
				this._estimateAmountAccumulate = value;
			}
	    }

        /// <summary>
		/// Devuelve o setea el valor de la propiedad PartCiaPct.
		/// </summary>
		/// <value>Propiedad PartCiaPct.</value>
	    [
        DescriptionKey("PART_CIA_PCT_PROPERTY"),
        PersistentProperty(),
        ColumnMap(ColumnName = "PART_CIA_PCT", DbType = System.Data.DbType.Decimal),
        ]
        public decimal PartCiaPct
        {
            get
            {
                return this._partCiaPct;
            }
            set
            {
                this._partCiaPct = value;
            }
        }

    }
}