/******************************************
 * Code generated by GEB (Version: 2.2.0.0)
 * Template: Sistran.Core.Application.Tax.TaxableBaseAttribute.dict v1.0
 * FileSize=5186 Header=253 CRC=562731640
 ******************************************/
using Sistran.Core.Framework;
using Sistran.Core.Framework.DAF;
using System;
using System.Collections;
using System.Collections.Generic;

namespace Sistran.Core.Application.Tax.Entities
{
    /// <summary>
    /// Definición de entidad TaxableBaseAttribute.
    /// </summary>
    [
    PersistentClass("Sistran.Core.Application.Tax.TaxableBaseAttribute.dict"),
    Serializable(),
    DescriptionKey("TAXABLE_BASE_ATTRIBUTE_ENTITY"),
    TableMap(TableName = "TAXABLE_BASE_ATTRIBUTE", Schema = "TAX"),
    ]
    public partial class TaxableBaseAttribute :
        BusinessObject2
    {
        #region static
        /// <summary>
        /// Propiedades públicas de la entidad.
        /// </summary>
        public static class Properties
        {
            public static readonly string TaxAttributeTypeCode = "TaxAttributeTypeCode";
            public static readonly string TaxCode = "TaxCode";
            public static readonly string CurrentFrom = "CurrentFrom";
        }

        /// <summary>
        /// Crea una clave primaria para una clase concreta.
        /// </summary>
        /// <param name="concreteClass">Clase concreta.</param>
        /// <param name="taxAttributeTypeCode">Propiedad clave TaxAttributeTypeCode.</param>
        /// <param name="taxCode">Propiedad clave TaxCode.</param>
        /// <param name="currentFrom">Propiedad clave CurrentFrom.</param>
        /// <returns>Clave primaria.</returns>
        protected static PrimaryKey InternalCreatePrimaryKey<T>(int taxAttributeTypeCode, int taxCode, DateTime currentFrom)
        {
            Dictionary<string, object> keys = new Dictionary<string, object>();
            keys.Add(Properties.TaxAttributeTypeCode, taxAttributeTypeCode);
            keys.Add(Properties.TaxCode, taxCode);
            keys.Add(Properties.CurrentFrom, currentFrom);

            return new PrimaryKey<T>(keys);
        }

        /// <summary>
        /// Crea una clave primaria para esta clase.
        /// </summary>
        /// <param name="taxAttributeTypeCode">Propiedad clave TaxAttributeTypeCode.</param>
        /// <param name="taxCode">Propiedad clave TaxCode.</param>
        /// <param name="currentFrom">Propiedad clave CurrentFrom.</param>
        public static PrimaryKey CreatePrimaryKey(int taxAttributeTypeCode, int taxCode, DateTime currentFrom)
        {
            return InternalCreatePrimaryKey<TaxableBaseAttribute>(taxAttributeTypeCode, taxCode, currentFrom);
        }
        #endregion

        //*** Object Attributes ********************************

        //*** Object Constructors ********************************

        /// <summary>
        /// Constructor de instancia de la clase en base a las propiedades claves.
        /// </summary>
        /// <param name="taxAttributeTypeCode">TaxAttributeTypeCode key property.</param>
        /// <param name="taxCode">TaxCode key property.</param>
        /// <param name="currentFrom">CurrentFrom key property.</param>
        public TaxableBaseAttribute(int taxAttributeTypeCode, int taxCode, DateTime currentFrom) :
            this(TaxableBaseAttribute.CreatePrimaryKey(taxAttributeTypeCode, taxCode, currentFrom), null)
        {
        }

        /// <summary>
        /// Constructor de instancia de la clase en base a una clave primaria y a valores iniciales.
        /// </summary>
        /// <param name="key">
        /// Identificador de la instancia de la entidad.
        /// </param>
        /// <param name="initialValues">
        /// Valores para establecer el estado de la instancia.
        /// </param>
        public TaxableBaseAttribute(PrimaryKey key, IDictionary initialValues) :
            base(key, initialValues)
        {
        }

        /*** Object Properties ********************************/
        /// <summary>
        /// Devuelve o setea el valor de la propiedad TaxAttributeTypeCode.
        /// </summary>
        /// <value>Propiedad TaxAttributeTypeCode.</value>
        [
        DescriptionKey("TAX_ATTRIBUTE_TYPE_CODE_PROPERTY"),
        PersistentProperty(IsKey = true),
        ColumnMap(ColumnName = "TAX_ATTRIBUTE_TYPE_CD", DbType = System.Data.DbType.String),
        ]
        public int TaxAttributeTypeCode
        {
            get
            {
                return (int)this._primaryKey[Properties.TaxAttributeTypeCode];
            }
            set
            {
                this._primaryKey[Properties.TaxAttributeTypeCode] = value;
            }
        }

        /// <summary>
        /// Devuelve o setea el valor de la propiedad TaxCode.
        /// </summary>
        /// <value>Propiedad TaxCode.</value>
        [
        DescriptionKey("TAX_CODE_PROPERTY"),
        PersistentProperty(IsKey = true),
        ColumnMap(ColumnName = "TAX_CD", DbType = System.Data.DbType.String),
        ]
        public int TaxCode
        {
            get
            {
                return (int)this._primaryKey[Properties.TaxCode];
            }
            set
            {
                this._primaryKey[Properties.TaxCode] = value;
            }
        }

        /// <summary>
        /// Devuelve o setea el valor de la propiedad CurrentFrom.
        /// </summary>
        /// <value>Propiedad CurrentFrom.</value>
        [
        DescriptionKey("CURRENT_FROM_PROPERTY"),
        PersistentProperty(IsKey = true),
        ColumnMap(ColumnName = "CURRENT_FROM", DbType = System.Data.DbType.String),
        ]
        public DateTime CurrentFrom
        {
            get
            {
                return (DateTime)this._primaryKey[Properties.CurrentFrom];
            }
            set
            {
                this._primaryKey[Properties.CurrentFrom] = value;
            }
        }

    }
}