/******************************************
 * Code generated by GEB (Version: 2.2.0.0)
 * Template: Sistran.Core.Application.Script.Rule.dict v1.0
 * FileSize=4465 Header=241 CRC=3998738377
 ******************************************/
using Sistran.Core.Framework;
using Sistran.Core.Framework.DAF;
using System;
using System.Collections;
using System.Collections.Generic;

namespace Sistran.Core.Application.Script.Entities
{
    /// <summary>
    /// Definición de entidad Rule.
    /// </summary>
    [
    PersistentClass("Sistran.Core.Application.Script.Rule.dict"),
    Serializable(),
    DescriptionKey("RULE_ENTITY"),
    TableMap(TableName = "RULE", Schema = "SCR"),
    ]
    public partial class Rule :
        BusinessObject2
    {
        #region static
        /// <summary>
        /// Propiedades públicas de la entidad.
        /// </summary>
        public static class Properties
        {
            public static readonly string RuleBaseId = "RuleBaseId";
            public static readonly string RuleId = "RuleId";
            public static readonly string OrderNum = "OrderNum";
        }

        /// <summary>
        /// Crea una clave primaria para una clase concreta.
        /// </summary>
        /// <param name="concreteClass">Clase concreta.</param>
        /// <param name="ruleBaseId">Propiedad clave RuleBaseId.</param>
        /// <param name="ruleId">Propiedad clave RuleId.</param>
        /// <returns>Clave primaria.</returns>
        protected static PrimaryKey InternalCreatePrimaryKey<T>(int ruleBaseId, int ruleId)
        {
            Dictionary<string, object> keys = new Dictionary<string, object>();
            keys.Add(Properties.RuleBaseId, ruleBaseId);
            keys.Add(Properties.RuleId, ruleId);

            return new PrimaryKey<T>(keys);
        }

        /// <summary>
        /// Crea una clave primaria para esta clase.
        /// </summary>
        /// <param name="ruleBaseId">Propiedad clave RuleBaseId.</param>
        /// <param name="ruleId">Propiedad clave RuleId.</param>
        public static PrimaryKey CreatePrimaryKey(int ruleBaseId, int ruleId)
        {
            return InternalCreatePrimaryKey<Rule>(ruleBaseId, ruleId);
        }
        #endregion

        //*** Object Attributes ********************************

        /// <summary>
        /// Atributo para la propiedad OrderNum.
        /// </summary>
        private int _orderNum;
        //*** Object Constructors ********************************

        /// <summary>
        /// Constructor de instancia de la clase en base a las propiedades claves.
        /// </summary>
        /// <param name="ruleBaseId">RuleBaseId key property.</param>
        /// <param name="ruleId">RuleId key property.</param>
        public Rule(int ruleBaseId, int ruleId) :
            this(Rule.CreatePrimaryKey(ruleBaseId, ruleId), null)
        {
        }

        /// <summary>
        /// Constructor de instancia de la clase en base a una clave primaria y a valores iniciales.
        /// </summary>
        /// <param name="key">
        /// Identificador de la instancia de la entidad.
        /// </param>
        /// <param name="initialValues">
        /// Valores para establecer el estado de la instancia.
        /// </param>
        public Rule(PrimaryKey key, IDictionary initialValues) :
            base(key, initialValues)
        {
        }

        /*** Object Properties ********************************/
        /// <summary>
        /// Devuelve o setea el valor de la propiedad RuleBaseId.
        /// </summary>
        /// <value>Propiedad RuleBaseId.</value>
        [
        DescriptionKey("RULE_BASE_ID_PROPERTY"),
        PersistentProperty(IsKey = true),
        ColumnMap(ColumnName = "RULE_BASE_ID", DbType = System.Data.DbType.String),
        ]
        public int RuleBaseId
        {
            get
            {
                return (int)this._primaryKey[Properties.RuleBaseId];
            }
            set
            {
                this._primaryKey[Properties.RuleBaseId] = value;
            }
        }

        /// <summary>
        /// Devuelve o setea el valor de la propiedad RuleId.
        /// </summary>
        /// <value>Propiedad RuleId.</value>
        [
        DescriptionKey("RULE_ID_PROPERTY"),
        PersistentProperty(IsKey = true),
        ColumnMap(ColumnName = "RULE_ID", DbType = System.Data.DbType.String),
        ]
        public int RuleId
        {
            get
            {
                return (int)this._primaryKey[Properties.RuleId];
            }
            set
            {
                this._primaryKey[Properties.RuleId] = value;
            }
        }

        /// <summary>
        /// Devuelve o setea el valor de la propiedad OrderNum.
        /// </summary>
        /// <value>Propiedad OrderNum.</value>
        [
        DescriptionKey("ORDER_NUM_PROPERTY"),
        PersistentProperty(),
        ColumnMap(ColumnName = "ORDER_NUM", DbType = System.Data.DbType.String),
        ]
        public int OrderNum
        {
            get
            {
                return this._orderNum;
            }
            set
            {
                this._orderNum = value;
            }
        }

    }
}