Resources.Person =
    {
        ErrorAddress: "Dirección",
        ErrorAddressDuplicate: "Dirección repetida",
        ErrorAddressEmpty: "No existen datos para Grabar",
        ErrorAddressMain: "Solo debe existir una direccion principal",
        ErrorCompany: "Error Creando Compañia",
        ErrorConsortiumMain: "Ya existe Un Consorcio Principal",
        ErrorCreateProvider: "Error al crear Proveedor",
        ErrorCreateTax: "Error al crear Impuestos",
        ErrorDaneCode: "El codigo DANE ingresado no existe",
        ErrorDaneCodeEmpty: "El codigo DANE no existe",
        ErrorDeleteOperationQuota: "No se puede eliminar el cupo operativo.",
        ErrorEconomyActivity: "Actividad Económica no encontrada",
        ErrorEmail: "Debe ingresar un Email valido",
        ErrorEmailExists: "Correo ya Existe",
        ErrorEmailMain: "Solo debe existir un Correo principal",
        ErrorEmpty: "No existen datos para Grabar",
        ErrorFieldIncomplete: "Campos incompletos",
        ErrorGuaranteesTypes: "Error al consultar tipo de contragarantias",
        ErrorHolder: "Error al consultar tomadores",
        ErrorIndividual: "Error Consultando el Individuo",
        ErrorInsuredCreate: "Error Creando El Asegurado de forma automatica",
        ErrorMethodPayment: "No se permite editar el medio de pago efectivo",
        ErrorNoExistModuleGuaranteesTypes: "No hay modulo para este tipo de contragarantía",
        ErrorNumberPhone: "Número de teléfono ya existe",
        ErrorPercentage: "La suma de los porcentajes debe ser igual o menor a 100.",
        ErrorPercentageEmpty: "Debe ingresar Porcentaje de participacion.",
        ErrorPercentageHigher: "El valor del porcentaje debe ser mayor que cero y menor o igual a 100.",
        ErrorPercentageTotal: "La suma de los porcentajes debe ser 100.",
        ErrorPersonEmpty: "Debe Existir la Persona",
        ErrorPhoneMain: "Solo debe existir un teléfono principal",
        ErrorQueryingCities: "Error consultando ciudades",
        ErrorQueryingCountries: "Error consultando países",
        ErrorQueryingStates: "Error consultando departamentos",
        ErrorRolInsured: "Persona sin Rol de Asegurado",
        ErrorSave: "Error Guardar",
        ErrorSaveOperationQuota: "Ocurrió un error guardando el Cupo Operativo",
        ErrorSavePerson: "Error Guardar La persona",
        ErrorSaveProspectus: "Error al grabar el prospecto",
        ErrorSearchCountry: "Error al consultar paises",
        ErrorSearchDefaultData: "Error al consultar datos por defecto",
        ErrorTaxExists: "Ya existe esta asociacion de impuesto",
        LabelAccountNumber: "Número de cuenta",
        LabelAccountType: "Tipo de cuenta",
        LabelActive: "Activo",
        LabelAddress: "Dirección",
        LabelAddressAll: "Dirección completa",
        LabelAddressMain: "Dirección principal",
        LabelAgentDisabled: "El Agente esta deshabilitado",
        LabelBirthdate: "Fecha de nacimiento",
        LabelBranch: "Sucursal",
        LabelBusinessName: "Razón Social",
        Labelcash: "EFECTIVO",
        LabelCity: "Ciudad",
        LabelCurrency: "Moneda",
        LabelCurrentTo: "Fecha hasta",
        LabelDeclinedDate: "Fecha de Baja",
        LabelDepartment: "Departamento",
        LabelDocument: "Documento",
        LabelEconomyActivity: "Actividad económica",
        LabelEmail: "Email",
        LabelEmailType: "Tipo Email",
        LabelFirstName: "Primer apellido",
        labelGender: "Género",
        LabelInactive: "Inactivo",
        LabelInformative: "La siguiente información es obligatoria",
        LabelInsuredCreate: "Desea crearla como Asegurado?",
        LabelKey: "Clave",
        LabelMaritalStatus: "Estado civil",
        LabelMethodPayment: "Forma de pago",
        LabelName: "Nombre",
        LabelNameAgency: "Nombre de la Agencia",
        LabelNumberDocument: "Número de documento",
        LabelOperatingQuota: "Cupo Operativo",
        LabelPaymentMethodAlreadyExists: "Medio de pago  ya existe",
        LabelPerson: "Datos Personas",
        LabelPersonCode: "Persona con código Nro.",
        LabelPersonCreate: "creada satisfactoriamente.",
        LabelPersonNew: "Nueva Persona",
        LabelPersonUpdate: "actualizada satisfactoriamente",
        LabelPhone: "Teléfono",
        LabelPhoneNumber: "Número de teléfono",
        LabelPhoneType: "Tipo de teléfono",
        LabelPrefix: "Ramo",
        LabelReasonLow: "Motivo de Baja",
        LabelSarlaft: "Sarlaft",
        labelSelectConsortium: "Seleccione Consorciado",
        LabelTypeAddress: "Tipo de dirección",
        LabelTypeDocument: "Tipo de documento",
        LabelTypeIntermediary: "Tipo Intermediario",
        LabelTypeIntermediary: "Tipo Intermediario",
        LabelTypeIntermediary: "Tipo Intermediario",
    
    LabelSBSCode: "Código SBS",
    LabelDistrict: "Distrito",


        MesageCreate: "creado satisfactoriamente",
        MessageAddress: "Dirección",
        MessageAddressEmpty: "Debe Ingresar la direccion",
        MessageAgencyExist: "Nombre de Agencia ya existe",
        MessageAgents: "Intermediarios",
        MessageBranchExist: "Sucursal de la Agencia ya existe",
        MessageBusinessNameEmpty: "Debe Ingresar razon social",
        MessageCompany: "Compañía con código Nro. ",
        MessageConsortiumDuplicate: "Consorcio ya Existe",
        MessageConsortiumMain: "Debe Existir Solo Un consorcio Principal",
        MessageConsortiumMembers: "Este tipo de asociación no requiere información de consorciados",
        MessageConsortiumMembersEmpty: "No a Ingresado el Consorcio",
        MessageConsortiumMembersMandatory: "Es obligatorio incluir los participantes del consorcio",
        MessageConsortiumNoExists: "No existe el consorcio en el sistema",
        MessageConsortiums: "Consorciados",
        MessageDaneCode: "El codigo DANE ingresado no existe",
        MessageDeleteOperationQuota: "Se ha eliminado el cupo",
        MessageEmailEmpty: " Debe Ingresar el email",
        MessageFieldsAreMandatory: "Los siguientes campos son obligatorios",
        MessageHolder: "Seleccione el Tomador",
        MessageIndividual: "Debe Existir el individuo",
        MessageInfoMinimumChar: "Debe digitar mínimo 3 caracteres",
        MessageInsured: "Asegurado",
        MessageKeyExist: "Clave de Agencia ya existe",
        MessageMehodPayment: "Medios de pago",
        MessageNotFoundCities: "No se encontraron ciudades para mostrar",
        MessageNotFoundCountries: "No se encontraron países para mostrar",
        MessageNotFoundStates: "No se encontraron departamentos para mostrar",
        MessagePartner: "Accionista ya existe",
        MessagePaymentConceptExisting: "Este concepto de pago, ya se encuentra asignado",
        MessagePaymentMethod: "No se permite editar el medio de pago efectivo",
        MessagePersonEmpty: "La persona no existe en el sistema",
        MessagePhoneEmpty: " Debe Ingresar telefono",
        MessageSarlaft: "Empresa sin exoneración. El ingreso de Sarlaft es Obligatorio",
        MessageUpdate: "actualizado satisfactoriamente",
        MessageCantSetInitialCountry: "No se pudo cargar pais inicial",
        Provider: "Proveedor",
        Required: "es requerido",
        ShowSaveData: "Los datos han sido guardado correctamente",
        Tax: "Impuestos",
        TitleInsured: "Rol Asegurado",
        TitlePartner: "Accionistas / Asociados",
        ModalTitleCountries: "Lista de Paises",
        ModalTitleStates: "Lista de Departamentos",
        ModalTitleCities: "Lista de Ciudades"
    }
