/******************************************
 * Code generated by GEB (Version: 2.2.0.0)
 * Template: Sistran.Core.Application.AccountingServices.PaymentOrderAgentItem.dict v1.0
 * FileSize=5054 Header=266 CRC=3232643782
 ******************************************/
using System;
using System.Collections;
using System.Collections.Generic;
using Sistran.Core.Framework;
using Sistran.Core.Framework.DAF;

namespace Sistran.Core.Application.Accounting.Entities
{
    /// <summary>
    /// Definición de entidad PaymentOrderAgentItem.
    /// </summary>
    [
    PersistentClass("Sistran.Core.Application.Accounting.PaymentOrderAgentItem.dict"),
    Serializable(),
    DescriptionKey("PAYMENT_ORDER_AGENT_ITEM_ENTITY"),
    TableMap(TableName = "PAYMENT_ORDER_AGENT_ITEM", Schema = "ACC"),
    ]
    public partial class PaymentOrderAgentItem :
        BusinessObject2
    {
#region static
		/// <summary>
		/// Propiedades públicas de la entidad.
		/// </summary>
		public static class Properties
		{
			public static readonly string PaymentOrderAgentItemCode = "PaymentOrderAgentItemCode";
			public static readonly string PaymentOrderAgentCode = "PaymentOrderAgentCode";
			public static readonly string PaymentOrderCode = "PaymentOrderCode";
		}

		/// <summary>
		/// Crea una clave primaria para una clase concreta.
		/// </summary>
		/// <param name="concreteClass">Clase concreta.</param>
		/// <param name="paymentOrderAgentItemCode">Propiedad clave PaymentOrderAgentItemCode.</param>
		/// <returns>Clave primaria.</returns>
	    protected static PrimaryKey InternalCreatePrimaryKey<T>(int paymentOrderAgentItemCode)
	    {
		    Dictionary<string, object> keys = new Dictionary<string, object>();
		    keys.Add(Properties.PaymentOrderAgentItemCode, paymentOrderAgentItemCode);

		    return new PrimaryKey<T>(keys);
	    }

		/// <summary>
		/// Crea una clave primaria para esta clase.
		/// </summary>
		/// <param name="paymentOrderAgentItemCode">Propiedad clave PaymentOrderAgentItemCode.</param>
		public static PrimaryKey CreatePrimaryKey(int paymentOrderAgentItemCode)
	    {
			return InternalCreatePrimaryKey<PaymentOrderAgentItem>(paymentOrderAgentItemCode);
		}
#endregion

	    //*** Object Attributes ********************************

		/// <summary>
		/// Atributo para la propiedad PaymentOrderAgentCode.
		/// </summary>
        private int? _paymentOrderAgentCode = null;
		/// <summary>
		/// Atributo para la propiedad PaymentOrderCode.
		/// </summary>
        private int? _paymentOrderCode = null;
	    //*** Object Constructors ********************************

		/// <summary>
		/// Constructor de instancia de la clase en base a las propiedades claves.
		/// </summary>
		/// <param name="paymentOrderAgentItemCode">PaymentOrderAgentItemCode key property.</param>
	    public PaymentOrderAgentItem(int paymentOrderAgentItemCode):
			this(PaymentOrderAgentItem.CreatePrimaryKey(paymentOrderAgentItemCode), null)
	    {
	    }

		/// <summary>
		/// Constructor de instancia de la clase en base a una clave primaria y a valores iniciales.
		/// </summary>
		/// <param name="key">
		/// Identificador de la instancia de la entidad.
		/// </param>
		/// <param name="initialValues">
		/// Valores para establecer el estado de la instancia.
		/// </param>
	    public PaymentOrderAgentItem(PrimaryKey key, IDictionary initialValues):
			base(key, initialValues)
	    {
	    }

	    /*** Object Properties ********************************/
		/// <summary>
		/// Devuelve o setea el valor de la propiedad PaymentOrderAgentItemCode.
		/// </summary>
		/// <value>Propiedad PaymentOrderAgentItemCode.</value>
	    [
		DescriptionKey("PAYMENT_ORDER_AGENT_ITEM_CODE_PROPERTY"),
		PersistentProperty(IsKey = true),
        ColumnMap(ColumnName="PAYMENT_ORDER_AGENT_ITEM_CD", DbType=System.Data.DbType.String),
	    ]
        public int PaymentOrderAgentItemCode
	    {
		    get
		    {
				return (int)this._primaryKey[Properties.PaymentOrderAgentItemCode];
		    }
		    set
		    {
				this._primaryKey[Properties.PaymentOrderAgentItemCode] = value;
			}
	    }

		/// <summary>
		/// Devuelve o setea el valor de la propiedad PaymentOrderAgentCode.
		/// </summary>
		/// <value>Propiedad PaymentOrderAgentCode.</value>
	    [
		DescriptionKey("PAYMENT_ORDER_AGENT_CODE_PROPERTY"),
		PersistentProperty(IsNullable = true),
        ColumnMap(ColumnName="PAYMENT_ORDER_AGENT_CD", DbType=System.Data.DbType.String),
	    ]
        public int? PaymentOrderAgentCode
	    {
		    get
		    {
			    return this._paymentOrderAgentCode;
		    }
		    set
		    {
				this._paymentOrderAgentCode = value;
			}
	    }

		/// <summary>
		/// Devuelve o setea el valor de la propiedad PaymentOrderCode.
		/// </summary>
		/// <value>Propiedad PaymentOrderCode.</value>
	    [
		DescriptionKey("PAYMENT_ORDER_CODE_PROPERTY"),
		PersistentProperty(IsNullable = true),
        ColumnMap(ColumnName="PAYMENT_ORDER_CD", DbType=System.Data.DbType.String),
	    ]
        public int? PaymentOrderCode
	    {
		    get
		    {
			    return this._paymentOrderCode;
		    }
		    set
		    {
				this._paymentOrderCode = value;
			}
	    }

    }
}