/******************************************
 * Code generated by GEB (Version: 2.2.0.0)
 * Template: Sistran.Core.Application.Accounting.PolicyToCancelV.dict v1.0
 * FileSize=26976 Header=257 CRC=1968322693
 ******************************************/
using System;
using System.Collections;
using System.Collections.Generic;
using Sistran.Core.Framework;
using Sistran.Core.Framework.DAF;

namespace Sistran.Core.Application.Accounting.Entities
{
    /// <summary>
    /// Definición de entidad PolicyToCancelV.
    /// </summary>
    [
    PersistentClass("Sistran.Core.Application.Accounting.PolicyToCancelV.dict"),
    Serializable(),
    DescriptionKey("POLICY_TO_CANCEL_V_ENTITY"),
    TableMap(TableName="POLICY_TO_CANCEL_V", Schema="ACC"),
    ]
    public partial class PolicyToCancelV :
        BusinessObject2
    {
#region static
		/// <summary>
		/// Propiedades públicas de la entidad.
		/// </summary>
		public static class Properties
		{
			public static readonly string BranchCode = "BranchCode";
			public static readonly string BranchName = "BranchName";
			public static readonly string PrefixCode = "PrefixCode";
			public static readonly string PrefixName = "PrefixName";
			public static readonly string PolicyNumber = "PolicyNumber";
			public static readonly string EndorsementNumber = "EndorsementNumber";
			public static readonly string PayExpDate = "PayExpDate";
			public static readonly string DeclaredAmount = "DeclaredAmount";
			public static readonly string PremiumAmount = "PremiumAmount";
			public static readonly string PolicyBalance = "PolicyBalance";
			public static readonly string InsuredId = "InsuredId";
			public static readonly string InsuredName = "InsuredName";
			public static readonly string InsuredDocumentNumber = "InsuredDocumentNumber";
			public static readonly string IssueDate = "IssueDate";
			public static readonly string CurrentFrom = "CurrentFrom";
			public static readonly string CurrentTo = "CurrentTo";
			public static readonly string EndoGroupId = "EndoGroupId";
			public static readonly string EndorsementTypeCode = "EndorsementTypeCode";
			public static readonly string EndorsementTypeName = "EndorsementTypeName";
			public static readonly string PolicyId = "PolicyId";
			public static readonly string AgentTypeCode = "AgentTypeCode";
			public static readonly string AgentId = "AgentId";
			public static readonly string AgentDocumentNumber = "AgentDocumentNumber";
			public static readonly string AgentName = "AgentName";
			public static readonly string CurrencyCode = "CurrencyCode";
			public static readonly string BusinessTypeCode = "BusinessTypeCode";
			public static readonly string UserId = "UserId";
			public static readonly string EndorsementId = "EndorsementId";
			public static readonly string PaymentNum = "PaymentNum";
			public static readonly string PayerId = "PayerId";
			public static readonly string RiskNum = "RiskNum";
			public static readonly string CoverNum = "CoverNum";
			public static readonly string RiskCoverId = "RiskCoverId";
			public static readonly string PrefixTypeCode = "PrefixTypeCode";
			public static readonly string AgentAgencyId = "AgentAgencyId";
			public static readonly string IndividualId = "IndividualId";
		}

		/// <summary>
		/// Crea una clave primaria para una clase concreta.
		/// </summary>
		/// <param name="concreteClass">Clase concreta.</param>
		/// <returns>Clave primaria.</returns>
	    protected static PrimaryKey InternalCreatePrimaryKey<T>()
	    {
		    Dictionary<string, object> keys = new Dictionary<string, object>();

		    return new PrimaryKey<T>(keys);
	    }

		/// <summary>
		/// Crea una clave primaria para esta clase.
		/// </summary>
		public static PrimaryKey CreatePrimaryKey()
	    {
			return InternalCreatePrimaryKey<PolicyToCancelV>();
		}
#endregion

	    //*** Object Attributes ********************************

		/// <summary>
		/// Atributo para la propiedad BranchCode.
		/// </summary>
        private int _branchCode;
		/// <summary>
		/// Atributo para la propiedad BranchName.
		/// </summary>
        private string _branchName = null;
		/// <summary>
		/// Atributo para la propiedad PrefixCode.
		/// </summary>
        private int _prefixCode;
		/// <summary>
		/// Atributo para la propiedad PrefixName.
		/// </summary>
        private string _prefixName = null;
		/// <summary>
		/// Atributo para la propiedad PolicyNumber.
		/// </summary>
        private decimal _policyNumber;
		/// <summary>
		/// Atributo para la propiedad EndorsementNumber.
		/// </summary>
        private int _endorsementNumber;
		/// <summary>
		/// Atributo para la propiedad PayExpDate.
		/// </summary>
        private DateTime _payExpDate;
		/// <summary>
		/// Atributo para la propiedad DeclaredAmount.
		/// </summary>
        private decimal _declaredAmount;
		/// <summary>
		/// Atributo para la propiedad PremiumAmount.
		/// </summary>
        private decimal _premiumAmount;
		/// <summary>
		/// Atributo para la propiedad PolicyBalance.
		/// </summary>
        private decimal? _policyBalance = null;
		/// <summary>
		/// Atributo para la propiedad InsuredId.
		/// </summary>
        private int? _insuredId = null;
		/// <summary>
		/// Atributo para la propiedad InsuredName.
		/// </summary>
        private string _insuredName = null;
		/// <summary>
		/// Atributo para la propiedad InsuredDocumentNumber.
		/// </summary>
        private string _insuredDocumentNumber = null;
		/// <summary>
		/// Atributo para la propiedad IssueDate.
		/// </summary>
        private DateTime? _issueDate = null;
		/// <summary>
		/// Atributo para la propiedad CurrentFrom.
		/// </summary>
        private DateTime _currentFrom;
		/// <summary>
		/// Atributo para la propiedad CurrentTo.
		/// </summary>
        private DateTime? _currentTo = null;
		/// <summary>
		/// Atributo para la propiedad EndoGroupId.
		/// </summary>
        private int _endoGroupId;
		/// <summary>
		/// Atributo para la propiedad EndorsementTypeCode.
		/// </summary>
        private int _endorsementTypeCode;
		/// <summary>
		/// Atributo para la propiedad EndorsementTypeName.
		/// </summary>
        private string _endorsementTypeName = null;
		/// <summary>
		/// Atributo para la propiedad PolicyId.
		/// </summary>
        private int _policyId;
		/// <summary>
		/// Atributo para la propiedad AgentTypeCode.
		/// </summary>
        private int _agentTypeCode;
		/// <summary>
		/// Atributo para la propiedad AgentId.
		/// </summary>
        private int _agentId;
		/// <summary>
		/// Atributo para la propiedad AgentDocumentNumber.
		/// </summary>
        private string _agentDocumentNumber = null;
		/// <summary>
		/// Atributo para la propiedad AgentName.
		/// </summary>
        private string _agentName = null;
		/// <summary>
		/// Atributo para la propiedad CurrencyCode.
		/// </summary>
        private int _currencyCode;
		/// <summary>
		/// Atributo para la propiedad BusinessTypeCode.
		/// </summary>
        private int _businessTypeCode;
		/// <summary>
		/// Atributo para la propiedad UserId.
		/// </summary>
        private int _userId;
		/// <summary>
		/// Atributo para la propiedad EndorsementId.
		/// </summary>
        private int _endorsementId;
		/// <summary>
		/// Atributo para la propiedad PaymentNum.
		/// </summary>
        private int _paymentNum;
		/// <summary>
		/// Atributo para la propiedad PayerId.
		/// </summary>
        private int _payerId;
		/// <summary>
		/// Atributo para la propiedad RiskNum.
		/// </summary>
        private int _riskNum;
		/// <summary>
		/// Atributo para la propiedad CoverNum.
		/// </summary>
        private int _coverNum;
		/// <summary>
		/// Atributo para la propiedad RiskCoverId.
		/// </summary>
        private int _riskCoverId;
		/// <summary>
		/// Atributo para la propiedad PrefixTypeCode.
		/// </summary>
        private int _prefixTypeCode;
		/// <summary>
		/// Atributo para la propiedad AgentAgencyId.
		/// </summary>
        private int _agentAgencyId;
		/// <summary>
		/// Atributo para la propiedad IndividualId.
		/// </summary>
        private int _individualId;
	    //*** Object Constructors ********************************

		/// <summary>
		/// Constructor de instancia de la clase en base a las propiedades claves.
		/// </summary>
	    public PolicyToCancelV():
			this(PolicyToCancelV.CreatePrimaryKey(), null)
	    {
	    }

		/// <summary>
		/// Constructor de instancia de la clase en base a una clave primaria y a valores iniciales.
		/// </summary>
		/// <param name="key">
		/// Identificador de la instancia de la entidad.
		/// </param>
		/// <param name="initialValues">
		/// Valores para establecer el estado de la instancia.
		/// </param>
	    public PolicyToCancelV(PrimaryKey key, IDictionary initialValues):
			base(key, initialValues)
	    {
	    }

	    /*** Object Properties ********************************/
		/// <summary>
		/// Devuelve o setea el valor de la propiedad BranchCode.
		/// </summary>
		/// <value>Propiedad BranchCode.</value>
	    [
		DescriptionKey("BRANCH_CODE_PROPERTY"),
		PersistentProperty(),
        ColumnMap(ColumnName="BRANCH_CD", DbType=System.Data.DbType.String),
	    ]
        public int BranchCode
	    {
		    get
		    {
			    return this._branchCode;
		    }
		    set
		    {
				this._branchCode = value;
			}
	    }

		/// <summary>
		/// Devuelve o setea el valor de la propiedad BranchName.
		/// </summary>
		/// <value>Propiedad BranchName.</value>
	    [
		DescriptionKey("BRANCH_NAME_PROPERTY"),
		PersistentProperty(),
        ColumnMap(ColumnName="BRANCH_NAME", DbType=System.Data.DbType.String),
	    ]
        public string BranchName
	    {
		    get
		    {
			    return this._branchName;
		    }
		    set
		    {
				if(value == null)
				{
					throw new PropertyNotNullableException(this.GetType().FullName, Properties.BranchName);
				}
				this._branchName = value;
			}
	    }

		/// <summary>
		/// Devuelve o setea el valor de la propiedad PrefixCode.
		/// </summary>
		/// <value>Propiedad PrefixCode.</value>
	    [
		DescriptionKey("PREFIX_CODE_PROPERTY"),
		PersistentProperty(),
        ColumnMap(ColumnName="PREFIX_CD", DbType=System.Data.DbType.String),
	    ]
        public int PrefixCode
	    {
		    get
		    {
			    return this._prefixCode;
		    }
		    set
		    {
				this._prefixCode = value;
			}
	    }

		/// <summary>
		/// Devuelve o setea el valor de la propiedad PrefixName.
		/// </summary>
		/// <value>Propiedad PrefixName.</value>
	    [
		DescriptionKey("PREFIX_NAME_PROPERTY"),
		PersistentProperty(),
        ColumnMap(ColumnName="PREFIX_NAME", DbType=System.Data.DbType.String),
	    ]
        public string PrefixName
	    {
		    get
		    {
			    return this._prefixName;
		    }
		    set
		    {
				if(value == null)
				{
					throw new PropertyNotNullableException(this.GetType().FullName, Properties.PrefixName);
				}
				this._prefixName = value;
			}
	    }

		/// <summary>
		/// Devuelve o setea el valor de la propiedad PolicyNumber.
		/// </summary>
		/// <value>Propiedad PolicyNumber.</value>
	    [
		DescriptionKey("POLICY_NUMBER_PROPERTY"),
		PersistentProperty(),
        ColumnMap(ColumnName="POLICY_NUMBER", DbType=System.Data.DbType.Decimal),
	    ]
        public decimal PolicyNumber
	    {
		    get
		    {
			    return this._policyNumber;
		    }
		    set
		    {
				this._policyNumber = value;
			}
	    }

		/// <summary>
		/// Devuelve o setea el valor de la propiedad EndorsementNumber.
		/// </summary>
		/// <value>Propiedad EndorsementNumber.</value>
	    [
		DescriptionKey("ENDORSEMENT_NUMBER_PROPERTY"),
		PersistentProperty(),
        ColumnMap(ColumnName="ENDORSEMENT_NUMBER", DbType=System.Data.DbType.String),
	    ]
        public int EndorsementNumber
	    {
		    get
		    {
			    return this._endorsementNumber;
		    }
		    set
		    {
				this._endorsementNumber = value;
			}
	    }

		/// <summary>
		/// Devuelve o setea el valor de la propiedad PayExpDate.
		/// </summary>
		/// <value>Propiedad PayExpDate.</value>
	    [
		DescriptionKey("PAY_EXP_DATE_PROPERTY"),
		PersistentProperty(),
        ColumnMap(ColumnName="PAY_EXP_DATE", DbType=System.Data.DbType.String),
	    ]
        public DateTime PayExpDate
	    {
		    get
		    {
			    return this._payExpDate;
		    }
		    set
		    {
				this._payExpDate = value;
			}
	    }

		/// <summary>
		/// Devuelve o setea el valor de la propiedad DeclaredAmount.
		/// </summary>
		/// <value>Propiedad DeclaredAmount.</value>
	    [
		DescriptionKey("DECLARED_AMOUNT_PROPERTY"),
		PersistentProperty(),
        ColumnMap(ColumnName="DECLARED_AMT", DbType=System.Data.DbType.Decimal),
	    ]
        public decimal DeclaredAmount
	    {
		    get
		    {
			    return this._declaredAmount;
		    }
		    set
		    {
				this._declaredAmount = value;
			}
	    }

		/// <summary>
		/// Devuelve o setea el valor de la propiedad PremiumAmount.
		/// </summary>
		/// <value>Propiedad PremiumAmount.</value>
	    [
		DescriptionKey("PREMIUM_AMOUNT_PROPERTY"),
		PersistentProperty(),
        ColumnMap(ColumnName="PREMIUM_AMT", DbType=System.Data.DbType.Decimal),
	    ]
        public decimal PremiumAmount
	    {
		    get
		    {
			    return this._premiumAmount;
		    }
		    set
		    {
				this._premiumAmount = value;
			}
	    }

		/// <summary>
		/// Devuelve o setea el valor de la propiedad PolicyBalance.
		/// </summary>
		/// <value>Propiedad PolicyBalance.</value>
	    [
		DescriptionKey("POLICY_BALANCE_PROPERTY"),
		PersistentProperty(IsNullable = true),
        ColumnMap(ColumnName="POLICY_BALANCE", DbType=System.Data.DbType.Decimal),
	    ]
        public decimal? PolicyBalance
	    {
		    get
		    {
			    return this._policyBalance;
		    }
		    set
		    {
				this._policyBalance = value;
			}
	    }

		/// <summary>
		/// Devuelve o setea el valor de la propiedad InsuredId.
		/// </summary>
		/// <value>Propiedad InsuredId.</value>
	    [
		DescriptionKey("INSURED_ID_PROPERTY"),
		PersistentProperty(IsNullable = true),
        ColumnMap(ColumnName="INSURED_ID", DbType=System.Data.DbType.String),
	    ]
        public int? InsuredId
	    {
		    get
		    {
			    return this._insuredId;
		    }
		    set
		    {
				this._insuredId = value;
			}
	    }

		/// <summary>
		/// Devuelve o setea el valor de la propiedad InsuredName.
		/// </summary>
		/// <value>Propiedad InsuredName.</value>
	    [
		DescriptionKey("INSURED_NAME_PROPERTY"),
		PersistentProperty(IsNullable = true),
        ColumnMap(ColumnName="INSURED_NAME", DbType=System.Data.DbType.String),
	    ]
        public string InsuredName
	    {
		    get
		    {
			    return this._insuredName;
		    }
		    set
		    {
				this._insuredName = value;
			}
	    }

		/// <summary>
		/// Devuelve o setea el valor de la propiedad InsuredDocumentNumber.
		/// </summary>
		/// <value>Propiedad InsuredDocumentNumber.</value>
	    [
		DescriptionKey("INSURED_DOCUMENT_NUMBER_PROPERTY"),
		PersistentProperty(IsNullable = true),
        ColumnMap(ColumnName="INSURED_DOCUMENT_NUMBER", DbType=System.Data.DbType.String),
	    ]
        public string InsuredDocumentNumber
	    {
		    get
		    {
			    return this._insuredDocumentNumber;
		    }
		    set
		    {
				this._insuredDocumentNumber = value;
			}
	    }

		/// <summary>
		/// Devuelve o setea el valor de la propiedad IssueDate.
		/// </summary>
		/// <value>Propiedad IssueDate.</value>
	    [
		DescriptionKey("ISSUE_DATE_PROPERTY"),
		PersistentProperty(IsNullable = true),
        ColumnMap(ColumnName="ISSUE_DATE", DbType=System.Data.DbType.String),
	    ]
        public DateTime? IssueDate
	    {
		    get
		    {
			    return this._issueDate;
		    }
		    set
		    {
				this._issueDate = value;
			}
	    }

		/// <summary>
		/// Devuelve o setea el valor de la propiedad CurrentFrom.
		/// </summary>
		/// <value>Propiedad CurrentFrom.</value>
	    [
		DescriptionKey("CURRENT_FROM_PROPERTY"),
		PersistentProperty(),
        ColumnMap(ColumnName="CURRENT_FROM", DbType=System.Data.DbType.String),
	    ]
        public DateTime CurrentFrom
	    {
		    get
		    {
			    return this._currentFrom;
		    }
		    set
		    {
				this._currentFrom = value;
			}
	    }

		/// <summary>
		/// Devuelve o setea el valor de la propiedad CurrentTo.
		/// </summary>
		/// <value>Propiedad CurrentTo.</value>
	    [
		DescriptionKey("CURRENT_TO_PROPERTY"),
		PersistentProperty(IsNullable = true),
        ColumnMap(ColumnName="CURRENT_TO", DbType=System.Data.DbType.String),
	    ]
        public DateTime? CurrentTo
	    {
		    get
		    {
			    return this._currentTo;
		    }
		    set
		    {
				this._currentTo = value;
			}
	    }

		/// <summary>
		/// Devuelve o setea el valor de la propiedad EndoGroupId.
		/// </summary>
		/// <value>Propiedad EndoGroupId.</value>
	    [
		DescriptionKey("ENDO_GROUP_ID_PROPERTY"),
		PersistentProperty(),
        ColumnMap(ColumnName="ENDO_GROUP_ID", DbType=System.Data.DbType.String),
	    ]
        public int EndoGroupId
	    {
		    get
		    {
			    return this._endoGroupId;
		    }
		    set
		    {
				this._endoGroupId = value;
			}
	    }

		/// <summary>
		/// Devuelve o setea el valor de la propiedad EndorsementTypeCode.
		/// </summary>
		/// <value>Propiedad EndorsementTypeCode.</value>
	    [
		DescriptionKey("ENDORSEMENT_TYPE_CODE_PROPERTY"),
		PersistentProperty(),
        ColumnMap(ColumnName="ENDORSEMENT_TYPE_CD", DbType=System.Data.DbType.String),
	    ]
        public int EndorsementTypeCode
	    {
		    get
		    {
			    return this._endorsementTypeCode;
		    }
		    set
		    {
				this._endorsementTypeCode = value;
			}
	    }

		/// <summary>
		/// Devuelve o setea el valor de la propiedad EndorsementTypeName.
		/// </summary>
		/// <value>Propiedad EndorsementTypeName.</value>
	    [
		DescriptionKey("ENDORSEMENT_TYPE_NAME_PROPERTY"),
		PersistentProperty(),
        ColumnMap(ColumnName="ENDORSEMENT_TYPE_NAME", DbType=System.Data.DbType.String),
	    ]
        public string EndorsementTypeName
	    {
		    get
		    {
			    return this._endorsementTypeName;
		    }
		    set
		    {
				if(value == null)
				{
					throw new PropertyNotNullableException(this.GetType().FullName, Properties.EndorsementTypeName);
				}
				this._endorsementTypeName = value;
			}
	    }

		/// <summary>
		/// Devuelve o setea el valor de la propiedad PolicyId.
		/// </summary>
		/// <value>Propiedad PolicyId.</value>
	    [
		DescriptionKey("POLICY_ID_PROPERTY"),
		PersistentProperty(),
        ColumnMap(ColumnName="POLICY_ID", DbType=System.Data.DbType.String),
	    ]
        public int PolicyId
	    {
		    get
		    {
			    return this._policyId;
		    }
		    set
		    {
				this._policyId = value;
			}
	    }

		/// <summary>
		/// Devuelve o setea el valor de la propiedad AgentTypeCode.
		/// </summary>
		/// <value>Propiedad AgentTypeCode.</value>
	    [
		DescriptionKey("AGENT_TYPE_CODE_PROPERTY"),
		PersistentProperty(),
        ColumnMap(ColumnName="AGENT_TYPE_CD", DbType=System.Data.DbType.String),
	    ]
        public int AgentTypeCode
	    {
		    get
		    {
			    return this._agentTypeCode;
		    }
		    set
		    {
				this._agentTypeCode = value;
			}
	    }

		/// <summary>
		/// Devuelve o setea el valor de la propiedad AgentId.
		/// </summary>
		/// <value>Propiedad AgentId.</value>
	    [
		DescriptionKey("AGENT_ID_PROPERTY"),
		PersistentProperty(),
        ColumnMap(ColumnName="AGENT_ID", DbType=System.Data.DbType.String),
	    ]
        public int AgentId
	    {
		    get
		    {
			    return this._agentId;
		    }
		    set
		    {
				this._agentId = value;
			}
	    }

		/// <summary>
		/// Devuelve o setea el valor de la propiedad AgentDocumentNumber.
		/// </summary>
		/// <value>Propiedad AgentDocumentNumber.</value>
	    [
		DescriptionKey("AGENT_DOCUMENT_NUMBER_PROPERTY"),
		PersistentProperty(IsNullable = true),
        ColumnMap(ColumnName="AGENT_DOCUMENT_NUMBER", DbType=System.Data.DbType.String),
	    ]
        public string AgentDocumentNumber
	    {
		    get
		    {
			    return this._agentDocumentNumber;
		    }
		    set
		    {
				this._agentDocumentNumber = value;
			}
	    }

		/// <summary>
		/// Devuelve o setea el valor de la propiedad AgentName.
		/// </summary>
		/// <value>Propiedad AgentName.</value>
	    [
		DescriptionKey("AGENT_NAME_PROPERTY"),
		PersistentProperty(IsNullable = true),
        ColumnMap(ColumnName="AGENT_NAME", DbType=System.Data.DbType.String),
	    ]
        public string AgentName
	    {
		    get
		    {
			    return this._agentName;
		    }
		    set
		    {
				this._agentName = value;
			}
	    }

		/// <summary>
		/// Devuelve o setea el valor de la propiedad CurrencyCode.
		/// </summary>
		/// <value>Propiedad CurrencyCode.</value>
	    [
		DescriptionKey("CURRENCY_CODE_PROPERTY"),
		PersistentProperty(),
        ColumnMap(ColumnName="CURRENCY_CD", DbType=System.Data.DbType.String),
	    ]
        public int CurrencyCode
	    {
		    get
		    {
			    return this._currencyCode;
		    }
		    set
		    {
				this._currencyCode = value;
			}
	    }

		/// <summary>
		/// Devuelve o setea el valor de la propiedad BusinessTypeCode.
		/// </summary>
		/// <value>Propiedad BusinessTypeCode.</value>
	    [
		DescriptionKey("BUSINESS_TYPE_CODE_PROPERTY"),
		PersistentProperty(),
        ColumnMap(ColumnName="BUSINESS_TYPE_CD", DbType=System.Data.DbType.String),
	    ]
        public int BusinessTypeCode
	    {
		    get
		    {
			    return this._businessTypeCode;
		    }
		    set
		    {
				this._businessTypeCode = value;
			}
	    }

		/// <summary>
		/// Devuelve o setea el valor de la propiedad UserId.
		/// </summary>
		/// <value>Propiedad UserId.</value>
	    [
		DescriptionKey("USER_ID_PROPERTY"),
		PersistentProperty(),
        ColumnMap(ColumnName="USER_ID", DbType=System.Data.DbType.String),
	    ]
        public int UserId
	    {
		    get
		    {
			    return this._userId;
		    }
		    set
		    {
				this._userId = value;
			}
	    }

		/// <summary>
		/// Devuelve o setea el valor de la propiedad EndorsementId.
		/// </summary>
		/// <value>Propiedad EndorsementId.</value>
	    [
		DescriptionKey("ENDORSEMENT_ID_PROPERTY"),
		PersistentProperty(),
        ColumnMap(ColumnName="ENDORSEMENT_ID", DbType=System.Data.DbType.String),
	    ]
        public int EndorsementId
	    {
		    get
		    {
			    return this._endorsementId;
		    }
		    set
		    {
				this._endorsementId = value;
			}
	    }

		/// <summary>
		/// Devuelve o setea el valor de la propiedad PaymentNum.
		/// </summary>
		/// <value>Propiedad PaymentNum.</value>
	    [
		DescriptionKey("PAYMENT_NUM_PROPERTY"),
		PersistentProperty(),
        ColumnMap(ColumnName="PAYMENT_NUM", DbType=System.Data.DbType.String),
	    ]
        public int PaymentNum
	    {
		    get
		    {
			    return this._paymentNum;
		    }
		    set
		    {
				this._paymentNum = value;
			}
	    }

		/// <summary>
		/// Devuelve o setea el valor de la propiedad PayerId.
		/// </summary>
		/// <value>Propiedad PayerId.</value>
	    [
		DescriptionKey("PAYER_ID_PROPERTY"),
		PersistentProperty(),
        ColumnMap(ColumnName="PAYER_ID", DbType=System.Data.DbType.String),
	    ]
        public int PayerId
	    {
		    get
		    {
			    return this._payerId;
		    }
		    set
		    {
				this._payerId = value;
			}
	    }

		/// <summary>
		/// Devuelve o setea el valor de la propiedad RiskNum.
		/// </summary>
		/// <value>Propiedad RiskNum.</value>
	    [
		DescriptionKey("RISK_NUM_PROPERTY"),
		PersistentProperty(),
        ColumnMap(ColumnName="RISK_NUM", DbType=System.Data.DbType.String),
	    ]
        public int RiskNum
	    {
		    get
		    {
			    return this._riskNum;
		    }
		    set
		    {
				this._riskNum = value;
			}
	    }

		/// <summary>
		/// Devuelve o setea el valor de la propiedad CoverNum.
		/// </summary>
		/// <value>Propiedad CoverNum.</value>
	    [
		DescriptionKey("COVER_NUM_PROPERTY"),
		PersistentProperty(),
        ColumnMap(ColumnName="COVER_NUM", DbType=System.Data.DbType.String),
	    ]
        public int CoverNum
	    {
		    get
		    {
			    return this._coverNum;
		    }
		    set
		    {
				this._coverNum = value;
			}
	    }

		/// <summary>
		/// Devuelve o setea el valor de la propiedad RiskCoverId.
		/// </summary>
		/// <value>Propiedad RiskCoverId.</value>
	    [
		DescriptionKey("RISK_COVER_ID_PROPERTY"),
		PersistentProperty(),
        ColumnMap(ColumnName="RISK_COVER_ID", DbType=System.Data.DbType.String),
	    ]
        public int RiskCoverId
	    {
		    get
		    {
			    return this._riskCoverId;
		    }
		    set
		    {
				this._riskCoverId = value;
			}
	    }

		/// <summary>
		/// Devuelve o setea el valor de la propiedad PrefixTypeCode.
		/// </summary>
		/// <value>Propiedad PrefixTypeCode.</value>
	    [
		DescriptionKey("PREFIX_TYPE_CODE_PROPERTY"),
		PersistentProperty(),
        ColumnMap(ColumnName="PREFIX_TYPE_CD", DbType=System.Data.DbType.String),
	    ]
        public int PrefixTypeCode
	    {
		    get
		    {
			    return this._prefixTypeCode;
		    }
		    set
		    {
				this._prefixTypeCode = value;
			}
	    }

		/// <summary>
		/// Devuelve o setea el valor de la propiedad AgentAgencyId.
		/// </summary>
		/// <value>Propiedad AgentAgencyId.</value>
	    [
		DescriptionKey("AGENT_AGENCY_ID_PROPERTY"),
		PersistentProperty(),
        ColumnMap(ColumnName="AGENT_AGENCY_ID", DbType=System.Data.DbType.String),
	    ]
        public int AgentAgencyId
	    {
		    get
		    {
			    return this._agentAgencyId;
		    }
		    set
		    {
				this._agentAgencyId = value;
			}
	    }

		/// <summary>
		/// Devuelve o setea el valor de la propiedad IndividualId.
		/// </summary>
		/// <value>Propiedad IndividualId.</value>
	    [
		DescriptionKey("INDIVIDUAL_ID_PROPERTY"),
		PersistentProperty(),
        ColumnMap(ColumnName="INDIVIDUAL_ID", DbType=System.Data.DbType.String),
	    ]
        public int IndividualId
	    {
		    get
		    {
			    return this._individualId;
		    }
		    set
		    {
				this._individualId = value;
			}
	    }

    }
}