/******************************************
 * Code generated by GEB (Version: 2.2.0.0)
 * Template: Sistran.Core.Application.Accounting.Voucher.dict v1.0
 * FileSize=7196 Header=267 CRC=2464392543
 ******************************************/
using System;
using System.Collections;
using System.Collections.Generic;
using Sistran.Core.Framework;
using Sistran.Core.Framework.DAF;

namespace Sistran.Core.Application.Accounting.Entities
{
    /// <summary>
    /// Definición de entidad Voucher.
    /// </summary>
    [
    PersistentClass("Sistran.Core.Application.Accounting.Voucher.dict"),
    Serializable(),
    DescriptionKey("VOUCHER_ENTITY"),
    TableMap(TableName="VOUCHER", Schema="ACC"),
    ]
    public partial class Voucher :
        BusinessObject2
    {
#region static
		/// <summary>
		/// Propiedades públicas de la entidad.
		/// </summary>
		public static class Properties
		{
			public static readonly string VoucherId = "VoucherId";
			public static readonly string PaymentRequestCode = "PaymentRequestCode";
			public static readonly string VoucherTypeCode = "VoucherTypeCode";
			public static readonly string Number = "Number";
			public static readonly string Date = "Date";
			public static readonly string CurrencyCode = "CurrencyCode";
			public static readonly string ExchangeRate = "ExchangeRate";
		}

		/// <summary>
		/// Crea una clave primaria para una clase concreta.
		/// </summary>
		/// <param name="concreteClass">Clase concreta.</param>
		/// <param name="voucherId">Propiedad clave VoucherId.</param>
		/// <returns>Clave primaria.</returns>
	    protected static PrimaryKey InternalCreatePrimaryKey<T>(int voucherId)
	    {
		    Dictionary<string, object> keys = new Dictionary<string, object>();
		    keys.Add(Properties.VoucherId, voucherId);

		    return new PrimaryKey<T>(keys);
	    }

		/// <summary>
		/// Crea una clave primaria para esta clase.
		/// </summary>
		/// <param name="voucherId">Propiedad clave VoucherId.</param>
		public static PrimaryKey CreatePrimaryKey(int voucherId)
	    {
			return InternalCreatePrimaryKey<Voucher>(voucherId);
		}
#endregion

	    //*** Object Attributes ********************************

		/// <summary>
		/// Atributo para la propiedad PaymentRequestCode.
		/// </summary>
        private int? _paymentRequestCode = null;
		/// <summary>
		/// Atributo para la propiedad VoucherTypeCode.
		/// </summary>
        private int? _voucherTypeCode = null;
		/// <summary>
		/// Atributo para la propiedad Number.
		/// </summary>
        private string _number = null;
		/// <summary>
		/// Atributo para la propiedad Date.
		/// </summary>
        private DateTime? _date = null;
		/// <summary>
		/// Atributo para la propiedad CurrencyCode.
		/// </summary>
        private int? _currencyCode = null;
		/// <summary>
		/// Atributo para la propiedad ExchangeRate.
		/// </summary>
        private decimal? _exchangeRate = null;
	    //*** Object Constructors ********************************

		/// <summary>
		/// Constructor de instancia de la clase en base a las propiedades claves.
		/// </summary>
		/// <param name="voucherId">VoucherId key property.</param>
	    public Voucher(int voucherId):
			this(Voucher.CreatePrimaryKey(voucherId), null)
	    {
	    }

		/// <summary>
		/// Constructor de instancia de la clase en base a una clave primaria y a valores iniciales.
		/// </summary>
		/// <param name="key">
		/// Identificador de la instancia de la entidad.
		/// </param>
		/// <param name="initialValues">
		/// Valores para establecer el estado de la instancia.
		/// </param>
	    public Voucher(PrimaryKey key, IDictionary initialValues):
			base(key, initialValues)
	    {
	    }

	    /*** Object Properties ********************************/
		/// <summary>
		/// Devuelve o setea el valor de la propiedad VoucherId.
		/// </summary>
		/// <value>Propiedad VoucherId.</value>
	    [
		DescriptionKey("VOUCHER_ID_PROPERTY"),
		PersistentProperty(IsKey = true),
        ColumnMap(ColumnName="VOUCHER_ID", DbType=System.Data.DbType.String),
	    ]
        public int VoucherId
	    {
		    get
		    {
				return (int)this._primaryKey[Properties.VoucherId];
		    }
		    set
		    {
				this._primaryKey[Properties.VoucherId] = value;
			}
	    }

		/// <summary>
		/// Devuelve o setea el valor de la propiedad PaymentRequestCode.
		/// </summary>
		/// <value>Propiedad PaymentRequestCode.</value>
	    [
		DescriptionKey("PAYMENT_REQUEST_CODE_PROPERTY"),
		PersistentProperty(IsNullable = true),
        ColumnMap(ColumnName="PAYMENT_REQUEST_CD", DbType=System.Data.DbType.String),
	    ]
        public int? PaymentRequestCode
	    {
		    get
		    {
			    return this._paymentRequestCode;
		    }
		    set
		    {
				this._paymentRequestCode = value;
			}
	    }

		/// <summary>
		/// Devuelve o setea el valor de la propiedad VoucherTypeCode.
		/// </summary>
		/// <value>Propiedad VoucherTypeCode.</value>
	    [
		DescriptionKey("VOUCHER_TYPE_CODE_PROPERTY"),
		PersistentProperty(IsNullable = true),
        ColumnMap(ColumnName="VOUCHER_TYPE_CD", DbType=System.Data.DbType.String),
	    ]
        public int? VoucherTypeCode
	    {
		    get
		    {
			    return this._voucherTypeCode;
		    }
		    set
		    {
				this._voucherTypeCode = value;
			}
	    }

		/// <summary>
		/// Devuelve o setea el valor de la propiedad Number.
		/// </summary>
		/// <value>Propiedad Number.</value>
	    [
		DescriptionKey("NUMBER_PROPERTY"),
		PersistentProperty(IsNullable = true),
        ColumnMap(ColumnName="NUMBER", DbType=System.Data.DbType.String),
	    ]
        public string Number
	    {
		    get
		    {
			    return this._number;
		    }
		    set
		    {
				this._number = value;
			}
	    }

		/// <summary>
		/// Devuelve o setea el valor de la propiedad Date.
		/// </summary>
		/// <value>Propiedad Date.</value>
	    [
		DescriptionKey("DATE_PROPERTY"),
		PersistentProperty(IsNullable = true),
        ColumnMap(ColumnName="DATE", DbType=System.Data.DbType.String),
	    ]
        public DateTime? Date
	    {
		    get
		    {
			    return this._date;
		    }
		    set
		    {
				this._date = value;
			}
	    }

		/// <summary>
		/// Devuelve o setea el valor de la propiedad CurrencyCode.
		/// </summary>
		/// <value>Propiedad CurrencyCode.</value>
	    [
		DescriptionKey("CURRENCY_CODE_PROPERTY"),
		PersistentProperty(IsNullable = true),
        ColumnMap(ColumnName="CURRENCY_CD", DbType=System.Data.DbType.String),
	    ]
        public int? CurrencyCode
	    {
		    get
		    {
			    return this._currencyCode;
		    }
		    set
		    {
				this._currencyCode = value;
			}
	    }

		/// <summary>
		/// Devuelve o setea el valor de la propiedad ExchangeRate.
		/// </summary>
		/// <value>Propiedad ExchangeRate.</value>
	    [
		DescriptionKey("EXCHANGE_RATE_PROPERTY"),
		PersistentProperty(IsNullable = true),
        ColumnMap(ColumnName="EXCHANGE_RATE", DbType=System.Data.DbType.Decimal),
	    ]
        public decimal? ExchangeRate
	    {
		    get
		    {
			    return this._exchangeRate;
		    }
		    set
		    {
				this._exchangeRate = value;
			}
	    }

    }
}