var ProductResource = {
    ControlButtonEnabled: 'Habilitar Producto',
    ControlButtonDisabled: 'Deshabilitar Producto',
    ErrorAgentDuplicate: 'Agente ya ha sido Asignado',
    ErrorCurrency: 'Error Obteniendo Moneda',
    ErrorRiskTypeEmpty: 'Error No hay tipos de Riesgo',
    ErrorSelectAgency: 'No ha seleccionado una Agencia',
    ErrorSelectAgent: 'No ha seleccionado un Agente',
    ErrorNotAgents: 'No se encontraron agentes',
    ErrorQueryAgents: 'Error al consultar agentes',
    ErrorSearchAgents: 'Error al consultar agentes',
    ErrorSearchProduct: 'Error al consultar producto',
    ErrorSelectInsuredObject: 'No ha seleccionado un Objeto de Seguro',
    ErrorSelectTypeRisk: 'Seleccione un tipo de riesgo para continuar',
    ErrorSelectRiskType: 'No hay Tipos de Riesgo para este ramo',
    ErrorSelectPoliciType: 'Seleccione un tipo de poliza para continuar',
    ErrorSelectPrefix: 'Seleccione el Ramo',
    ErrorInsuredObjectAssigned: 'El Objeto del seguro ya se encuentra asignado',
    ErrorSaveProduct: 'Error al guardar Producto',
    ErrorCoverageAssigned: 'La Cobertura ya se encuentra asignada',
    ErrorSelectCoverage: 'No ha seleccionado una Cobertura',
    ErrorDeleteCoverage: 'La Cobertura no se puede eliminar',
    ErrorGetCoverage: 'Error al consultar la cobertura',
    ErrorDeleteInsuredObject: 'El Objeto del Seguro no se puede eliminar',
    ErrorGetInsuredObject: 'Error al consultar Objeto del Seguro',
    ErrorValidCoverage: 'Debe asignar al menos una cobertura a cada objeto de seguro',
    ErroGetProduct: 'Error al Obtener el Producto',
    ErrorGetCoveragesByTechnicalPlan: 'Error al obtener coberturas por código de plan técnico',
    ErrorPolicyTypeDuplicate: 'Tipo de poliza ya ha sido Asignado',
    ErrorPolicyTypeDefaultDuplicate: 'Tipo de Poliza por defecto ya ha sido Asignado',
    ErrorRiskTypeDuplicate: 'Tipo de Riesgo ya ha sido Asignado',
    ErrorPrefix: 'Debe seleccionar un ramo comercial',
    ErrorPolicyTypeMain: 'Solo debe existir un tipo de poliza por defecto',
    InfoSaveAgencySelected: 'Debe Seleccionar una Agencia',
    LabelAdditionalData: 'Datos Adicionales',
    LabelAgentPrincipal: 'Seleccione el Agente Principal',
    LabelCopyProduct: 'Copiar Producto',
    labelDifferentialCommission: 'Comisión Diferencial',
    LabelGroupCoverage: 'Grupo de Cobertura',
    LabelInformative: 'La siguiente información es obligatoria',
    LabelIntermediariesCommissions: 'Intermediarios y Comisiones',
    LabelInsuredObject: 'Objeto de Seguro',
    LabelProducts: 'Productos',
    LabelProduct: 'Producto',
    LabelRulesAndScripts: 'Reglas y Guiones del producto',
    MessageBranch: 'Debe seleccionar un ramo comercial para obtener los tipos de pólizas',
    MessageCopyProduct: 'Debe Seleccionar un Producto',
    MessageObjectInsurance: 'Datos del Objeto del Seguro',
    MessageProduct: 'Seleccione un Producto',
    MessagePrefix: 'Debe seleccionar una ramo comercial',
    MessageRiskType: 'Tipos de Riesgo',
    MessageSearchAgents: 'No se encontraron agentes',
    MessageTechnicalConditions: 'Condiciones Técnicas',
    MessageInsuredObjectInUse: 'El producto ya esta Asignado a una Poliza o Temporal',
    CoverageNoHaveAllyCoverage: 'No tiene coberturas aliadas',
    CoverageHaveAllyCoverage: 'Tiene Aliadas',
    CoverageNotHaveAllyCoverage: 'No tiene aliadas',
    CoverageAlreadyExists: 'La cobertura ya fue asignada',
    SuccessSaveProduct: 'Producto guardado correctamente',
    InfoMinCoverageProduct: 'El producto debe tener mínimo una cobertura',
    InfoCantEnableDisableProduct: 'No se puede Habilitar / Deshabilitar el producto',
    WarningCurrencyTypePaymentPlan: 'No todos los tipos de moneda tienen un plan de pago predeterminado'

};
