/******************************************
 * Code generated by GEB (Version: 2.2.0.0)
 * Template: Sistran.Core.Application.UnderwritingServices.ConceptType.dict v1.0
 * FileSize=4014 Header=261 CRC=191358254
 ******************************************/
using System;
using System.Collections;
using System.Collections.Generic;
using Sistran.Core.Framework;
using Sistran.Core.Framework.DAF;

namespace Sistran.Core.Application.RulesScriptsServices.EEProvider.Entities
{
    /// <summary>
    /// Definición de entidad ConceptType.
    /// </summary>
    [
    PersistentClass("Sistran.Core.Application.RulesScriptsServices.EEProvider.ConceptType.dict"),
    Serializable(),
    DescriptionKey("CONCEPT_TYPE_ENTITY"),
    TableMap(TableName = "CONCEPT_TYPE", Schema = "PARAM"),
    ]
    public partial class ConceptType : BusinessObject2
    {
        public enum Types
        {
            Basic = 1,
            Range = 2,
            List = 3,
            Reference = 4
        }
        #region static
        /// <summary>
        /// Propiedades públicas de la entidad.
        /// </summary>
        public static class Properties
        {
            public static readonly string ConceptTypeCode = "ConceptTypeCode";
            public static readonly string Description = "Description";
        }

        /// <summary>
        /// Crea una clave primaria para una clase concreta.
        /// </summary>
        /// <param name="concreteClass">Clase concreta.</param>
        /// <param name="conceptTypeCode">Propiedad clave ConceptTypeCode.</param>
        /// <returns>Clave primaria.</returns>
        protected static PrimaryKey InternalCreatePrimaryKey<T>(int conceptTypeCode)
        {
            Dictionary<string, object> keys = new Dictionary<string, object>();
            keys.Add(Properties.ConceptTypeCode, conceptTypeCode);

            return new PrimaryKey<T>(keys);
        }

        /// <summary>
        /// Crea una clave primaria para esta clase.
        /// </summary>
        /// <param name="conceptTypeCode">Propiedad clave ConceptTypeCode.</param>
        public static PrimaryKey CreatePrimaryKey(int conceptTypeCode)
        {
            return InternalCreatePrimaryKey<ConceptType>(conceptTypeCode);
        }
        #endregion

        //*** Object Attributes ********************************

        /// <summary>
        /// Atributo para la propiedad Description.
        /// </summary>
        private string _description = null;
        //*** Object Constructors ********************************

        /// <summary>
        /// Constructor de instancia de la clase en base a las propiedades claves.
        /// </summary>
        /// <param name="conceptTypeCode">ConceptTypeCode key property.</param>
        public ConceptType(int conceptTypeCode) :
            this(ConceptType.CreatePrimaryKey(conceptTypeCode), null)
        {
        }

        /// <summary>
        /// Constructor de instancia de la clase en base a una clave primaria y a valores iniciales.
        /// </summary>
        /// <param name="key">
        /// Identificador de la instancia de la entidad.
        /// </param>
        /// <param name="initialValues">
        /// Valores para establecer el estado de la instancia.
        /// </param>
        public ConceptType(PrimaryKey key, IDictionary initialValues) :
            base(key, initialValues)
        {
        }

        /*** Object Properties ********************************/
        /// <summary>
        /// Devuelve o setea el valor de la propiedad ConceptTypeCode.
        /// </summary>
        /// <value>Propiedad ConceptTypeCode.</value>
        [
        DescriptionKey("CONCEPT_TYPE_CODE_PROPERTY"),
        PersistentProperty(IsKey = true),
        ColumnMap(ColumnName = "CONCEPT_TYPE_CD", DbType = System.Data.DbType.String),
        ]
        public int ConceptTypeCode
        {
            get
            {
                return (int)this._primaryKey[Properties.ConceptTypeCode];
            }
            set
            {
                this._primaryKey[Properties.ConceptTypeCode] = value;
            }
        }

        /// <summary>
        /// Devuelve o setea el valor de la propiedad Description.
        /// </summary>
        /// <value>Propiedad Description.</value>
        [
        DescriptionKey("DESCRIPTION_PROPERTY"),
        PersistentProperty(),
        ColumnMap(ColumnName = "DESCRIPTION", DbType = System.Data.DbType.String),
        ]
        public string Description
        {
            get
            {
                return this._description;
            }
            set
            {
                if (value == null)
                {
                    throw new PropertyNotNullableException(this.GetType().FullName, Properties.Description);
                }
                this._description = value;
            }
        }

    }
}