namespace Sistran.Core.Services.UtilitiesServices.Enums
{

    public enum FileType
    {
        Excel = 1,
        CSV = 2
    }

    public enum FieldType
    {
        Int32 = 1,
        Int64 = 2,
        Decimal = 3,
        String = 4,
        DateTime = 5,
        Boolean = 6,
        Int8 = 7,
        Int16 = 8
    }

    public enum FileProcessType
    {
        Undefined = 0,
        MassiveEmission = 1,
        CollectiveEmission = 2,
        ParametrizationLineBusiness = 3,
        ParametrizationSubLineBusiness = 4,
        ParametrizationPrefix = 5,
        ParametrizationBranch = 6,
        ParametrizationCoverage = 7,
        ParametrizationInsuredObject = 8,
        ParametrizationPeril = 9,
        Profiles = 10,
        Modules = 11,
        Submodules = 12,
        Accesses = 13,
        MassiveRenewal = 14,
        PayrollAgent = 15,
        CancellationMassive = 16,
        MassiveReport = 17,
        CollectiveRenewal = 18,
        ParametrizationText = 19,
        CollectiveInclusion = 20,
        CollectiveExclusion = 21,
        ProcessReport = 22,
        ParametrizationProduct = 23,
        ParametrizationDeductible = 24,
        ParametrizationClause = 25,
        ParametrizationDiscount = 26,
        ParametrizationSurcharge = 27,
        ParametrizationPaymentPlan = 28,
        ParametrizationServiceQuotationSource = 29,
        ParametrizationCeoveredRiskType = 30,
        ParametrizationInsuredProfile = 31,
        ParametrizationInsuredSegment = 32,
        ParametrizationAlliance = 33,
        ParametrizationBranchAlliance = 34,
        ParametrizationSalePointsAlliance = 35,
        ParametrizationAssistanceType = 37,
        ParametrizationProduct2G = 38,
        ParametrizationVehicleType = 39,
        ParametrizationVehicleTypeBody = 40,
        ParametrizationPrintAllyFormat = 41,
        ParametrizationServiceRatingZone = 42,
        ParametrizationQuotationNumber = 43,
        ParametrizationDetail = 44,
        ParametrizationCoverageGroupRiskType = 45,
        ParametrizationLegalReprSign = 46,
        ParametrizationSalePoint = 47,
        ParametrizationInfringement = 48,
        ParametrizationInfringementGroup = 49,
        ParametrizationInfringementState = 50,
        ParametrizationVehicleBody = 51,
        ParametrizationVehicleBodyUse = 52,
        ParametrizationExpenseComponent = 61,
        ParametrizationPaymentMethod = 64,
        ParametrizationVehicleModel = 65,
        ParametrizationFasecolda = 54,
        ParametrizationWorkerType = 62,
        LogAudit = 55,
        ParametrizationPolicyNumber = 56,
        ParametrizationVehicleVersion = 63,
        BusinessConfiguration = 57,
        AddressType = 58,
        PhoneType = 59,
        ScoreTypeDoc = 60,
        ScriptReport = 67,
        ParametrizationLimitRc = 68,
        ParametrizationVehicleVersionYear = 69,
        ParametrizationTechnicalPlan = 70,
        ParametrizationProducts = 72,
        ParametrizationDecisionTables = 73,
        Rules = 74,
        ParametrizationConcepts = 75,
        ParametrizationRejectionCauses = 76,
        ParametrizationRatingZoneBranch = 78,
        ParametrizationDelegations = 95,
        ParametrizationMinPremiunRelation = 94,
        ParametrizationCoCoverageValue = 92,
        ParametrizationAllyCoverage = 97,
        QuotationSearch = 98,
        PolicySearch = 99,
        ParametrizationProductionReport = 100,
        ParametrizationTaxReport = 101,
        ParametrizationTextPrecatalogued = 102,
        //................................
        PoliciesReport = 103,
        LoadCodesFaseColda = 104,
        LoadValuesFaseColda = 105,
        ErroresFaseColda = 106,
        ListRisk = 107,
        ParametrizationFinancialPlan = 108,

    }

    public enum FileProcessFilter
    {
        ProcessType = 1,
        EndorsementType = 2,
        LoadType = 3,
        Prefix = 4,
        RiskType = 5
    }

    public enum ValidationProperty
    {
        Undefined = 0,
        City = 1,
        State = 2,
        EconomicActivity = 3,
        CoVehiculeType = 4,
        RatingZone = 5,
        GroupCoverage = 6,
        AddressType = 7,
        Bank = 8,
        BeneficiaryType = 9,
        VehicleColor = 10,
        Currency = 11,
        Deductible = 12,
        Fasecolda = 13,
        PaymentSchedule = 14,
        ServiceType = 15,
        Shuttle = 16,
        DocumentType = 17,
        MaritalStatus = 18,
        StreetType = 19,
        CompanyType = 20,
        Country = 21,
        PhoneType = 22,
        EmailType = 23,
        VehicleType = 24,
        VehicleUse = 25,
        VehicleBody = 26,
        VehicleFuel = 27,
        RcLimitProduct = 28,
        Coverage = 29,
        AccesoryDetail = 30,
        Product = 31,
        RiskTypeLocationN = 32,
        Agent = 33,
        PolicyType = 34,
        RiskActivity = 35,
        HouseType = 36,
        ConstructionCategory = 37,
        AgentType = 38,
        GrouInsuredObject = 39,
        CoInsuranceCompany = 40,
        AgentAgency = 41,
        BusinessType = 42,
        Insured = 43,
        Holder = 44,
        Beneficiary = 45,
        TributaryType = 46,
        IndividualType = 47,
        Branch = 48,
        Prefix = 49,
        AgentAgencyRenewal = 50,
        CoverageRenewal = 51,
        DeductibleRenewal = 52,
        GroupInsuredObjectRenewal = 53,
        EndorsementType = 54,
        EndorsemenrReason = 55,
        InsuredObject = 56,
        ClauseLevel = 57,
        SalePoint = 58,
        RiskCOfConstruction = 60,
        CoInsurance = 65,
        AgentRen = 75,
        CoverageRen = 76,
        DeductibleRen = 77,
        InsuredObjectRen = 78,
        CoLimitsRC_Rel = 79,
        IrregularHeightEarthquake = 80,
        IrregularPlantEarthquake = 81,
        PreviousDamagesEarthquake = 82,
        RepairedEarthquake = 83,
        ReinforcedStructureTypeEarthquake = 84,
        StructureTypeEarthquake = 85,
        RiskTypeOfProperty = 86,
    }

    public enum RegularExpression
    {
        Undefined = 0,
        cellPhone = 1,
        cellPhoneBank = 2,
        email = 3,
        gender = 4,
        longitude = 5,
        latitude = 6,
        date = 7,
        RiskRate = 8,
        RiskLicensePlate = 9,
        SpecialCharacter = 10
    }
}
