/******************************************
 * Code generated by GEB (Version: 2.2.0.0)
 * Template: namespaces.TributaryIdentityType.dict v1.0
 * FileSize=4987 Header=237 CRC=1260061310
 ******************************************/
using Sistran.Core.Framework;
using Sistran.Core.Framework.DAF;
using System;
using System.Collections;
using System.Collections.Generic;

namespace Sistran.Core.Application.UniquePerson.Entities
{
    /// <summary>
    /// Definición de entidad TributaryIdentityType.
    /// </summary>
    [
    PersistentClass("Sistran.Core.Application.UniquePerson.TributaryIdentityType.dict"),
    Serializable(),
    DescriptionKey("TRIBUTARY_IDENTITY_TYPE_ENTITY"),
    TableMap(TableName = "TRIBUTARY_IDENTITY_TYPE", Schema = "UP"),
    ]
    public partial class TributaryIdentityType :
        BusinessObject2
    {
        #region static
        /// <summary>
        /// Propiedades públicas de la entidad.
        /// </summary>
        public static class Properties
        {
            public static readonly string TributaryIdTypeCode = "TributaryIdTypeCode";
            public static readonly string Description = "Description";
            public static readonly string SmallDescription = "SmallDescription";
        }

        /// <summary>
        /// Crea una clave primaria para una clase concreta.
        /// </summary>
        /// <param name="concreteClass">Clase concreta.</param>
        /// <param name="tributaryIdTypeCode">Propiedad clave TributaryIdTypeCode.</param>
        /// <returns>Clave primaria.</returns>
        protected static PrimaryKey InternalCreatePrimaryKey<T>(int tributaryIdTypeCode)
        {
            Dictionary<string, object> keys = new Dictionary<string, object>();
            keys.Add(Properties.TributaryIdTypeCode, tributaryIdTypeCode);

            return new PrimaryKey<T>(keys);
        }

        protected static PrimaryKey InternalCreatePrimaryKey<T>()
        {
            Dictionary<string, object> keys = new Dictionary<string, object>();
            keys.Add(Properties.TributaryIdTypeCode, null);

            return new PrimaryKey<T>(keys);
        }

        /// <summary>
        /// Crea una clave primaria para esta clase.
        /// </summary>
        /// <param name="tributaryIdTypeCode">Propiedad clave TributaryIdTypeCode.</param>
        public static PrimaryKey CreatePrimaryKey(int tributaryIdTypeCode)
        {
            return InternalCreatePrimaryKey<TributaryIdentityType>(tributaryIdTypeCode);
        }

        public static PrimaryKey CreatePrimaryKey()
        {
            return InternalCreatePrimaryKey<TributaryIdentityType>();
        }
        #endregion

        //*** Object Attributes ********************************

        /// <summary>
        /// Atributo para la propiedad Description.
        /// </summary>
        private string _description = null;
        /// <summary>
        /// Atributo para la propiedad SmallDescription.
        /// </summary>
        private string _smallDescription = null;
        //*** Object Constructors ********************************

        /// <summary>
        /// Constructor de instancia de la clase en base a las propiedades claves.
        /// </summary>
        /// <param name="tributaryIdTypeCode">TributaryIdTypeCode key property.</param>
        public TributaryIdentityType(int tributaryIdTypeCode) :
            this(TributaryIdentityType.CreatePrimaryKey(tributaryIdTypeCode), null)
        {
        }

        public TributaryIdentityType() :
            this(TributaryIdentityType.CreatePrimaryKey(), null)
        {
        }

        /// <summary>
        /// Constructor de instancia de la clase en base a una clave primaria y a valores iniciales.
        /// </summary>
        /// <param name="key">
        /// Identificador de la instancia de la entidad.
        /// </param>
        /// <param name="initialValues">
        /// Valores para establecer el estado de la instancia.
        /// </param>
        public TributaryIdentityType(PrimaryKey key, IDictionary initialValues) :
            base(key, initialValues)
        {
        }


        /// <summary>
        /// Devuelve o setea el valor de la propiedad TributaryIdTypeCode.
        /// </summary>
        /// <value>Propiedad TributaryIdTypeCode.</value>
        [
        DescriptionKey("TRIBUTARY_ID_TYPE_CODE_PROPERTY"),
        PersistentProperty(IsKey = true, KeyType ="None"),
        ColumnMap(ColumnName = "TRIBUTARY_ID_TYPE_CD", DbType = System.Data.DbType.String),
        ]
        public int TributaryIdTypeCode
        {
            get
            {
                return (int)this._primaryKey[Properties.TributaryIdTypeCode];
            }
            set
            {
                this._primaryKey[Properties.TributaryIdTypeCode] = value;
            }
        }

        /// <summary>
        /// Devuelve o setea el valor de la propiedad Description.
        /// </summary>
        /// <value>Propiedad Description.</value>
        [
        DescriptionKey("DESCRIPTION_PROPERTY"),
        PersistentProperty(),
        ColumnMap(ColumnName = "DESCRIPTION", DbType = System.Data.DbType.String),
        ]
        public string Description
        {
            get
            {
                return this._description;
            }
            set
            {
                if (value == null)
                {
                    throw new PropertyNotNullableException(this.GetType().FullName, Properties.Description);
                }
                this._description = value;
            }
        }

        /// <summary>
        /// Devuelve o setea el valor de la propiedad SmallDescription.
        /// </summary>
        /// <value>Propiedad SmallDescription.</value>
        [
        DescriptionKey("SMALL_DESCRIPTION_PROPERTY"),
        PersistentProperty(),
        ColumnMap(ColumnName = "SMALL_DESCRIPTION", DbType = System.Data.DbType.String),
        ]
        public string SmallDescription
        {
            get
            {
                return this._smallDescription;
            }
            set
            {
                if (value == null)
                {
                    throw new PropertyNotNullableException(this.GetType().FullName, Properties.SmallDescription);
                }
                this._smallDescription = value;
            }
        }

    }
}