/******************************************
 * Code generated by GEB (Version: 2.2.0.0)
 * Template: Sistran.Core.Application.Quotation.CoMassiveLoadVehiclePolicy.dict v1.0
 * FileSize=12441 Header=266 CRC=121571761
 ******************************************/
using Sistran.Core.Framework;
using Sistran.Core.Framework.DAF;
using System;
using System.Collections;
using System.Collections.Generic;

namespace Sistran.Core.Application.Quotation.Entities
{
    /// <summary>
    /// Definición de entidad CoMassiveLoadVehiclePolicy.
    /// </summary>
    [
    PersistentClass("Sistran.Core.Application.Quotation.CoMassiveLoadVehiclePolicy.dict"),
    Serializable(),
    DescriptionKey("CO_MASSIVE_LOAD_VEHICLE_POLICY_ENTITY"),
    TableMap(TableName = "CO_MASSIVE_LOAD_VEHICLE_POLICY", Schema = "QUO"),
    ]
    public partial class CoMassiveLoadVehiclePolicy :
        BusinessObject2
    {
        #region static
        /// <summary>
        /// Propiedades públicas de la entidad.
        /// </summary>
        public static class Properties
        {
            public static readonly string MassiveLoadId = "MassiveLoadId";
            public static readonly string MassiveLoadVehiclePolicyId = "MassiveLoadVehiclePolicyId";
            public static readonly string LimitsRcCode = "LimitsRcCode";
            public static readonly string FasecoldaMakeId = "FasecoldaMakeId";
            public static readonly string FasecoldaModelId = "FasecoldaModelId";
            public static readonly string IncludeAssistenceCover = "IncludeAssistenceCover";
            public static readonly string PolicyTypeCode = "PolicyTypeCode";
            public static readonly string InSurname2 = "InSurname2";
            public static readonly string BeSurname2 = "BeSurname2";
            public static readonly string PhSurname2 = "PhSurname2";
            public static readonly string SinisterPercentage = "SinisterPercentage";
            public static readonly string HasSinister = "HasSinister";
            public static readonly string AssistanceCode = "AssistanceCode";
        }

        /// <summary>
        /// Crea una clave primaria para una clase concreta.
        /// </summary>
        /// <param name="concreteClass">Clase concreta.</param>
        /// <param name="massiveLoadId">Propiedad clave MassiveLoadId.</param>
        /// <param name="massiveLoadVehiclePolicyId">Propiedad clave MassiveLoadVehiclePolicyId.</param>
        /// <returns>Clave primaria.</returns>
        protected static PrimaryKey InternalCreatePrimaryKey<T>(int massiveLoadId, int massiveLoadVehiclePolicyId)
        {
            Dictionary<string, object> keys = new Dictionary<string, object>();
            keys.Add(Properties.MassiveLoadId, massiveLoadId);
            keys.Add(Properties.MassiveLoadVehiclePolicyId, massiveLoadVehiclePolicyId);

            return new PrimaryKey<T>(keys);
        }

        /// <summary>
        /// Crea una clave primaria para esta clase.
        /// </summary>
        /// <param name="massiveLoadId">Propiedad clave MassiveLoadId.</param>
        /// <param name="massiveLoadVehiclePolicyId">Propiedad clave MassiveLoadVehiclePolicyId.</param>
        public static PrimaryKey CreatePrimaryKey(int massiveLoadId, int massiveLoadVehiclePolicyId)
        {
            return InternalCreatePrimaryKey<CoMassiveLoadVehiclePolicy>(massiveLoadId, massiveLoadVehiclePolicyId);
        }
        #endregion

        //*** Object Attributes ********************************

        /// <summary>
        /// Atributo para la propiedad LimitsRcCode.
        /// </summary>
        private int? _limitsRcCode = null;
        /// <summary>
        /// Atributo para la propiedad FasecoldaMakeId.
        /// </summary>
        private string _fasecoldaMakeId = null;
        /// <summary>
        /// Atributo para la propiedad FasecoldaModelId.
        /// </summary>
        private string _fasecoldaModelId = null;
        /// <summary>
        /// Atributo para la propiedad IncludeAssistenceCover.
        /// </summary>
        private bool _includeAssistenceCover;
        /// <summary>
        /// Atributo para la propiedad PolicyTypeCode.
        /// </summary>
        private int? _policyTypeCode = null;
        /// <summary>
        /// Atributo para la propiedad InSurname2.
        /// </summary>
        private string _inSurname2 = null;
        /// <summary>
        /// Atributo para la propiedad BeSurname2.
        /// </summary>
        private string _beSurname2 = null;
        /// <summary>
        /// Atributo para la propiedad PhSurname2.
        /// </summary>
        private string _phSurname2 = null;
        /// <summary>
        /// Atributo para la propiedad SinisterPercentage.
        /// </summary>
        private bool? _sinisterPercentage = null;
        /// <summary>
        /// Atributo para la propiedad HasSinister.
        /// </summary>
        private int? _hasSinister = null;
        /// <summary>
        /// Atributo para la propiedad AssistanceCode.
        /// </summary>
        private string _assistanceCode = null;
        //*** Object Constructors ********************************

        /// <summary>
        /// Constructor de instancia de la clase en base a las propiedades claves.
        /// </summary>
        /// <param name="massiveLoadId">MassiveLoadId key property.</param>
        /// <param name="massiveLoadVehiclePolicyId">MassiveLoadVehiclePolicyId key property.</param>
        public CoMassiveLoadVehiclePolicy(int massiveLoadId, int massiveLoadVehiclePolicyId) :
            this(CoMassiveLoadVehiclePolicy.CreatePrimaryKey(massiveLoadId, massiveLoadVehiclePolicyId), null)
        {
        }

        /// <summary>
        /// Constructor de instancia de la clase en base a una clave primaria y a valores iniciales.
        /// </summary>
        /// <param name="key">
        /// Identificador de la instancia de la entidad.
        /// </param>
        /// <param name="initialValues">
        /// Valores para establecer el estado de la instancia.
        /// </param>
        public CoMassiveLoadVehiclePolicy(PrimaryKey key, IDictionary initialValues) :
            base(key, initialValues)
        {
        }

        /*** Object Properties ********************************/
        /// <summary>
        /// Devuelve o setea el valor de la propiedad MassiveLoadId.
        /// </summary>
        /// <value>Propiedad MassiveLoadId.</value>
        [
        DescriptionKey("MASSIVE_LOAD_ID_PROPERTY"),
        PersistentProperty(IsKey = true),
        ColumnMap(ColumnName = "MASSIVE_LOAD_ID", DbType = System.Data.DbType.String),
        ]
        public int MassiveLoadId
        {
            get
            {
                return (int)this._primaryKey[Properties.MassiveLoadId];
            }
            set
            {
                this._primaryKey[Properties.MassiveLoadId] = value;
            }
        }

        /// <summary>
        /// Devuelve o setea el valor de la propiedad MassiveLoadVehiclePolicyId.
        /// </summary>
        /// <value>Propiedad MassiveLoadVehiclePolicyId.</value>
        [
        DescriptionKey("MASSIVE_LOAD_VEHICLE_POLICY_ID_PROPERTY"),
        PersistentProperty(IsKey = true),
        ColumnMap(ColumnName = "MASSIVE_LOAD_VEHICLE_POLICY_ID", DbType = System.Data.DbType.String),
        ]
        public int MassiveLoadVehiclePolicyId
        {
            get
            {
                return (int)this._primaryKey[Properties.MassiveLoadVehiclePolicyId];
            }
            set
            {
                this._primaryKey[Properties.MassiveLoadVehiclePolicyId] = value;
            }
        }

        /// <summary>
        /// Devuelve o setea el valor de la propiedad LimitsRcCode.
        /// </summary>
        /// <value>Propiedad LimitsRcCode.</value>
        [
        DescriptionKey("LIMITS_RC_CODE_PROPERTY"),
        PersistentProperty(IsNullable = true),
        ColumnMap(ColumnName = "LIMITS_RC_CD", DbType = System.Data.DbType.String),
        ]
        public int? LimitsRcCode
        {
            get
            {
                return this._limitsRcCode;
            }
            set
            {
                this._limitsRcCode = value;
            }
        }

        /// <summary>
        /// Devuelve o setea el valor de la propiedad FasecoldaMakeId.
        /// </summary>
        /// <value>Propiedad FasecoldaMakeId.</value>
        [
        DescriptionKey("FASECOLDA_MAKE_ID_PROPERTY"),
        PersistentProperty(IsNullable = true),
        ColumnMap(ColumnName = "FASECOLDA_MAKE_ID", DbType = System.Data.DbType.String),
        ]
        public string FasecoldaMakeId
        {
            get
            {
                return this._fasecoldaMakeId;
            }
            set
            {
                this._fasecoldaMakeId = value;
            }
        }

        /// <summary>
        /// Devuelve o setea el valor de la propiedad FasecoldaModelId.
        /// </summary>
        /// <value>Propiedad FasecoldaModelId.</value>
        [
        DescriptionKey("FASECOLDA_MODEL_ID_PROPERTY"),
        PersistentProperty(IsNullable = true),
        ColumnMap(ColumnName = "FASECOLDA_MODEL_ID", DbType = System.Data.DbType.String),
        ]
        public string FasecoldaModelId
        {
            get
            {
                return this._fasecoldaModelId;
            }
            set
            {
                this._fasecoldaModelId = value;
            }
        }

        /// <summary>
        /// Devuelve o setea el valor de la propiedad IncludeAssistenceCover.
        /// </summary>
        /// <value>Propiedad IncludeAssistenceCover.</value>
        [
        DescriptionKey("INCLUDE_ASSISTENCE_COVER_PROPERTY"),
        PersistentProperty(),
        ColumnMap(ColumnName = "INCLUDE_ASSISTENCE_COVER", DbType = System.Data.DbType.String),
        ]
        public bool IncludeAssistenceCover
        {
            get
            {
                return this._includeAssistenceCover;
            }
            set
            {
                this._includeAssistenceCover = value;
            }
        }

        /// <summary>
        /// Devuelve o setea el valor de la propiedad PolicyTypeCode.
        /// </summary>
        /// <value>Propiedad PolicyTypeCode.</value>
        [
        DescriptionKey("POLICY_TYPE_CODE_PROPERTY"),
        PersistentProperty(IsNullable = true),
        ColumnMap(ColumnName = "POLICY_TYPE_CD", DbType = System.Data.DbType.String),
        ]
        public int? PolicyTypeCode
        {
            get
            {
                return this._policyTypeCode;
            }
            set
            {
                this._policyTypeCode = value;
            }
        }

        /// <summary>
        /// Devuelve o setea el valor de la propiedad InSurname2.
        /// </summary>
        /// <value>Propiedad InSurname2.</value>
        [
        DescriptionKey("IN_SURNAME2_PROPERTY"),
        PersistentProperty(IsNullable = true),
        ColumnMap(ColumnName = "IN_SURNAME_2", DbType = System.Data.DbType.String),
        ]
        public string InSurname2
        {
            get
            {
                return this._inSurname2;
            }
            set
            {
                this._inSurname2 = value;
            }
        }

        /// <summary>
        /// Devuelve o setea el valor de la propiedad BeSurname2.
        /// </summary>
        /// <value>Propiedad BeSurname2.</value>
        [
        DescriptionKey("BE_SURNAME2_PROPERTY"),
        PersistentProperty(IsNullable = true),
        ColumnMap(ColumnName = "BE_SURNAME_2", DbType = System.Data.DbType.String),
        ]
        public string BeSurname2
        {
            get
            {
                return this._beSurname2;
            }
            set
            {
                this._beSurname2 = value;
            }
        }

        /// <summary>
        /// Devuelve o setea el valor de la propiedad PhSurname2.
        /// </summary>
        /// <value>Propiedad PhSurname2.</value>
        [
        DescriptionKey("PH_SURNAME2_PROPERTY"),
        PersistentProperty(IsNullable = true),
        ColumnMap(ColumnName = "PH_SURNAME_2", DbType = System.Data.DbType.String),
        ]
        public string PhSurname2
        {
            get
            {
                return this._phSurname2;
            }
            set
            {
                this._phSurname2 = value;
            }
        }

        /// <summary>
        /// Devuelve o setea el valor de la propiedad SinisterPercentage.
        /// </summary>
        /// <value>Propiedad SinisterPercentage.</value>
        [
        DescriptionKey("SINISTER_PERCENTAGE_PROPERTY"),
        PersistentProperty(IsNullable = true),
        ColumnMap(ColumnName = "SINISTER_PCT", DbType = System.Data.DbType.String),
        ]
        public bool? SinisterPercentage
        {
            get
            {
                return this._sinisterPercentage;
            }
            set
            {
                this._sinisterPercentage = value;
            }
        }

        /// <summary>
        /// Devuelve o setea el valor de la propiedad HasSinister.
        /// </summary>
        /// <value>Propiedad HasSinister.</value>
        [
        DescriptionKey("HAS_SINISTER_PROPERTY"),
        PersistentProperty(IsNullable = true),
        ColumnMap(ColumnName = "HAS_SINISTER", DbType = System.Data.DbType.String),
        ]
        public int? HasSinister
        {
            get
            {
                return this._hasSinister;
            }
            set
            {
                this._hasSinister = value;
            }
        }

        /// <summary>
        /// Devuelve o setea el valor de la propiedad AssistanceCode.
        /// </summary>
        /// <value>Propiedad AssistanceCode.</value>
        [
        DescriptionKey("ASSISTANCE_CODE_PROPERTY"),
        PersistentProperty(IsNullable = true),
        ColumnMap(ColumnName = "ASSISTANCE_CD", DbType = System.Data.DbType.String),
        ]
        public string AssistanceCode
        {
            get
            {
                return this._assistanceCode;
            }
            set
            {
                this._assistanceCode = value;
            }
        }

    }
}