/******************************************
 * Code generated by GEB (Version: 2.2.0.0)
 * Template: Sistran.Core.Application.Quotation.QuotationAgent.dict v1.0
 * FileSize=6366 Header=254 CRC=3952247772
 ******************************************/
using Sistran.Core.Framework;
using Sistran.Core.Framework.DAF;
using System;
using System.Collections;
using System.Collections.Generic;

namespace Sistran.Core.Application.Quotation.Entities
{
    /// <summary>
    /// Definición de entidad QuotationAgent.
    /// </summary>
    [
    PersistentClass("Sistran.Core.Application.Quotation.QuotationAgent.dict"),
    Serializable(),
    DescriptionKey("QUOTATION_AGENT_ENTITY"),
    TableMap(TableName = "QUOTATION_AGENT", Schema = "QUO"),
    ]
    public partial class QuotationAgent :
        BusinessObject2
    {
        #region static
        /// <summary>
        /// Propiedades públicas de la entidad.
        /// </summary>
        public static class Properties
        {
            public static readonly string QuotationId = "QuotationId";
            public static readonly string IndividualId = "IndividualId";
            public static readonly string AgentAgencyId = "AgentAgencyId";
            public static readonly string IsPrimary = "IsPrimary";
            public static readonly string IsOrgAgent = "IsOrgAgent";
        }

        /// <summary>
        /// Crea una clave primaria para una clase concreta.
        /// </summary>
        /// <param name="concreteClass">Clase concreta.</param>
        /// <param name="quotationId">Propiedad clave QuotationId.</param>
        /// <param name="individualId">Propiedad clave IndividualId.</param>
        /// <param name="agentAgencyId">Propiedad clave AgentAgencyId.</param>
        /// <returns>Clave primaria.</returns>
        protected static PrimaryKey InternalCreatePrimaryKey<T>(int quotationId, int individualId, int agentAgencyId)
        {
            Dictionary<string, object> keys = new Dictionary<string, object>();
            keys.Add(Properties.QuotationId, quotationId);
            keys.Add(Properties.IndividualId, individualId);
            keys.Add(Properties.AgentAgencyId, agentAgencyId);

            return new PrimaryKey<T>(keys);
        }

        /// <summary>
        /// Crea una clave primaria para esta clase.
        /// </summary>
        /// <param name="quotationId">Propiedad clave QuotationId.</param>
        /// <param name="individualId">Propiedad clave IndividualId.</param>
        /// <param name="agentAgencyId">Propiedad clave AgentAgencyId.</param>
        public static PrimaryKey CreatePrimaryKey(int quotationId, int individualId, int agentAgencyId)
        {
            return InternalCreatePrimaryKey<QuotationAgent>(quotationId, individualId, agentAgencyId);
        }
        #endregion

        //*** Object Attributes ********************************

        /// <summary>
        /// Atributo para la propiedad IsPrimary.
        /// </summary>
        private bool _isPrimary;
        /// <summary>
        /// Atributo para la propiedad IsOrgAgent.
        /// </summary>
        private bool _isOrgAgent;
        //*** Object Constructors ********************************

        /// <summary>
        /// Constructor de instancia de la clase en base a las propiedades claves.
        /// </summary>
        /// <param name="quotationId">QuotationId key property.</param>
        /// <param name="individualId">IndividualId key property.</param>
        /// <param name="agentAgencyId">AgentAgencyId key property.</param>
        public QuotationAgent(int quotationId, int individualId, int agentAgencyId) :
            this(QuotationAgent.CreatePrimaryKey(quotationId, individualId, agentAgencyId), null)
        {
        }

        /// <summary>
        /// Constructor de instancia de la clase en base a una clave primaria y a valores iniciales.
        /// </summary>
        /// <param name="key">
        /// Identificador de la instancia de la entidad.
        /// </param>
        /// <param name="initialValues">
        /// Valores para establecer el estado de la instancia.
        /// </param>
        public QuotationAgent(PrimaryKey key, IDictionary initialValues) :
            base(key, initialValues)
        {
        }

        /*** Object Properties ********************************/
        /// <summary>
        /// Devuelve o setea el valor de la propiedad QuotationId.
        /// </summary>
        /// <value>Propiedad QuotationId.</value>
        [
        DescriptionKey("QUOTATION_ID_PROPERTY"),
        PersistentProperty(IsKey = true),
        ColumnMap(ColumnName = "QUOTATION_ID", DbType = System.Data.DbType.String),
        ]
        public int QuotationId
        {
            get
            {
                return (int)this._primaryKey[Properties.QuotationId];
            }
            set
            {
                this._primaryKey[Properties.QuotationId] = value;
            }
        }

        /// <summary>
        /// Devuelve o setea el valor de la propiedad IndividualId.
        /// </summary>
        /// <value>Propiedad IndividualId.</value>
        [
        DescriptionKey("INDIVIDUAL_ID_PROPERTY"),
        PersistentProperty(IsKey = true),
        ColumnMap(ColumnName = "INDIVIDUAL_ID", DbType = System.Data.DbType.String),
        ]
        public int IndividualId
        {
            get
            {
                return (int)this._primaryKey[Properties.IndividualId];
            }
            set
            {
                this._primaryKey[Properties.IndividualId] = value;
            }
        }

        /// <summary>
        /// Devuelve o setea el valor de la propiedad AgentAgencyId.
        /// </summary>
        /// <value>Propiedad AgentAgencyId.</value>
        [
        DescriptionKey("AGENT_AGENCY_ID_PROPERTY"),
        PersistentProperty(IsKey = true),
        ColumnMap(ColumnName = "AGENT_AGENCY_ID", DbType = System.Data.DbType.String),
        ]
        public int AgentAgencyId
        {
            get
            {
                return (int)this._primaryKey[Properties.AgentAgencyId];
            }
            set
            {
                this._primaryKey[Properties.AgentAgencyId] = value;
            }
        }

        /// <summary>
        /// Devuelve o setea el valor de la propiedad IsPrimary.
        /// </summary>
        /// <value>Propiedad IsPrimary.</value>
        [
        DescriptionKey("IS_PRIMARY_PROPERTY"),
        PersistentProperty(),
        ColumnMap(ColumnName = "IS_PRIMARY", DbType = System.Data.DbType.String),
        ]
        public bool IsPrimary
        {
            get
            {
                return this._isPrimary;
            }
            set
            {
                this._isPrimary = value;
            }
        }

        /// <summary>
        /// Devuelve o setea el valor de la propiedad IsOrgAgent.
        /// </summary>
        /// <value>Propiedad IsOrgAgent.</value>
        [
        DescriptionKey("IS_ORG_AGENT_PROPERTY"),
        PersistentProperty(),
        ColumnMap(ColumnName = "IS_ORG_AGENT", DbType = System.Data.DbType.String),
        ]
        public bool IsOrgAgent
        {
            get
            {
                return this._isOrgAgent;
            }
            set
            {
                this._isOrgAgent = value;
            }
        }

    }
}