//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistran.Core.Application.UnderwritingParamService.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sistran.Core.Application.UnderwritingParamService.Resources.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The description can not contain more than 50 characters.
        /// </summary>
        internal static string PaymentMethodModelDescError {
            get {
                return ResourceManager.GetString("PaymentMethodModelDescError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The description can not be empty.
        /// </summary>
        internal static string PaymentMethodModelDescNullError {
            get {
                return ResourceManager.GetString("PaymentMethodModelDescNullError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The short description can not contain more than 30 characters.
        /// </summary>
        internal static string PaymentMethodModelSDescError {
            get {
                return ResourceManager.GetString("PaymentMethodModelSDescError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The short description can not be empty.
        /// </summary>
        internal static string PaymentMethodModelSDescNullError {
            get {
                return ResourceManager.GetString("PaymentMethodModelSDescNullError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La descripción no puede contener mas de 50 caracteres.
        /// </summary>
        internal static string ValidateDescriptionCarateresExpense {
            get {
                return ResourceManager.GetString("ValidateDescriptionCarateresExpense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La descripción no puede estar vacia.
        /// </summary>
        internal static string ValidateDescriptionExpense {
            get {
                return ResourceManager.GetString("ValidateDescriptionExpense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La descripción no puede estar vacia.
        /// </summary>
        internal static string ValidateDescriptionRateType {
            get {
                return ResourceManager.GetString("ValidateDescriptionRateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La descripción no puede estar vacia.
        /// </summary>
        internal static string ValidateDescriptionRuleSet {
            get {
                return ResourceManager.GetString("ValidateDescriptionRuleSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La descripcion corta no puede contener mas de 15 caracteres.
        /// </summary>
        internal static string ValidateSmallDescriptionCaracteresExpense {
            get {
                return ResourceManager.GetString("ValidateSmallDescriptionCaracteresExpense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La descripcion corta no puede estar vacia.
        /// </summary>
        internal static string ValidateSmallDescriptionExpense {
            get {
                return ResourceManager.GetString("ValidateSmallDescriptionExpense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La descripción no puede contener mas de 50 caracteres.
        /// </summary>
        internal static string ValidateSmallDescriptionRateType {
            get {
                return ResourceManager.GetString("ValidateSmallDescriptionRateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La descripción no puede contener mas de 50 caracteres.
        /// </summary>
        internal static string ValidateSmallDescriptionRuleSet {
            get {
                return ResourceManager.GetString("ValidateSmallDescriptionRuleSet", resourceCulture);
            }
        }
    }
}
